### ISSUE TITLE
Issue #1000

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#1000]
Woooh ! :confetti_ball: :tada: :cocktail:

**Comment by byneoseb** [comment]
Happy @Aquaj  :+1:

**Comment by burisu** [comment]
I can't reproduce, have you more details?

**Comment by Aquaj** [comment]
Launch a github project, get 999 (pull request or issue)s. Add an issue. *Voilà*.

**Comment by burisu** [comment]
Thanks!

**Comment by Aquaj** [comment]
1000th closed issue. Woohoo! :confetti_ball: :tada: :cocktail:
