### ISSUE TITLE
Gem to manage ENV variables ?

### ISSUE THREAD

**Issue by jonathanpa** [ekylibre/ekylibre#1008]
To setup oauth as client, I use several environment variables such as `EKYLIBRE_OAUTH2_CLIENT_ID`, `EKYLIBRE_OAUTH2_CLIENT_SECRET`, ...

For the moment I set all with my `rails server` command, but do you use something like `dotenv`, `figaro` or something else to write all in a file ?

**Comment by burisu** [comment]
Made with figaro sometimes ago
