### ISSUE TITLE
Add a way to set automatic naming of plant

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1018]
Users need to set precisely the automatic naming of plant after a sowing intervention.
For the moment, the new name can be enter in the intervention but it's too long (and error source) to do it for every plant.

**Comment by EmmaDorie** [comment]
Now, the automatic naming of plant after a sowing intervention doesn't work anymore.
The default name is the last name registered (even if it was on an other land parcel) with a number.

**Comment by burisu** [comment]
The bug part will be fixed by #1703 for now.
