### ISSUE TITLE
Impossible to delete sales containing a suscription.

### ISSUE THREAD

**Issue by Estellefelices** [ekylibre/ekylibre#1020]
You can not delete a sales.
![capture du 2016-08-19 14-39-58](https://cloud.githubusercontent.com/assets/21124756/17812452/74b51aa0-6627-11e6-8700-d98b38a94919.png)
![capture du 2016-08-19 14-40-14](https://cloud.githubusercontent.com/assets/21124756/17812454/76ba7958-6627-11e6-8dbc-ada55ddd2aab.png)
![capture du 2016-08-19 14-40-25](https://cloud.githubusercontent.com/assets/21124756/17812455/76d6534e-6627-11e6-8acc-f4df534cb78e.png)

**Comment by PH64** [comment]
It seems the bug is only on sales of subscription
