### ISSUE TITLE
all data (text and pictures) lost for the wiki web page https://wiki.ekylibre.org/fr/guides/import-inventaire-animaux-ede-bretagne

### ISSUE THREAD

**Issue by yannick56** [ekylibre/ekylibre#1025]
Hello,

All the data are lost for the wiki web page https://wiki.ekylibre.org/fr/guides/import-inventaire-animaux-ede-bretagne.
The web page is empty, there is only the summary in the right panel.
Do you have a backup to restore ?

PS: a lot of others wiki web pages seems OK after the wiki web site down.

Thank you.

**Comment by yannick56** [comment]
add a blank line and save the page fix the blank page problem.
very strange problem.

**Comment by EmmaDorie** [comment]
Hello,

Yes it was a strange problem ! That's good if all is ok now ...
