### ISSUE TITLE
No way to import GeoJSON or KML polygon in activity production

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1034]
When selecting a file to import with geojson or kml format, no polygon are visible in activity production map.

See bellow for more details

![geojson2](https://cloud.githubusercontent.com/assets/1838491/18005681/cd2c5102-6b9b-11e6-9ef7-278cc5b5cff6.png)

![geojson1](https://cloud.githubusercontent.com/assets/1838491/18005683/cd4bda5e-6b9b-11e6-8a8c-041c730f3a2e.png)

**Comment by Nyxelio** [comment]
Could you send your file ?

**Comment by PH64** [comment]
Import a kml or geojson in creation work , but don't work in modification
