### ISSUE TITLE
Child components must have diffrent name

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1060]
In product variants, child component can't have the same name, even if the child component's variant is the same.

**Comment by burisu** [comment]
We need to add tests on this validation with nested params on product nature variant creation into `ProductNatureVariantComponentTest`.

**Comment by burisu** [comment]
I re-read the description and I understand it's not a bug. For now, component children must have different to ensure that user can't be wrong when selecting one in the intervention form.
