### ISSUE TITLE
Crumbs aren't visible

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1072]
In 2.4.x version, crumbs are no longer visible and accessible. Or maybe it's a problem of synchronisation from Zero

**Comment by burisu** [comment]
I have my crumbs in my screens. I think it's a Zeo sync issue

**Comment by PierreBougon** [comment]
It is not an issue, GPS tracking is deactivated by default since 0.4. You need to accept the fact you will be tracked by zero to use GPS.

To activate GPS you need to go on settings -> enable GPS
