### ISSUE TITLE
Parcel invoicing fails due to a not updateable record

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1102]
An Ekylibre::Record::RecordNotUpdateable occurred in parcels#invoice:

  Record cannot be updated
  app/models/parcel.rb:434:in `block (3 levels) in convert_to_purchase'

**Comment by igkyab** [comment]
This error is happened again in production with the details below : 

An Ekylibre::Record::RecordNotUpdateable occurred in parcels#invoice:

  Record cannot be updated
  app/models/parcel.rb:486:in `block (3 levels) in convert_to_purchase'


  * Parameters : {"_method"=>"post", "controller"=>"backend/parcels", "action"=>"invoice", "id"=>"59"}

**Comment by burisu** [comment]
No news, I close for now.
