### ISSUE TITLE
product_nature_variants#incorporate (RuntimeError)

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1114]
A RuntimeError occurred in product_nature_variants#incorporate:

  Cannot import variant "seedling": Dérivé de est invalide
  app/models/product_nature_variant.rb:424:in `import_from_nomenclature'

**Comment by igkyab** [comment]
I can't reproduce the problem. I import many variants but impossible to throw the error.

**Comment by burisu** [comment]
Can't reproduce too

**Comment by igkyab** [comment]
Can't reproduce this bug. Add a unit test for this.
