### ISSUE TITLE
Geometry contains non-closed rings

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1116]
An ActiveRecord::StatementInvalid occurred in plots#create:

  PG::InternalError: ERREUR:  geometry contains non-closed rings
ASTUCE : "...4.26836132559357 48.725323338140235))" <-- parse error at position 321 within geometry
: SELECT ST_AsEWKT(ST_GeomFromEWKT('SRID=4326;MULTIPOLYGON(((4.26779784718567 48.72578546861472, 4.268397357079105 48.726164047547485, 4.268241294226181 48.72629192037439, 4.27206733827004 48.728875012692505, 4.27220638062551 48.72887265790673, 4.274510690266568 48.72759253196529, 4.269626977162673 48.724300337374224, 4.26836132559357 48.725323338140235)))'))
  lib/charta.rb:85:in `select_value'

**Comment by igkyab** [comment]
It's problem with keyfield, the first and last points of Multipolygon function are not equals.

We will send us an email.

**Comment by igkyab** [comment]
Same as #1197

**Comment by tudro** [comment]
Hello,

This is caused by the daplos data we receive that doesn't have last point = first point. I will change what we send to EK to fix this. If you want, you can add that EK needs this in the docs for future reference (https://forge.ekylibre.com/projects/keyfield/wiki/APIv1#Set-all-plots).

**Comment by igkyab** [comment]
Hello,

Ok i change the docs with your comments. Thank you!

**Comment by igkyab** [comment]
This error not happen again. I closed this issue.
