### ISSUE TITLE
Undefined method 'round' for nil:NilClass on interventions#compute

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1118]
A NoMethodError occurred in interventions#compute:

  undefined method `round' for nil:NilClass
  lib/procedo/engine/intervention/quantified.rb:85:in `compute_value'

**Comment by Aquaj** [comment]
Very probably linked to/fixed by 5cfdc45.

**Comment by igkyab** [comment]
Maybe fixed with your commit. We can't see now if the problem is solved.
