### ISSUE TITLE
"ActionController::InvalidAuthenticityToken" sessions#create

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1122]
An ActionController::InvalidAuthenticityToken occurred in sessions#create:

  ActionController::InvalidAuthenticityToken
  config/initializers/apartment.rb:52:in `call'

**Comment by igkyab** [comment]
Same as #274

**Comment by igkyab** [comment]
Same error today

**Comment by Aquaj** [comment]
The only ones I can find are coming from the CIVAM demo which is outside of our jurisdiction. They're probably not yet up-to-date.

Did I miss some emails with this error coming from ekylibre instances?
