### ISSUE TITLE
products#create (ActiveRecord::AssociationTypeMismatch)

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1125]
An ActiveRecord::AssociationTypeMismatch occurred in products#create:

  ProductNatureVariant(#70227802832420) expected, got String(#70227675948920)
  app/models/product.rb:330:in `new_with_cast'

**Comment by burisu** [comment]
We need to check creation of product into dialog box

**Comment by Aquaj** [comment]
Creation of product seems to work no matter how hard I threw stuff at it.
The error has only appeared 4 times since June, to reopen when it'll happen again if we can get more info.

**Comment by PH64** [comment]
seems solve like #1203
