### ISSUE TITLE
loans#destroy "You cannot call create unless the parent is saved"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1138]
An ActiveRecord::RecordNotSaved occurred in loans#destroy:

  You cannot call create unless the parent is saved
  app/models/loan.rb:100:in `block in generate_repayments'

**Comment by thib44** [comment]
Resolved with :
https://github.com/ekylibre/ekylibre/commit/7cd9c3f03f5170dfaf4e719d1b30a1aef209c2fb
