### ISSUE TITLE
Intervention kanban top bar is not correctly displayed when i scroll down the page

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1141]
When i scroll down the page with the kanban board, i top bar with the columns name is not displayed correctly.

**Comment by igkyab** [comment]
I can't reproduce ce problem on the master branch. @EmmaDorie, you reproduce it if you are on master branch ?

**Comment by EmmaDorie** [comment]
I can't reproduce it again ... I close this issue for the moment.
