### ISSUE TITLE
sale_natures#create "super: no superclass method `[:payment_delay]'

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1159]
A NoMethodError occurred in sale_natures#create:

  super: no superclass method `[:payment_delay]' for #<SaleNature:0x007ff462796298>
  lib/delay.rb:166:in`rescue in validate_each'

**Comment by burisu** [comment]
Fixed by @Aquaj in 330c12975012699bcfc9f95eba4afd6f5fa888d2 (related to #1212), 6d2a2b16db9cd8515612ed52736f62979b339a7a, and bfa8064a55d7130abb08f5bd02b1c4b91c0f80c2.
