### ISSUE TITLE
No way to access to index page on Outgoing payments

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1163]
When trying to get /backend/outgoing_payment_modes
Then
NoMethodError in Backend::OutgoingPaymentModes#index
 Showing app/views/backend/outgoing_payment_modes/index.html.haml where line #3 raised:

undefined method `text' for "<div class=\"checkbox-false\"></div>":ActiveSupport::SafeBuffer

**Comment by jonathanpa** [comment]
Yes, I use `t.column :sepa`. I remember it was working at the very beginning but then I got the same error than you. See PR #1157 main comment and code comment here https://github.com/ekylibre/ekylibre/pull/1157/files#r82668709

**Comment by ionosphere** [comment]
Maybe because you use both column attribute and scope name "sepa".

**Comment by jonathanpa** [comment]
Fixed in this commit https://github.com/ekylibre/ekylibre/commit/65f9eb824483ac7a8d6e26a8646dace8ed86ced1
