### ISSUE TITLE
When IBAN has space, try to delete it before validate it.

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1164]
Try to delete space before validated IBAN or BIC field

![iban_strip](https://cloud.githubusercontent.com/assets/1838491/19198035/2520abfa-8cbd-11e6-9795-054ec309a82b.png)

**Comment by jonathanpa** [comment]
Fixed in this commit https://github.com/ekylibre/ekylibre/commit/b4a3b70efe6d15a137d80033abcc92e14fb32e5c
