### ISSUE TITLE
SEPA XML File is wrong on test

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1165]
Line 2 - message PAIN 001 not 003
pain.001.003.03
=> pain.001.001.03

Line 24 - ISO Date not Time
<ReqdExctnDt>2016-10-07T18:46:06+02:00</ReqdExctnDt> 
=> <ReqdExctnDt>2016-10-07</ReqdExctnDt> 

see http://www.mesfluxdepaiement.fr/testez-vos-fichiers-sepa
and https://xml-validator.nordea.lt/pain_validation/validate
for testing

[standard-credit_transfer-xml-v31-fr_0.pdf](https://github.com/ekylibre/ekylibre/files/516696/standard-credit_transfer-xml-v31-fr_0.pdf)

**Comment by jonathanpa** [comment]
Fixed in this commit https://github.com/ekylibre/ekylibre/commit/3da1d44e8069d394703d21cf7d4239839560d319
