### ISSUE TITLE
Purchase could be paid from many states not just on "order" state

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1166]
Allow to paid purchase on status like 'order' or 'invoice' not just 'order'.

![commande_on _validation](https://cloud.githubusercontent.com/assets/1838491/19198826/4cf2128c-8cc1-11e6-857c-02d29a442afe.png)

**Comment by jonathanpa** [comment]
Fix in this commit https://github.com/ekylibre/ekylibre/pull/1157/commits/f6dadf095d5c89881161f8f629999b59a5186798
