### ISSUE TITLE
product_nature_variants#create "Account is not configure for \"Confit. cit. java 240gr\".

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1172]
An ArgumentError occurred in product_nature_variants#create:

  Account is not configure for "Confit. cit. java 240gr". You have to check category first
  app/models/product_nature_variant.rb:210:in `create_unique_account'

**Comment by igkyab** [comment]
Same as #1167

**Comment by igkyab** [comment]
* Parameters : {"product_nature_variant"=>{"nature_id"=>"35", "variety"=>"product", "name"=>"Confit. cit. java 240gr", "work_number"=>"", "gtin"=>"", "active"=>"1", "unit_name"=>"Unité"}, "dialog"=>"dialog-1", "controller"=>"backend/product_nature_variants", "action"=>"create"}

**Comment by igkyab** [comment]
The errors is now displayed to the users with the commit e7a436f3714df9e66c1e50f68c4b41bf3d7e896c by @Aquaj

**Comment by PH64** [comment]
close as #1167
