### ISSUE TITLE
accounts#load "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1175]
An ActiveRecord::RecordInvalid occurred in accounts#load:

  Validations échouées : Nom a déjà été pris
  app/models/preference.rb:166:in `set!'

**Comment by Aquaj** [comment]
Fixed through direct action on instance.

More explanations for future reference:
The user had managed to have two records of the same global preference (`accounting_system`), which made it so each time one of the two records was updated, the validations kicked in and refused for lack of unicity => deadlock.

Notably one of the two preferences add its `creator/updater_id`s  set to `nil`.
