### ISSUE TITLE
cultivable_zones#create "getaddrinfo: Name or service not known"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1180]
A SocketError occurred in cultivable_zones#create:

  getaddrinfo: Name or service not known
  lib/ekylibre/hook.rb:15:in `call'

**Comment by igkyab** [comment]
Same as #1205

**Comment by igkyab** [comment]
* Parameters : {"cultivable_zone"=>{"name"=>"Dessous de la Maladrerie", "work_number"=>"2", "production_system_name"=>"intensive_farming", "soil_nature"=>"silty_clay_loam_soil", "farmer_id"=>"2", "owner_id"=>"", "description"=>"", "shape"=>"{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{\"internal_id\":1476368341391,\"removable\":true,\"name\":\"1-  Unnamed\"},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[3.3914455957710743,50.018325509042064],[3.391418773680925,50.019438834157675],[3.391402680426836,50.02001444414634],[3.3913919515907764,50.02124491662176],[3.393349964171648,50.02149307531881],[3.3933177776634693,50.02129661645603],[3.393655735999346,50.02132418967822],[3.3937522955238815,50.02080029575034],[3.393870312720537,50.02023158863797],[3.394079525023699,50.01942160021936],[3.3926847763359547,50.019435387370514],[3.3926150389015675,50.01927683489335],[3.392722327262163,50.019173430821965],[3.3927169628441334,50.01883908946812],[3.3923414535820484,50.01881496165153],[3.3923146314918995,50.018239337291796],[3.3914455957710743,50.018325509042064]]]}}]}"}, "commit"=>"Créer", "controller"=>"backend/cultivable_zones", "action"=>"create"}

**Comment by igkyab** [comment]
I can't reproduce the bug with the parameters of the two issues (#1205 and #1180) and with the interface for the create and delete actions.

@EmmaDorie you reproduce the bug ?

**Comment by PH64** [comment]
I can't reproduce
I have the opposite problem. see #1162

**Comment by igkyab** [comment]
@tudro i think it's a problem with the webhook url you specify. What do you think about it ?

**Comment by tudro** [comment]
Yes, it could be. We had one of our services moved to a different server and EK still had the old urls for the farms. I have told the guys how to fix this in production, so as far as I know it should be ok now.

**Comment by igkyab** [comment]
Not happen again. I closed the issue.
