### ISSUE TITLE
The owner of an account have to be transcode to latin characters

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1183]
When exporting SEPA XML, the owner of the account are not well transcode.
For example : "**Cédric** DUPONT" is in the file like "**Cdric** DUPONT"
line 26
<Nm>Cdric Dupont</Nm>

Is it possible to transcode with gsub method é,è to e and same thing for the others ?

**Comment by jonathanpa** [comment]
Fixed in commit https://github.com/ekylibre/ekylibre/commit/3be1d62013cc91aa9cbd0fd048dbdd29fc78d644
