### ISSUE TITLE
campaigns#destroy Cannot delete record because of dependent cap_statements

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1195]
An ActiveRecord::DeleteRestrictionError occurred in campaigns#destroy:

  Cannot delete record because of dependent cap_statements
  config/initializers/apartment.rb:52:in `call'

**Comment by igkyab** [comment]
* Parameters : {"_method"=>"delete", "redirect"=>"/backend/campaigns", "controller"=>"backend/campaigns", "action"=>"destroy", "id"=>"1"}

**Comment by igkyab** [comment]
Today, i have this error : 

An ActiveRecord::DeleteRestrictionError occurred in campaigns#destroy:

  Cannot delete record because of dependent activity_budgets
  config/initializers/apartment.rb:52:in `call'

**Comment by Aquaj** [comment]
Removed Frequent label. Bug happened only 3 times (27/8 - 11/10 - 25/10).

**Comment by burisu** [comment]
No news? I close
