### ISSUE TITLE
products#create ProductNatureVariant(#70065306835240) expected, got String(#70065208313720)

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1203]
An ActiveRecord::AssociationTypeMismatch occurred in products#create:

  ProductNatureVariant(#70065306835240) expected, got String(#70065208313720)
  app/models/product.rb:334:in `new_with_cast'
- Parameters : {"product"=>{"variant"=>"285"}, "dialog"=>"dialog-0", "controller"=>"backend/products", "action"=>"create"}

**Comment by Aquaj** [comment]
Removed label Frequent as the bug only happened 8 times since June.

**Comment by Aquaj** [comment]
Also, closing as it is a duplicate of #1125.
