### ISSUE TITLE
purchases#invoice "Unknown journal: (nil)"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1209]
An ArgumentError occurred in purchases#invoice:

  Unknown journal: (nil)
  lib/ekylibre/record/bookkeep.rb:39:in `journal_entry'
- Parameters : {"_method"=>"post", "controller"=>"backend/purchases", "action"=>"invoice", "id"=>"2"}

**Comment by burisu** [comment]
Fixed by f3843f2ea50878f629934f81022ac86e39fe335b
