### ISSUE TITLE
beehives#update "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1211]
An ActiveRecord::RecordInvalid occurred in beehives#update:

  Validations échouées : Nom a déjà été pris
  app/models/user.rb:214:in `prefer!'
- Parameters : {"boxes"=>{"0"=>{"cells"=>{"0"=>{"name"=>"last_movements", "type"=>"last_movements"}, "1"=>{"name"=>"last_incoming_parcels", "type"=>"last_incoming_parcels"}}}}, "controller"=>"backend/beehives", "action"=>"update", "id"=>"stock"}

**Comment by Aquaj** [comment]
Duplicate of #1729.
