### ISSUE TITLE
seedings#create PG::UndefinedColumn: ERREUR:  la colonne « iban » de la relation « entities » n'existe pas

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1213]
An ActiveRecord::StatementInvalid occurred in seedings#create:

  PG::UndefinedColumn: ERREUR:  la colonne « iban » de la relation « entities » n'existe pas
LIGNE 1 : ..., "full_name", "language", "currency", "country", "iban", "b...
                                                               ^
: INSERT INTO "entities" ("first_name", "last_name", "nature", "number", "full_name", "language", "currency", "country", "iban", "bank_identifier_code", "bank_account_holder_name", "supplier_payment_delay", "of_company", "created_at", "updated_at", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING "id"
  app/models/user.rb:149:in `block in class:User'

**Comment by burisu** [comment]
Same as #1274
