### ISSUE TITLE
Impossible to change currency in settings

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1216]
In settings, add a field to set currency.

**Comment by PH64** [comment]
Every parameters of the step 1 of first-run aren't record in configuration 
![capture du 2016-10-14 16-24-55](https://cloud.githubusercontent.com/assets/12525665/19391051/0d126d82-922b-11e6-915b-28e311c7ad68.png)

State, language and money aren't in configuration

**Comment by burisu** [comment]
We can't change currency as easy as in 0e041f7, because all absolute values must be updated in journal_entries and account_balances at least. Moreover it's not in user preference that we should find this.

**Comment by burisu** [comment]
Fixed by 3b6f0b52c8befb42084848a42a71c1515912a2c9.
