### ISSUE TITLE
interventions#compute (JSON::ParserError) 757: unexpected token at 'SRID=4326;MULTIPOLYGON

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1219]
A JSON::ParserError occurred in interventions#compute:

  757: unexpected token at 'SRID=4326;MULTIPOLYGON(((-0.187353680397977 43.3369029998329,-0.187097697724696 43.3370401125112,-0.186963484884268 43.3370917111601,-0.186807568533319 43.3370312160383,-0.186633831718619 43.3370172795413,-0.186564325932375 43.3369407179962,-0.186537603496443 43.3366788781375,-0.185801799649974 43.3366400776426,-0.185726597471349 43.3366375289677,-0.185684899778635 43.336650667962,-0.18565728531235 43.3366824491541,-0.185809404399514 43.3372496748619,-0.185849088645187 43.3373771394509,-0.185882652050321 43.3375119311779,-0.185966859493711 43.3377953031135,-0.186009641455802 43.3378607421656,-0.186064929916142 43.3379162836324,-0.186458160292063 43.337878815631,-0.18752846153964 43.3378289909215,-0.187530691762934 43.3378461123942,-0.187573944121179 43.3381235331905,-0.187597672101257 43.3382456111408,-0.188435925382557 43.3381177896813,-0.188447211221674 43.3381168896654,-0.188456277808386 43.3381157849946,-0.188542505779819 43.3381018890377,-0.190275849616362 43.3379849536534,-0.189790624758659 43.3372516473443,-0.189460515975952 43.3373677424569,-0.188934803009033 43.3369931803044,-0.188591480255127 43.3368605223214,-0.187175777750594 43.3367112827963,-0.187353680397977 43.3369029998329)))'
  lib/charta/geo_json.rb:8:in `initialize'

**Comment by Aquaj** [comment]
Happened again today (17/02/17). Stack trace is identical, but the token is now position 784 instead of 756.
