### ISSUE TITLE
dashboards#search (ActionView::Template::Error) "translation data {:zero=>\"No se han encontrado resultados\...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1223]
An ActionView::Template::Error occurred in dashboards#search:

  translation data {:zero=>"No se han encontrado resultados"} can not be used with :count => 10
  config/initializers/10-patches.rb:164:in `tl'

**Comment by burisu** [comment]
Pluralization data must be complete or empty but not partial.
