### ISSUE TITLE
attachments#create Syntax Warning: May not be a PDF file (continuing anyway)

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1229]
A Docsplit::ExtractionFailed occurred in attachments#create:

  Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

  app/controllers/backend/attachments_controller.rb:12:in `create'

**Comment by Nyxelio** [comment]
Due to a corrupted file, but should fail properly.
