### ISSUE TITLE
address is two time present in entities show view

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1231]
We have to remove the first ?!

![address_bug](https://cloud.githubusercontent.com/assets/1838491/19465495/009b3174-9505-11e6-9479-41b4503e4af9.png)

**Comment by burisu** [comment]
We have to keep the first ones. A merge conflict should have resolved too quickly. Restored as wanted by 17ff389997468d9c3d915ec284decc13d5e1054d.
