### ISSUE TITLE
Creation new cultivable area

### ISSUE THREAD

**Issue by ctouzouli** [ekylibre/ekylibre#1245]
Version: Ekylibre 2.13.2
Instance: https://fermedetest81.ekylibre.farm
This instance is synchronized with Keyfield
I want to create a new cultivable area: (https://fermedetest81.ekylibre.farm/backend/cultivable-zones/new)
![image](https://cloud.githubusercontent.com/assets/21262265/19553558/f74b7ca8-96b4-11e6-89b4-32e6e81f42a8.png)

I have this error: 
![image](https://cloud.githubusercontent.com/assets/21262265/19553690/7e1d3aaa-96b5-11e6-9890-0da2faf4d779.png)

**Comment by ionosphere** [comment]
OK. Fix it.

**Comment by ctouzouli** [comment]
I test again: 20/10/2016 16:00, there is the same problem
