### ISSUE TITLE
Locales are not correctly set after first run

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1257]
When making a first run, nothing appends.

![bug_first_run_locales](https://cloud.githubusercontent.com/assets/1838491/19649313/a4c70f7a-9a05-11e6-89e0-c88a879d9752.png)

**Comment by Nyxelio** [comment]
This occurs when trying to import an 2016 cap statement. Fixed.

**Comment by PH64** [comment]
Could you test with 2015 cap statement ? I think I have the same problem on my tests instance

**Comment by Nyxelio** [comment]
Have you tried with your 2016 cap statement ? First run now relies on this file instead of 2015.

**Comment by PH64** [comment]
I try with 2015 and 2016 cap statement and I don't have cultivable zone in Ekylibre

**Comment by Nyxelio** [comment]
Thanks @PH64, I check that.

**Comment by Nyxelio** [comment]
Should be solved on the next release

**Comment by PH64** [comment]
Same problem with release 2.14.1 : CAP statement isn't loaded

**Comment by PH64** [comment]
Seems work in 2.15.0
