### ISSUE TITLE
telepac_files#upload (Encoding::UndefinedConversionError) "\"\\x92\" from ASCII-8BIT to UTF-8"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1263]
An Encoding::UndefinedConversionError occurred in telepac_files#upload:

  "\x92" from ASCII-8BIT to UTF-8
  config/initializers/apartment.rb:52:in `call'

**Comment by PH64** [comment]
User used a (shp) zip file, instead of using a xml file...
