### ISSUE TITLE
parcels#give (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Parcel"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1265]
An ActiveRecord::StaleObjectError occurred in parcels#give:

  Attempted to update a stale object: Parcel
  app/models/parcel.rb:341:in `give'

**Comment by igkyab** [comment]
Same error type with #1189 ?

**Comment by igkyab** [comment]
Today (v. 2.16.0) : 

An ActiveRecord::StaleObjectError occurred in parcels#give:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

**Comment by burisu** [comment]
No news? I close
