### ISSUE TITLE
interventions#compute (NoMethodError) "undefined method `get' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1266]
A NoMethodError occurred in interventions#compute:

  undefined method `'get' for nil:NilClass
  lib/procedo/engine/interpreter.rb:127:in 'run'`

**Comment by Aquaj** [comment]
Happened only 4 times (for a total of 10 exception mails) since June (29/6 - 29/9 - 25/10 - 2/10). As such, removed label Frequent.
