### ISSUE TITLE
campaigns#open (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERREUR: la valeur d'une clé dupliquée ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1273]
An ActiveRecord::RecordNotUnique occurred in campaigns#open:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_activity_budgets_on_activity_id_and_campaign_id »
DÉTAIL : La clé « (activity_id, campaign_id)=(1, 1) » existe déjà.
: INSERT INTO "activity_budgets" ("campaign_id", "activity_id", "currency", "updater_id", "created_at", "updated_at", "creator_id", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
  app/controllers/backend/campaigns_controller.rb:57:in `open'

**Comment by igkyab** [comment]
Related with the 2.14.1 production deployment ? This error comming when we do the deployment (14H16)

**Comment by burisu** [comment]
Not sure. A user find a way to create 2 budgets for a given campaign and a given activity

**Comment by burisu** [comment]
No news? I close
