### ISSUE TITLE
interventions#index (ActionView::Template::Error) "PG::UndefinedColumn: ERREUR: la colonne interventions.re...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1274]
An ActionView::Template::Error occurred in interventions#index:

  PG::UndefinedColumn: ERREUR:  la colonne interventions.request_compliant n'existe pas
LIGNE 1 : ...24, "interventions"."journal_entry_id" AS t0_r25, "intervent...
                                                               ^
: SELECT "interventions"."id" AS t0_r0, "interventions"."issue_id" AS t0_r1, "interventions"."prescription_id" AS t0_r2, "interventions"."procedure_name" AS t0_r3, "interventions"."state" AS t0_r4, "interventions"."started_at" AS t0_r5, "interventions"."stopped_at" AS t0_r6, "interventions"."created_at" AS t0_r7, "interventions"."updated_at" AS t0_r8, "interventions"."creator_id" AS t0_r9, "interventions"."updater_id" AS t0_r10, "interventions"."lock_version" AS t0_r11, "interventions"."event_id" AS t0_r12, "interventions"."number" AS t0_r13, "interventions"."description" AS t0_r14, "interventions"."working_duration" AS t0_r15, "interventions"."whole_duration" AS t0_r16, "interventions"."actions" AS t0_r17, "interventions"."custom_fields" AS t0_r18, "interventions"."nature" AS t0_r19, "interventions"."request_intervention_id" AS t0_r20, "interventions"."trouble_encountered" AS t0_r21, "interventions"."trouble_description" AS t0_r22, "interventions"."accounted_at" AS t0_r23, "interventions"."currency" AS t0_r24, "interventions"."journal_entry_id" AS t0_r25, "interventions"."request_compliant" AS t0_r26, "intervention_parameters"."id" AS t1_r0, "intervention_parameters"."intervention_id" AS t1_r1, "intervention_parameters"."product_id" AS t1_r2, "intervention_parameters"."variant_id" AS t1_r3, "intervention_parameters"."quantity_population" AS t1_r4, "intervention_parameters"."reference_name" AS t1_r5, "intervention_parameters"."position" AS t1_r6, "intervention_parameters"."created_at" AS t1_r7, "intervention_parameters"."updated_at" AS t1_r8, "intervention_parameters"."creator_id" AS t1_r9, "intervention_parameters"."updater_id" AS t1_r10, "intervention_parameters"."lock_version" AS t1_r11, "intervention_parameters"."working_zone" AS t1_r12, "intervention_parameters"."event_participation_id" AS t1_r13, "intervention_parameters"."outcoming_product_id" AS t1_r14, "intervention_parameters"."type" AS t1_r15, "intervention_parameters"."new_container_id" AS t1_r16, "intervention_parameters"."new_group_id" AS t1_r17, "intervention_parameters"."new_variant_id" AS t1_r18, "intervention_parameters"."quantity_handler" AS t1_r19, "intervention_parameters"."quantity_value" AS t1_r20, "intervention_parameters"."quantity_unit_name" AS t1_r21, "intervention_parameters"."quantity_indicator_name" AS t1_r22, "intervention_parameters"."group_id" AS t1_r23, "intervention_parameters"."new_name" AS t1_r24, "intervention_parameters"."component_id" AS t1_r25, "intervention_parameters"."assembly_id" AS t1_r26, "intervention_parameters"."currency" AS t1_r27, "intervention_parameters"."unit_pretax_stock_amount" AS t1_r28 FROM "interventions" LEFT OUTER JOIN "intervention_parameters" ON "intervention_parameters"."intervention_id" = "interventions"."id" AND "intervention_parameters"."type" IN ('InterventionDoer') WHERE (interventions.nature = 'request' AND interventions.request_intervention_id IS NULL)  ORDER BY "interventions"."started_at" DESC
  app/helpers/backend/interventions_helper.rb:4:in `add_taskboard_tasks'

**Comment by igkyab** [comment]
Related with the 2.14.1 production deployment ? This error comming when we do the deployment (14H54)

**Comment by burisu** [comment]
Yep, production bug

**Comment by igkyab** [comment]
Received again this email today.

**Comment by burisu** [comment]
No news
