### ISSUE TITLE
custom_field_choices#edit (ActionView::Template::Error) "No route matches {:action=>\"export\", :controller=...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1278]
An ActionView::Template::Error occurred in custom_field_choices#edit:

  No route matches {:action=>"export", :controller=>"backend/entities", :id=>"1"}
  app/helpers/backend/helps_helper.rb:130:in `block in wikize'

**Comment by burisu** [comment]
Duplicate of #1256 .
