### ISSUE TITLE
last_movements_cells#show (ActionView::Template::Error) "PG::UndefinedColumn: ERREUR: la colonne interventi...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1279]
An ActionView::Template::Error occurred in last_movements_cells#show:

  PG::UndefinedColumn: ERREUR:  la colonne interventions.request_compliant n'existe pas
LIGNE 1 : ...24, "interventions"."journal_entry_id" AS t2_r25, "intervent...
                                                               ^
: SELECT  "product_movements"."id" AS t0_r0, "product_movements"."product_id" AS t0_r1, "product_movements"."intervention_id" AS t0_r2, "product_movements"."originator_id" AS t0_r3, "product_movements"."originator_type" AS t0_r4, "product_movements"."delta" AS t0_r5, "product_movements"."population" AS t0_r6, "product_movements"."started_at" AS t0_r7, "product_movements"."stopped_at" AS t0_r8, "product_movements"."created_at" AS t0_r9, "product_movements"."updated_at" AS t0_r10, "product_movements"."creator_id" AS t0_r11, "product_movements"."updater_id" AS t0_r12, "product_movements"."lock_version" AS t0_r13, "products"."id" AS t1_r0, "products"."type" AS t1_r1, "products"."name" AS t1_r2, "products"."number" AS t1_r3, "products"."variant_id" AS t1_r4, "products"."nature_id" AS t1_r5, "products"."category_id" AS t1_r6, "products"."initial_born_at" AS t1_r7, "products"."initial_dead_at" AS t1_r8, "products"."initial_container_id" AS t1_r9, "products"."initial_owner_id" AS t1_r10, "products"."initial_enjoyer_id" AS t1_r11, "products"."initial_population" AS t1_r12, "products"."initial_father_id" AS t1_r13, "products"."initial_mother_id" AS t1_r14, "products"."variety" AS t1_r15, "products"."derivative_of" AS t1_r16, "products"."tracking_id" AS t1_r17, "products"."fixed_asset_id" AS t1_r18, "products"."born_at" AS t1_r19, "products"."dead_at" AS t1_r20, "products"."description" AS t1_r21, "products"."picture_file_name" AS t1_r22, "products"."picture_content_type" AS t1_r23, "products"."picture_file_size" AS t1_r24, "products"."picture_updated_at" AS t1_r25, "products"."identification_number" AS t1_r26, "products"."work_number" AS t1_r27, "products"."address_id" AS t1_r28, "products"."parent_id" AS t1_r29, "products"."default_storage_id" AS t1_r30, "products"."created_at" AS t1_r31, "products"."updated_at" AS t1_r32, "products"."creator_id" AS t1_r33, "products"."updater_id" AS t1_r34, "products"."lock_version" AS t1_r35, "products"."initial_shape" AS t1_r36, "products"."person_id" AS t1_r37, "products"."initial_geolocation" AS t1_r38, "products"."uuid" AS t1_r39, "products"."initial_movement_id" AS t1_r40, "products"."custom_fields" AS t1_r41, "products"."team_id" AS t1_r42, "interventions"."id" AS t2_r0, "interventions"."issue_id" AS t2_r1, "interventions"."prescription_id" AS t2_r2, "interventions"."procedure_name" AS t2_r3, "interventions"."state" AS t2_r4, "interventions"."started_at" AS t2_r5, "interventions"."stopped_at" AS t2_r6, "interventions"."created_at" AS t2_r7, "interventions"."updated_at" AS t2_r8, "interventions"."creator_id" AS t2_r9, "interventions"."updater_id" AS t2_r10, "interventions"."lock_version" AS t2_r11, "interventions"."event_id" AS t2_r12, "interventions"."number" AS t2_r13, "interventions"."description" AS t2_r14, "interventions"."working_duration" AS t2_r15, "interventions"."whole_duration" AS t2_r16, "interventions"."actions" AS t2_r17, "interventions"."custom_fields" AS t2_r18, "interventions"."nature" AS t2_r19, "interventions"."request_intervention_id" AS t2_r20, "interventions"."trouble_encountered" AS t2_r21, "interventions"."trouble_description" AS t2_r22, "interventions"."accounted_at" AS t2_r23, "interventions"."currency" AS t2_r24, "interventions"."journal_entry_id" AS t2_r25, "interventions"."request_compliant" AS t2_r26, "containers_product_movements"."id" AS t3_r0, "containers_product_movements"."type" AS t3_r1, "containers_product_movements"."name" AS t3_r2, "containers_product_movements"."number" AS t3_r3, "containers_product_movements"."variant_id" AS t3_r4, "containers_product_movements"."nature_id" AS t3_r5, "containers_product_movements"."category_id" AS t3_r6, "containers_product_movements"."initial_born_at" AS t3_r7, "containers_product_movements"."initial_dead_at" AS t3_r8, "containers_product_movements"."initial_container_id" AS t3_r9, "containers_product_movements"."initial_owner_id" AS t3_r10, "containers_product_movements"."initial_enjoyer_id" AS t3_r11, "containers_product_movements"."initial_population" AS t3_r12, "containers_product_movements"."initial_father_id" AS t3_r13, "containers_product_movements"."initial_mother_id" AS t3_r14, "containers_product_movements"."variety" AS t3_r15, "containers_product_movements"."derivative_of" AS t3_r16, "containers_product_movements"."tracking_id" AS t3_r17, "containers_product_movements"."fixed_asset_id" AS t3_r18, "containers_product_movements"."born_at" AS t3_r19, "containers_product_movements"."dead_at" AS t3_r20, "containers_product_movements"."description" AS t3_r21, "containers_product_movements"."picture_file_name" AS t3_r22, "containers_product_movements"."picture_content_type" AS t3_r23, "containers_product_movements"."picture_file_size" AS t3_r24, "containers_product_movements"."picture_updated_at" AS t3_r25, "containers_product_movements"."identification_number" AS t3_r26, "containers_product_movements"."work_number" AS t3_r27, "containers_product_movements"."address_id" AS t3_r28, "containers_product_movements"."parent_id" AS t3_r29, "containers_product_movements"."default_storage_id" AS t3_r30, "containers_product_movements"."created_at" AS t3_r31, "containers_product_movements"."updated_at" AS t3_r32, "containers_product_movements"."creator_id" AS t3_r33, "containers_product_movements"."updater_id" AS t3_r34, "containers_product_movements"."lock_version" AS t3_r35, "containers_product_movements"."initial_shape" AS t3_r36, "containers_product_movements"."person_id" AS t3_r37, "containers_product_movements"."initial_geolocation" AS t3_r38, "containers_product_movements"."uuid" AS t3_r39, "containers_product_movements"."initial_movement_id" AS t3_r40, "containers_product_movements"."custom_fields" AS t3_r41, "containers_product_movements"."team_id" AS t3_r42 FROM "product_movements" LEFT OUTER JOIN "products" ON "products"."id" = "product_movements"."product_id" LEFT OUTER JOIN "interventions" ON "interventions"."id" = "product_movements"."intervention_id" LEFT OUTER JOIN "products" "products_product_movements_join" ON "products_product_movements_join"."id" = "product_movements"."product_id" LEFT OUTER JOIN "product_localizations" ON "product_localizations"."product_id" = "products_product_movements_join"."id" AND ("product_localizations"."started_at" <= '2016-10-27 19:16:06.830559' AND ("product_localizations"."stopped_at" IS NULL OR "product_localizations"."stopped_at" > '2016-10-27 19:16:06.830559')) LEFT OUTER JOIN "products" "containers_product_movements" ON "containers_product_movements"."id" = "product_localizations"."container_id"  ORDER BY "product_movements"."started_at" DESC LIMIT 10 OFFSET 0
  app/views/backend/cells/last_movements_cells/show.html.haml:1:in `_app_views_backend_cells_last_movements_cells_show_html_haml___1700004825675473555_69983957802140'

**Comment by burisu** [comment]
Already fixed. Production bug.

**Comment by igkyab** [comment]
Received again this email today.

**Comment by burisu** [comment]
Still production bug. Re-fixed
