### ISSUE TITLE
Intervention tracking in activities not linked to activities

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#1281]
v2.15.0

In **Production / Activities**, some check marks should be link to relevant interventions.
Some of the are not in the activity period and are linked to nothing...

![ekylibre_acti](https://cloud.githubusercontent.com/assets/17082331/19802960/8d2e168e-9d06-11e6-903c-386155f5014b.jpg)

**Comment by burisu** [comment]
Bug link to TargetDistribution...
