### ISSUE TITLE
Parcel price

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1284]
Unit price is replaced by analysis
input price is missing
![image](https://cloud.githubusercontent.com/assets/23054955/19808436/2c212d58-9d25-11e6-8b50-51c95d36d6f5.png)

**Comment by burisu** [comment]
Shift is fixed. I am not sure that price is missing, because it seems to me that we aren't supposed to set prices on outgoing parcels. @ionosphere, @AntoineGrz, @Aquaj, can you confirm that assertion?

**Comment by AnneKappy** [comment]
Solved with 2.25.0
