### ISSUE TITLE
entities#index (ActionView::Template::Error) "PG::UndefinedColumn: ERREUR: la colonne entities.supplier_pay...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1293]
An ActionView::Template::Error occurred in entities#index:

  PG::UndefinedColumn: ERREUR:  la colonne entities.supplier_payment_mode_id n'existe pas
LIGNE 1 : ...ier_code" AS t0_r48, "entities"."iban" AS t0_r49, "entities"...

**Comment by Aquaj** [comment]
Came from a Shepherd bug. Fixed on Shepherd: closing this.
