### ISSUE TITLE
entities#show (ActionView::Template::Error) "PG::UndefinedTable: ERREUR: la relation « contracts » n'existe...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1294]
An ActionView::Template::Error occurred in entities#show:

  PG::UndefinedTable: ERREUR:  la relation « contracts » n'existe pas
LIGNE 1 : SELECT COUNT(*) FROM "contracts" WHERE "contracts"."supplier...
                               ^
: SELECT COUNT(*) FROM "contracts" WHERE "contracts"."supplier_id" = $1
  app/views/backend/entities/show.html.haml:153:in `block (3 levels) in _app_views_backend_entities_show_html_haml__2874662092188803892_69983907443420'

**Comment by Aquaj** [comment]
Came from a Shepherd bug. Fixed on Shepherd: closing this.
