### ISSUE TITLE
parcels#index (ActionView::Template::Error) "PG::UndefinedColumn: ERREUR: la colonne parcels.responsible_id...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1295]
An ActionView::Template::Error occurred in parcels#index:

  PG::UndefinedColumn: ERREUR:  la colonne parcels.responsible_id n'existe pas
LIGNE 1 : ...OM "users" WHERE "users"."id" IN (SELECT DISTINCT "parcels"....
                                                               ^
: SELECT COUNT(*) FROM "users" WHERE "users"."id" IN (SELECT DISTINCT "parcels"."responsible_id" FROM "parcels")
  app/views/backend/parcels/index.html.haml:17:in `block in _app_views_backend_parcels_index_html_haml__4161649845536286773_69983835276820'

**Comment by Aquaj** [comment]
Came from a Shepherd bug. Fixed on Shepherd: closing this.
