### ISSUE TITLE
product_nature_variants#index (ActionView::Template::Error) "PG::UndefinedColumn: ERREUR: la colonne parcel...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1297]
An ActionView::Template::Error occurred in product_nature_variants#index:

  PG::UndefinedColumn: ERREUR:  la colonne parcel_items.unit_pretax_amount n'existe pas
LIGNE 1 : ...rcel_items"."unit_pretax_stock_amount" AS t1_r24, "parcel_it...

**Comment by Aquaj** [comment]
Came from a Shepherd bug. Fixed on Shepherd: closing this.
