### ISSUE TITLE
purchases#update (NoMethodError) "undefined method `to_date' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1301]
A NoMethodError occurred in purchases#update:

  undefined method `to_date' for nil:NilClass
  app/models/purchase_item.rb:129:in `block in <class:PurchaseItem>'

**Comment by Aquaj** [comment]
Problem stems from the fact that we create the fixed_asset at purchase_item#create/update even if the purchase's `state` is Draft.
As such it tries to set the `started_at` attribute to the (yet nonexistent) purchase's `invoiced_at`.

It should be at facturation instead of draft.
