### ISSUE TITLE
interventions#index (ActionView::Template::Error) "undefined method `flatten' for \"record\":String"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1302]
An ActionView::Template::Error occurred in interventions#index:

  undefined method `flatten' for "record":String
  app/helpers/backend/base_helper.rb:299:in `main_list'

**Comment by burisu** [comment]
Seems to be fixed 0f227ccd7dc61bba15f0137cddc240e12f036c74
