### ISSUE TITLE
Label name error

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1312]
In the 4th line : "erteterterte"
what is it ? 
It's the same in french and in english

![image](https://cloud.githubusercontent.com/assets/23054955/20055843/6cb36adc-a4e3-11e6-88e1-1b6db6eb9493.png)

**Comment by EmmaDorie** [comment]
This field exist only in this farm ...
May be it's a personalized field added in test.ekylibre.in ?

**Comment by PH64** [comment]
Yes, it's a custom field https://test.ekylibre.in/backend/custom-fields
