### ISSUE TITLE
sale_opportunities#show (ActionView::Template::Error) "undefined local variable or method `default_type' for...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1323]
An ActionView::Template::Error occurred in sale_opportunities#show:

  undefined local variable or method `default_type' for #<#<Class:0x007fccb44c9c48>:0x007fccb740f4a8>
  app/views/backend/affairs/_show.html.haml:17:in `_app_views_backend_affairs__show_html_haml__3182537057354974541_70258626776180'

**Comment by burisu** [comment]
Fixed by 1c9830c773031298ab788ff6e8a57172d6712863
