### ISSUE TITLE
Add sale number on incoming payments list

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1324]
Add sale number on incoming payments list

![capture du 2016-11-09 13-33-08](https://cloud.githubusercontent.com/assets/12525665/20138552/4ac85640-a681-11e6-88c9-14f425dd9f00.png)

**Comment by burisu** [comment]
Yes it should be better to have sale number with link on it in place of affair, but (there is always a "but") it will need for us to review totally `active_list` (which is on roadmap for later)
