### ISSUE TITLE
adding a new variant record doesn't work

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1342]
Ekylibre 2.19.0 test
When I create a new variant through "add a new recor", it's not create, it's not written in the window and I can't find it when I search. The only way to create a new variant is using the parameters.
Here, I've created a new variant "tourteau de soja"

![image](https://cloud.githubusercontent.com/assets/23054955/20338723/09b9066a-abd9-11e6-910c-cdfd1b3db734.png)

**Comment by PH64** [comment]
It's because account 'stock_movement_account' is not configured on category of "tourteau de soja" variant.
same problem #1317  and #1160
