### ISSUE TITLE
outgoing_payment_lists#export_to_sepa (ArgumentError) "Le montant à payer doit être supérieur à zéro\ntransl...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1347]
## Error:

An ArgumentError occurred in outgoing_payment_lists#export_to_sepa:

  Le montant à payer doit être supérieur à zéro
translation missing: fra.activemodel.errors.models.sepa/credit_transfer_transaction.attributes.bic.invalid
  app/models/outgoing_payment_list.rb:90:in `block in to_sepa'

---
## Environment:

- **Version :** 2.19.1
- **Server :** prod

**Comment by ionosphere** [comment]
I ve got this problem today for an outgoingpayment list with 146 payments (2 negatives).
Negatives outgoing payment (sepa or check) are not allowed.

**Comment by Nyxelio** [comment]
Still relevant ? Negatives outgoing payments on outgoing payment list aren't possible anymore

**Comment by Aquaj** [comment]
If this negative-amounts OutgoingPayments are not possible in OutgoingPaymentList, this shouldn't be relevant anymore. 

Fixed by, I think, f66a719b86 and/or 513fc2aadf ?
