### ISSUE TITLE
entities#show (ActionView::Template::Error) "undefined method `name' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1350]
## Error

An ActionView::Template::Error occurred in entities#show:

  undefined method `name' for nil:NilClass
  app/views/backend/shared/timeline/content/_sale.html.haml:1:in `_app_views_backend_shared_timeline_content__sale_html_haml__3585757340797924892_69967718694040'

---
## Environment

- **Version :** 2.19.1
- **Server :** Production

**Comment by burisu** [comment]
It seems that we have a sale without `sale_nature`...
