### ISSUE TITLE
interventions#destroy (NoMethodError) "undefined method `round' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1352]
## Error

A NoMethodError occurred in interventions#destroy:

  undefined method `round' for nil:NilClass
  app/models/intervention.rb:318:in `block (2 levels) in <class:Intervention>'

---
## Environment
- **Version :** 2.19.1
- **Server :** preprod

**Comment by burisu** [comment]
I can't reproduce. Have we more details on that?

**Comment by PH64** [comment]
The problem seems appear with "Parturition" intervention deletion.
ex : https://test.ekylibre.in/backend/interventions/77 and delete

**Comment by EmmaDorie** [comment]
Error message : 
![bug](https://cloud.githubusercontent.com/assets/11627573/20790894/c069c9ca-b7ba-11e6-8ced-e8f4dd52d360.png)

**Comment by burisu** [comment]
Stock accountancy is again the cause of the probleme

**Comment by igkyab** [comment]
@burisu this bug is fixed with all last accountancy work ?
