### ISSUE TITLE
No error message when informations are missing : add a red star and / or a comment

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1353]
If you create a new parcel : when Quantity or Product or Identification number aren't complete, you can't validate and there is no error message to tell where is the trouble. 
It would be better to add a red star to indicate the fields are required.

![image](https://cloud.githubusercontent.com/assets/23054955/20393526/80dacfae-acdc-11e6-9eb9-a4661b24d378.png)

**Comment by linuxipho** [comment]
Product variant is now required, and a message is displayed in case of missing. Bug closed.
