### ISSUE TITLE
Some indicators shoud'nt be displayed

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1355]
### 1- How to reproduce?
In Settings > Product types, create a new entry. 
`Entry date`, `Exit reason`, `Father race code`, `birth date`, `End of life witness`, `Entry Reason`, `Father country code`, `First calving date`, `Birth farm number`, `Country code`, `Exit date`, `Father identification number`, `Mother country code`, `Mother identification number`, `Mother race code`, `origin country code`, `Origin identification number` fields shouldn't appear.

### 2- What is really expected?
We shouldn't see this fields.

### 3- How to test it?
In Settings > Product types, create a new entry. Check concerned fields are not present.

- - -

Entry date, Exit reason, Father race code, birth date, End of life witness, Entry Reason, Father country code, First calving date, Birth farm number, Country code, Exit date, Father identification number
![image](https://cloud.githubusercontent.com/assets/23054955/20394883/5a21fd06-ace1-11e6-889b-224ac533e734.png)
Mother country code
Mother identification number
Mother race code
origin country code
Origin identification number
![image](https://cloud.githubusercontent.com/assets/23054955/20395087/017822e2-ace2-11e6-87ba-07701af46938.png)
![image](https://cloud.githubusercontent.com/assets/23054955/20395161/46f4ca78-ace2-11e6-85c0-f6f2e73c9cbc.png)

**Comment by PH64** [comment]
Those indicators in product type shouldn't be displayed
