### ISSUE TITLE
Translation missing : State in deliveries view

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1364]
Translations are missing on the state of parcel(s) in deliveries view.
![index](https://cloud.githubusercontent.com/assets/11627573/20430955/a869154c-ad97-11e6-9e70-0ca766b23bd4.png)

### 1- How to reproduce?
In Stocks > Deliveries, select a parcel. The `state` field translation is missing.

### 2- What is really expected?
Should be translated in other languages.
Translations files are localized in config/locales/`<lang>`/models.yml

state | eng | fra | deu
----- | ------- | ------ | ------
draft | "Draft" | "Brouillon" | "Entwurf"
finished | "Finished" | "Terminée" | "Fertig"
in preparation | "In preparation" | "En préparation" | "In Vorbereitung"
ordered | "Ordered" | "Commandée" | "Bestellt"
prepared | "Prepared" | "Prête" | "Bereit"
started | "Started" | "Commencée" | "Gestartet"

### 3- How to test it?
Go to Stocks > Deliveries, select a parcel. See if `state` field is translated in other languages than English.

**Comment by burisu** [comment]
Known problem due to a limitation of ActiveList
