### ISSUE TITLE
outgoing_payment_lists#index (ActionView::Template::Error) "undefined method `items' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1372]
## Error

An ActionView::Template::Error occurred in outgoing_payment_lists#index:

  undefined method `items' for nil:NilClass
  app/models/outgoing_payment_list.rb:50:in `map'

---
## Environment
- **Version :** 2.19.1
- **Server :** prod

**Comment by burisu** [comment]
Maybe fixed by c803b990?

**Comment by Aquaj** [comment]
I'd say this specific exception *is* fixed by c803b99 but I'm not sure we didn't just turn an Exception into a behavior bug. We'll have to wait and see.

**Comment by burisu** [comment]
We waited, we saw.
