### ISSUE TITLE
plots#index (ActionView::Template::Error) "undefined method `harvest_year' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1380]
# Error

An ActionView::Template::Error occurred in plots#index:

  undefined method `harvest_year' for nil:NilClass
  config/initializers/apartment.rb:52:in `call'

---
## Environment

- **Version :** 2.19.1
- **Server :** production

**Comment by burisu** [comment]
Plugin bug, not Ekylibre
