### ISSUE TITLE
activity_productions#create (ActiveRecord::RecordInvalid) "Validations échouées : Delta ne peut pas être vid...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1387]
## Error
An ActiveRecord::RecordInvalid occurred in activity_productions#create:

  Validations échouées : Delta ne peut pas être vide, Delta n’est pas un nombre
  app/models/product.rb:424:in `set_initial_values'

---
## Environment
- **Version :** 2.20.1
- **Server :** production

**Comment by PH64** [comment]
A red star should be added after the name "population" in "Animal Groups" or the number 0 by default at creation of the group.

**Comment by Nyxelio** [comment]
Fixed on f20f70d
