### ISSUE TITLE
purchases#invoice (ActiveModel::MissingAttributeError) "missing attribute: undelivered_invoice_entry_id"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1398]
## Error

An ActiveModel::MissingAttributeError occurred in purchases#invoice:

  missing attribute: undelivered_invoice_entry_id
  lib/ekylibre/record/bookkeep.rb:60:in `block in journal_entry'

---
## Environment
- **Version :** 2.20.1
- **Server :** production

---
## Informations
Production launched when the problem occur.

**Comment by burisu** [comment]
Word is no more in code, so issue is fixed.
