### ISSUE TITLE
7 translations missing in VAT...

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1401]
Draft, Validated and sent
Mode : Payment
Deductible, Fixed asset deductible and Collected
![image](https://cloud.githubusercontent.com/assets/23054955/20564106/e51f38b6-b18b-11e6-90df-1aea3e655de2.png)

**Comment by linuxipho** [comment]
Can't access TVA view for now. No info if already declared or not, no buttons, nothing... is this a bug?

**Comment by burisu** [comment]
@linuxipho, not a bug, but you need accounting data to create VAT declarations.

**Comment by chetannibotechnologies** [comment]
Not a bug. This is a user entered value, which is saved as a string in database. VAT  % are stored as numbers in database and hence get converted as per locale. As per current architecture, string fields are not translated on any page
