### ISSUE TITLE
purchases#new (ActiveRecord::StaleObjectError) "Attempted to update a stale object: User"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1413]
## Error
An ActiveRecord::StaleObjectError occurred in purchases#new:

  Attempted to update a stale object: User
  lib/userstamp/controller.rb:27:in `set_stamper'

---
## Environment
- **Version :** 2.21.5
- **Server :** production
- **Instance :** Fermes Larrère

**Comment by burisu** [comment]
Linked to #1414 and `set_stamper` since Userstamp refactoring

**Comment by igkyab** [comment]
Same error than #1631
