### ISSUE TITLE
attachments#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1417]
## Error
An ActiveRecord::StaleObjectError occurred in attachments#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.21.5
- **Server :** production

**Comment by Aquaj** [comment]
Duplicate of #1296.
