### ISSUE TITLE
Calendar in draft journal has a bad translation

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1428]
Calendar in draft journal isn't translate in the same language as the user

![capture du 2016-12-05 16-46-07](https://cloud.githubusercontent.com/assets/12525665/20891917/830d1884-bb0c-11e6-9244-c668fd90c592.png)

**Comment by igkyab** [comment]
Resolved with the commit a5cb75b2f04658cd8062261eff3aeebb57862464
