### ISSUE TITLE
activity_budgets#unroll (ActiveRecord::StatementInvalid) "PG::UndefinedColumn: ERREUR: la colonne activity_...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1435]
## Error

An ActiveRecord::StatementInvalid occurred in activity_budgets#unroll:

  PG::UndefinedColumn: ERREUR:  la colonne activity_budgets.activity_name n'existe pas
LIGNE 1 : ...vity_budgets".* FROM "activity_budgets"  ORDER BY "activity_...
                                                               ^
: SELECT "activity_budgets".* FROM "activity_budgets"  ORDER BY "activity_budgets"."activity_name" ASC, "activity_budgets"."campaign_name" ASC
  app/controllers/concerns/unrollable.rb:46:in `block (2 levels) in unroll'

---
## Environment
- **Version :** 2.22.0
- **Server :** production

**Comment by Aquaj** [comment]
Fixed by 5a0f3e377.
