### ISSUE TITLE
Add a red star to indicate the population of a band is missing in order to create a new band of animals

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1442]
v 2.22.2
When you create a new production, impossible to create a new band if you don't select a number for the population : please add a red star to indicate it's necessary to fill it and an error message to tell the value is missing.

After validation, you arrive again on the window create a product whereas you expect to come back on new production

**Comment by Nyxelio** [comment]
Fixed on f20f70d
