### ISSUE TITLE
Harvesting intervention :  filling matters and quantity must be optionnal

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1461]
When you ask for an harvesting request, you can't know before the harvest how many unit of matter you will have.
But you can't create the request if you don't fill in the matters and quantity.
![image](https://cloud.githubusercontent.com/assets/23054955/21046801/a60d9dde-be06-11e6-8ac4-96fef1bad4f6.png)

**Comment by EmmaDorie** [comment]
Link with #981.
