### ISSUE TITLE
Missing translation: hover text on time picker

### ISSUE THREAD

**Issue by PierreBougon** [ekylibre/ekylibre#1464]
On the new time picker hover text isn't translated

**Comment by burisu** [comment]
Confirmed
![capture-test modifier la fiche m kozo fuyutsuki - mozilla firefox](https://user-images.githubusercontent.com/240595/27102331-13d86fae-5085-11e7-9378-17c184c684a4.png)
We need to internationalize the component which is a bootstrap extension: `bootstrap3-datetimepicker-rails`
