### ISSUE TITLE
Validation needed before the creation of a purchase : VAT selected by default doesn't exist any more

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1468]
When you select the parcels that should be invoiced , it's necessary to validate amounts and VAT (individually), before the purchase is created. If not, there is mistakes on VAT (7% is default value).

![image](https://cloud.githubusercontent.com/assets/23054955/21093931/c3dc5486-c054-11e6-94de-6218175d8261.png)

**Comment by AnneKappy** [comment]
linked with #1467

**Comment by AnneKappy** [comment]
Now, default VAT is 19,6% on all taxes inclued column whereas default taxe selected is 0%

**Comment by Aquaj** [comment]
The tax is set for each PurchaseItem by taking the default tax of its variant (or if there's a lack thereof, the first Tax in DB).
If I understand correctly, in your case this works but then the computation Tax x Pretax Amount doesn't compute using the tax it should ?

**Comment by chetannibotechnologies** [comment]
Its working fine on demo and test sites. Computation of tax and Pretax amount compute using the tax correctly.

**Comment by chetannibotechnologies** [comment]
Its working correctly. The computation of Tax and Pretax Amount compute correctly.
