### ISSUE TITLE
parcels#invoice (ArgumentError) "wrong number of arguments (1 for 0)"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1470]
## Error
An ArgumentError occurred in parcels#invoice:

  wrong number of arguments (1 for 0)
  app/models/parcel.rb:363:in `first_available_date'

---
## Environment
- **Version :** 2.24.1
- **Server :** production

**Comment by Aquaj** [comment]
Fixed by 026466c.
