### ISSUE TITLE
cash_transfers#index (ActionView::Template::Error) "undefined method `currency' for #<CashTransfer:0x007f1b5...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1474]
## Error
An ActionView::Template::Error occurred in cash_transfers#index:

  undefined method `currency' for #<CashTransfer:0x007f1b5da795c0>
  app/helpers/backend/base_helper.rb:299:in `main_list'

---
## Environment
- **Version :** 2.25.0
- **Server :** production

**Comment by burisu** [comment]
Fixed by ekylibre/active-list v6.7.4
