### ISSUE TITLE
sales#invoice (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1477]
## Error
An ActiveRecord::StaleObjectError occurred in sales#invoice:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.25.1
- **Server :** production

**Comment by Aquaj** [comment]
Duplicate of #1346.
