### ISSUE TITLE
parcels#invoice (NameError) "undefined local variable or method `entry' for #<JournalEntry:0x007fa505eb3e60>...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1518]
## Error

A NameError occurred in parcels#invoice:

  undefined local variable or method `entry' for #<JournalEntry:0x007fa505eb3e60>
  app/models/journal_entry.rb:341:in `cancel'

---
## Environment
- **Version :** 2.27.1
- **Server :** production

**Comment by burisu** [comment]
Similar to #1510 and #1515. Already fixed.
