### ISSUE TITLE
intervention_participations#create (NameError) "undefined local variable or method `entry' for #<JournalEntr...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1520]
## Error

A NameError occurred in intervention_participations#create:

  undefined local variable or method `entry' for #<JournalEntry:0x007fa508ab9af0>
  app/models/journal_entry.rb:341:in `cancel'

---
## Environment
- **Version :** 2.27.1
- **Server :** production

**Comment by burisu** [comment]
Similar to #1510. Already fixed.
