### ISSUE TITLE
no way to view the balance of a purchase in salary mode

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1522]
The balance of the affair is not true concerning purchase in salary mode.

![Uploading Screenshot at 2017-01-02 11:34:56.png…]()

**Comment by Aquaj** [comment]
The screenshot doesn't work, is it possible to have some more info?

**Comment by ionosphere** [comment]
total of affair is zero event if we have a validated purchase only in this type of purchase because of the third account (421XX).

![bug_purchase_salary_type_1](https://cloud.githubusercontent.com/assets/1838491/22654546/5b4530b8-ec8d-11e6-83fd-31144e58cc8e.png)

![2](https://cloud.githubusercontent.com/assets/1838491/22654599/8ddfafda-ec8d-11e6-8979-9f3b0cd90657.png)

**Comment by EmmaDorie** [comment]
Moreover, the status stays in orange even if invoice and outgoing_payement are registred.
