### ISSUE TITLE
No way to add a credit sale on sale

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1523]
The screen is blank when we want to add a credit sale on sale

![credit_sale](https://cloud.githubusercontent.com/assets/1838491/21588461/315e2f14-d0e7-11e6-9c1a-51080f263202.png)

**Comment by burisu** [comment]
Can't reproduce.

**Comment by ionosphere** [comment]
Yes we can !

![sale_credit](https://cloud.githubusercontent.com/assets/1838491/21591121/9ff62c6e-d101-11e6-93e6-7303587f1e1b.png)
