### ISSUE TITLE
Date picker is in japanese

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1531]
The date picker is in japanese even if the language use in settings is not japanese.
![date_picker](https://cloud.githubusercontent.com/assets/11627573/21606530/6a00b200-d1b0-11e6-904d-e7f641460824.png)

**Comment by PH64** [comment]
same problem as #1428

**Comment by igkyab** [comment]
Resolved with the commit a5cb75b2f04658cd8062261eff3aeebb57862464
