### ISSUE TITLE
sales#create (PG::InFailedSqlTransaction) "ERREUR: la transaction est annulée, les commandes sont ignorées ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1549]
## Error
A PG::InFailedSqlTransaction occurred in sales#create:

  ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
de la transaction

  app/models/affair.rb:101:in `block in <class:Affair>'

---
## Environment
- **Version :** 2.27.2
- **Server :** production

**Comment by burisu** [comment]
This is a production bug due to DB restart
