### ISSUE TITLE
The date "dead_at" of land parcels is not filled automatically with the date of the end of the production anymore

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1552]
Before, the date "dead_at" of the land parcel was automatically filled with the date of the end of the production.
Now, the date "dead_at" remains empty.
Furthermore, if the dates of a production are updated, dates of land parcel are not updated with.

**Comment by burisu** [comment]
Fixed by f9d9b3c8905c54a94b3cf2e471520873334a6e0a
