### ISSUE TITLE
workers#index (ActionView::Template::Error) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1562]
## Error
An ActionView::Template::Error occurred in workers#index:

  Validations échouées : Nom a déjà été pris
  app/models/user.rb:216:in `prefer!'

---
## Environment
- **Version :** 2.29.1
- **Server :** production

**Comment by burisu** [comment]
Concurrency creation of a Preference for a `current_campaign`

**Comment by Aquaj** [comment]
Duplicate of #1729.
