### ISSUE TITLE
Failed to load view of interventions

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1564]
The list of interventions is not load in the view and buttons are missing.

![fermes larrere portugal interventions](https://cloud.githubusercontent.com/assets/11627573/21772290/e04507ca-d68a-11e6-84fb-201516624f4f.png)

**Comment by burisu** [comment]
I don't if it was the problem but I force presence of `started_at`/`stopped_at` on interventions to prevents more bugs from `InterventionParticipation` conversions. Can you confirm bug?

**Comment by EmmaDorie** [comment]
The bug persists.
