### ISSUE TITLE
activities#index (ActionView::Template::Error) "undefined method `to_date' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1565]
## Error
An ActionView::Template::Error occurred in activities#index:

  undefined method `to_date' for nil:NilClass
  app/models/activity_production.rb:359:in `block in interventions_by_weeks'

---
## Environment
- **Version :** 2.30.0
- **Server :** production

**Comment by burisu** [comment]
Already fixed by f42f8950f38157488f2d00c60e65aaf9b6eaa2a2
