### ISSUE TITLE
Colums are too large in accounts view

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1566]
The column "name" is too large in accounts view.
![nom lignes d ecritures](https://cloud.githubusercontent.com/assets/11627573/21806031/94d39ec0-d737-11e6-8c8f-1493fd98d0fa.png)

**Comment by EmmaDorie** [comment]
Same issue with the column in accounts/reconciliation

**Comment by Aquaj** [comment]
Fixed by c5a9ff72.
