### ISSUE TITLE
incoming_payments#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1569]
## Error
An ActiveRecord::StaleObjectError occurred in incoming_payments#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.30.2
- **Server :** production

**Comment by Aquaj** [comment]
Duplicate of #1346.
