### ISSUE TITLE
Modifying the supplier of a purchase doesn't modify the supplier's affair

### ISSUE THREAD

**Issue by AntoineGrz** [ekylibre/ekylibre#1577]
### 1- How to reproduce?
In Trade > Purchases, edit a purchase by changing the supplier. Save and go to the corresponding affair from the purchase view. The Third (supplier) has not changed.

### 2- What is really expected?
If the Third is alone in an affair and we change (edit) this Third (supplier) in the purchase view, this Third should also be changed in the affair view.

### 3- How to test it?
Check if the Third has changed in affair view after purchase edit.

**Comment by linuxipho** [comment]
@ionosphere I don't understand what's the really expected behaviour.
