### ISSUE TITLE
Add access to intervention participation for admin user

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1595]
When a user registers an intervention in Zero (without request), only this user can see the intervention participation in Ekylibre.
However, for interventions registered with a request, all user with admin profile can see intervention participations.

**Comment by ionosphere** [comment]
+1 I need to perform this task in the same way. Ask user to make an intervention throught request, user see request in Zero and perform it. user AND me could transform crumbs. Thanks
