### ISSUE TITLE
cultivable zone is twice present after first run

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1597]
see bellow

![screenshot at 2017-01-23 13 43 36](https://cloud.githubusercontent.com/assets/1838491/22204380/fbcd5b5e-e171-11e6-80f1-bdb74b515330.png)

**Comment by Aquaj** [comment]
I don't see any two Cultivable Zones with the same area on your screen shot. Which are the two duplicates? "ZC-...-14-1" & "-14-2" ?

**Comment by ionosphere** [comment]
We have cultivable zone with the same shape but different name like ZC-xxxxxx-21-1 and "Les pommiers".

To prevent ths, i've added shape similar detection https://github.com/ekylibre/ekylibre/commit/f807cbfa1d03cfa9487f3a2db49fd50a673735b1
