### ISSUE TITLE
product_nature_variants#update (ActiveRecord::RecordInvalid) "Validations échouées : Numéro a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1603]
## Error
An ActiveRecord::RecordInvalid occurred in product_nature_variants#update:

  Validations échouées : Numéro a déjà été pris
  app/models/product_nature_variant.rb:230:in `create_unique_account'

---
## Environment
- **Version :** 2.32.1
- **Server :** production

**Comment by igkyab** [comment]
Fixed with a1ff3c9afa9618c9f4c1def0107a55107b23fcc0

**Comment by igkyab** [comment]
Error happened again with another line in stack trace : 

## Error
An ActiveRecord::RecordInvalid occurred in product_nature_variants#create:

  Validations échouées : Numéro a déjà été pris
  app/models/product_nature_variant.rb:232:in `create_unique_account'

---
## Environment
- **Version :** 2.36.8
- **Server :** production
- **Date :** 18/03/2017

**Comment by burisu** [comment]
No news since march
