### ISSUE TITLE
activity_productions#update (ActiveRecord::RecordInvalid) "Validations échouées : Delta ne peut pas être vid...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1610]
## Error
An ActiveRecord::RecordInvalid occurred in activity_productions#update:

  Validations échouées : Delta ne peut pas être vide, Delta n’est pas un nombre
  app/models/product.rb:437:in `set_initial_values'

---
## Environment
- **Version :** 2.33.0
- **Server :** production

**Comment by Nyxelio** [comment]
It will be fixed soon. See #1626.

**Comment by Nyxelio** [comment]
Fixed f20f70d84be8164ba44928d5401324aa4c4642f8
