### ISSUE TITLE
Time difference between Zero intervention and imported intervention

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1617]
It seems there is a time difference of 12 hours between registered Zero intervention and its import in Ekylibre.
Thanks to @PH64.

**Comment by PH64** [comment]
it seems all events in Ekylibre are 12 hours late / real time. Thanks to @Nyxelio

**Comment by Nyxelio** [comment]
It seems to be a compatibility issue with Firefox < 51.

**Comment by Nyxelio** [comment]
This issue is already fixed by ccfed418fa3b37b5472663177843cbce6ad8f3d1. It will be available on the next release.
