### ISSUE TITLE
sales#update (NoMethodError) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1623]
## Error
A NoMethodError occurred in sales#update:

  undefined method `id' for nil:NilClass
  app/models/sale.rb:226:in `block (3 levels) in <class:Sale>'

---
## Environment
- **Version :** 2.33.0
- **Server :** production

**Comment by Nyxelio** [comment]
No way to reproduce
