### ISSUE TITLE
sales#show (ActionView::Template::Error) "undefined method `subscribing?' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1624]
## Error
An ActionView::Template::Error occurred in sales#show:

  undefined method `subscribing?' for nil:NilClass
  app/helpers/cobbles_helper.rb:93:in `cobble_list'

---
## Environment
- **Version :** 2.33.0
- **Server :** production

**Comment by Nyxelio** [comment]
It occurs when saleItem has no variant, but I can't find a way to reproduce it.
