### ISSUE TITLE
PDF should not be served and stay in memory

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#163]
Hi,

When one exports its intervention_registry, Unicorn process goes from 290 MB to 662 MB in memory. And it stays at 662 MB. 
Seen on https://se2014.ekylibre.com/backend/exports/intervention_registry.pdf?key=5lfs&template=7

Is there something we can do about it ? 

Feel free to move milestone to an other version if it needs a lot of work.

Regards,

**Comment by burisu** [comment]
Fixed with 530415eec9f9acdc413d8e8955d31c5f391340f9.
