### ISSUE TITLE
map is missing on many views

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1634]
Why ?

https://demo.ekylibre.farm/backend/cap_statements/2

Example on cap-statement but same things on land-parcels, cultivable-zones, plants

![map_1](https://cloud.githubusercontent.com/assets/1838491/22661038/17c4c274-eca4-11e6-9fe3-e5747831e886.png)

**Comment by PH64** [comment]
The problem seems to be already corrected in 2.33.1

**Comment by Nyxelio** [comment]
@PH64 Yes it's already corrected for land parcels and cultivable zones but I need to reflect changes for cap statement and plants.
