### ISSUE TITLE
animals#index (ActionView::Template::Error) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1635]
## Error
An ActionView::Template::Error occurred in animals#index:

  Validations échouées : Nom a déjà été pris
  app/models/preference.rb:222:in `set!'

---
## Environment
- **Version :** 2.33.0
- **Server :** production

**Comment by Aquaj** [comment]
Duplicate of #1729.
