### ISSUE TITLE
interventions#index (ActionView::Template::Error) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1636]
## Error
An ActionView::Template::Error occurred in interventions#index:

  Validations échouées : Nom a déjà été pris
  app/models/user.rb:216:in `prefer!'

---
## Environment
- **Version :** 2.33.0
- **Server :** production

**Comment by Aquaj** [comment]
Duplicate of #1729.
