### ISSUE TITLE
cultivable_zones#show (ActionView::Template::Error) "PG::InternalError: ERREUR: transform: couldn't project...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1639]
## Error
An ActionView::Template::Error occurred in cultivable_zones#show:

  PG::InternalError: ERREUR:  transform: couldn't project point (55.4587 -21.2784 0): latitude or longitude exceeded limits (-14)
: SELECT ST_Area(ST_Transform(ST_MakeValid(ST_GeomFromEWKT(

---
## Environment
- **Version :** 2.34.0
- **Server :** production

**Comment by Aquaj** [comment]
Same issue as #1649.
