### ISSUE TITLE
Localize currency number in invoices

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#164]
Hi,

Currency numbers do not follow locale and are not easy to read.
See below:
![currency](https://cloud.githubusercontent.com/assets/121875/4458997/98c69fc6-48a7-11e4-9e37-6bed6f45d758.png)

It should display 30 713 and not 30713.0 for quantity
It should display 35 896,99 € and not 35896.9983 for amount

Regards

**Comment by burisu** [comment]
Fixed with 51d608dc2d56e9970b173f8786a2aecd56712a74.
