### ISSUE TITLE
sales#abort (NoMethodError) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1641]
## Error
A NoMethodError occurred in sales#abort:

  undefined method `id' for nil:NilClass
  app/models/sale.rb:226:in `block (3 levels) in <class:Sale>'

---
## Environment
- **Version :** 2.34.0
- **Server :** production

**Comment by burisu** [comment]
Account on sale_item is missing
