### ISSUE TITLE
parcels#give (NoMethodError) "undefined method `collect' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1645]
## Error
A NoMethodError occurred in parcels#give:

  undefined method `collect' for nil:NilClass
  app/controllers/backend/base_controller.rb:257:in `fire_event'

---
## Environment
- **Version :** 2.34.0
- **Server :** production

**Comment by thib44** [comment]
Impossible to reproduce this error !
