### ISSUE TITLE
cultivable_zones#index (ActionView::Template::Error) "PG::InternalError: ERREUR: transform: couldn't projec...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1649]
## Error
An ActionView::Template::Error occurred in cultivable_zones#index:

  PG::InternalError: ERREUR:  transform: couldn't project point (55.4587 -21.2784 0): latitude or longitude exceeded limits (-14)
: SELECT ST_Area(ST_Transform(ST_MakeValid(ST_GeomFromEWKT(...

---
## Environment
- **Version :** 2.34.0
- **Server :** production

**Comment by igkyab** [comment]
Same error for `activity_productions#create`

**Comment by burisu** [comment]
No news, I close for now.
