### ISSUE TITLE
journal_entries#currency_state (ActiveRecord::RecordInvalid) "Validations échouées : Code a déjà été pris, D...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1666]
## Error
An ActiveRecord::RecordInvalid occurred in journal_entries#currency_state:

  Validations échouées : Code a déjà été pris, Débuté le se trouve sur un exercice existant, Date de clôture se trouve sur un exercice existant
  app/models/financial_year.rb:302:in `find_or_create_previous!'

---
## Environment
- **Version :** 2.34.2
- **Server :** production

**Comment by burisu** [comment]
Duplicates of #1658 ?

**Comment by igkyab** [comment]
Duplicates of #1657

**Comment by igkyab** [comment]
Same problem that #1663
