### ISSUE TITLE
When try to input a journal entry out of existing financial year, problems appears

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1667]
app are going very slow after adding a journal entry on bad date in past ( year 202).

for the moment, we don't have to allow creating financial year on the fly because lot of problem appears in case of error on date (under Firefox) . see bellow

![fy](https://cloud.githubusercontent.com/assets/1838491/22964523/6cf42080-f359-11e6-8236-cbd05ab94647.png)

**Comment by burisu** [comment]
Fixed or not?

**Comment by ionosphere** [comment]
No.

![screenshot at 2017-02-21 20 52 32](https://cloud.githubusercontent.com/assets/1838491/23182114/b06fb842-f877-11e6-9e45-8001df35ca00.png)

**Comment by linuxipho** [comment]
Fixed today, but the warning message is not the good one. Opening issue #1986.
![capture d ecran de 2017-06-22 10-47-00](https://user-images.githubusercontent.com/6285769/27425356-72db3e78-5738-11e7-8d18-df36385d0505.png)
