### ISSUE TITLE
Cannot select intrant quantity unit

### ISSUE THREAD

**Issue by AntoineGrz** [ekylibre/ekylibre#1673]
![1](https://cloud.githubusercontent.com/assets/20905413/23063287/f8dd31b6-f509-11e6-87cd-e5f46b19a3ee.png)

**Comment by AlexisLeC** [comment]
Hi Antoine,
What is the context ? During sowing ?

**Comment by ionosphere** [comment]
This problem appears when some indicators are missing on the variant.

![missing_indicators_on_variants](https://cloud.githubusercontent.com/assets/1838491/23167190/aef76034-f843-11e6-8b50-08ede3e90997.png)
