### ISSUE TITLE
plants#index (ActionView::Template::Error) "undefined method `human_name' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1675]
## Error
An ActionView::Template::Error occurred in plants#index:

  undefined method `human_name' for nil:NilClass
  app/helpers/backend/plants_helper.rb:16:in `block in plants_map'

---
## Environment
- **Version :** 2.34.2
- **Server :** production

**Comment by Aquaj** [comment]
Same source as #1697.
