### ISSUE TITLE
interventions#edit (ActionView::Template::Error) "undefined method `human_name' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1676]
## Error
An ActionView::Template::Error occurred in interventions#edit:

  undefined method `human_name' for nil:NilClass
  app/views/backend/interventions/_product_parameter_fields.html.haml:43:in `block in _app_views_backend_interventions__product_parameter_fields_html_haml___2998975377137270058_70314451215620'

---
## Environment
- **Version :** 2.34.2
- **Server :** production

**Comment by Aquaj** [comment]
Linked to #1697.
