### ISSUE TITLE
journal_entries#create (ActionController::ParameterMissing) "param is missing or the value is empty: journal...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1677]
## Error
An ActionController::ParameterMissing occurred in journal_entries#create:

  param is missing or the value is empty: journal_entry
  app/controllers/backend/journal_entries_controller.rb:154:in `permitted_params'

---
## Environment
- **Version :** 2.34.3
- **Server :** production

**Comment by igkyab** [comment]
Same error today with an other line : 

## Error
An ActionController::ParameterMissing occurred in journal_entries#create:

  param is missing or the value is empty: journal_entry
  app/controllers/backend/journal_entries_controller.rb:172:in `permitted_params'

## Environment
- **Version :** 2.41.2
- **Server :** production
- **Date :** 25/04/2017

**Comment by thib44** [comment]
Solves with : https://github.com/ekylibre/ekylibre/pull/1830
