### ISSUE TITLE
Small unit display in intervention

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#1683]
When spraying some pesticide I use to put some grams of a product (_e.g._ 5 gr/ha). The calculated total amount of product is well displayed (see image 5gr/ha for 17ha26) but the grams per hectare is not (underlined) and truncated to 1:100

![capture d ecran_2017-02-22_21-30-48](https://cloud.githubusercontent.com/assets/8056027/23231044/933eb528-f946-11e6-81b6-a187d48f1cc5.png)

### 1- How to reproduce?
In Production > Interventions, try to create a new spraying entry. The unit g/ha does not exist.

### 2- What is really expected?
We should have more choice, especially with small units.

### 3- How to test it?
Create a new entry with g/ha as unit.

**Comment by burisu** [comment]
We need to add a new unit "g/ha" to fix the issue in nomenclature and in `spraying` procedure.
