### ISSUE TITLE
Issue displaying activities

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#1684]
When looking at a production screen, 3 interventions are well displayed
![capture d ecran_2017-02-22_22-36-22](https://cloud.githubusercontent.com/assets/8056027/23233755/1f7b4e30-f950-11e6-9b13-930e16170afc.png)
But being on the activities screen : only one (+ a strange icon on the right)
![capture d ecran_2017-02-22_22-36-23](https://cloud.githubusercontent.com/assets/8056027/23233799/3d246dcc-f950-11e6-9217-131744078eec.png)

This may be an issue with WebGL, I have this issue in the console:

`Error: WebGL: texImage2D: Conversion requires pixel reformatting.  application-f6915f8c195853d67973a528cf3a7c8e03b97c69334d1d0c86b13d248777c9ca.js:20:23310
Error: WebGL: drawArrays: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)  application-f6915f8c195853d67973a528cf3a7c8e03b97c69334d1d0c86b13d248777c9ca.js:20:23783
Error: WebGL: texImage2D: Conversion requires pixel reformatting.  application-f6915f8c195853d67973a528cf3a7c8e03b97c69334d1d0c86b13d248777c9ca.js:20:23310`

**Comment by burisu** [comment]
Th strange icon is used for intervention requests which are scheduled in future. 
The 2 missing interventions are maybe linked to our target distribution configuration (#915)
