### ISSUE TITLE
interventions#new (ActionView::Template::Error) "undefined method `display_status' for <Procedo::Procedure::...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1694]
## Error
An ActionView::Template::Error occurred in interventions#new:

  undefined method `display_status' for <Procedo::Procedure::GroupParameter parturition#parturition>:Procedo::Procedure::GroupParameter
  app/views/backend/interventions/_parameter_form.html.haml:21:in `_app_views_backend_interventions__parameter_form_html_haml__3211549108400833317_70335327223100'

---
## Environment
- **Version :** 2.36.1
- **Server :** production

**Comment by Aquaj** [comment]
Closed by 9c0bb9a1b.
