### ISSUE TITLE
animals#keep (ActiveRecord::RecordInvalid) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1695]
## Error
An ActiveRecord::RecordInvalid occurred in animals#keep:

  Validations échouées : Nom a déjà été pris
  app/models/user.rb:216:in `prefer!'

---
## Environment
- **Version :** 2.35.0
- **Server :** production

**Comment by Nyxelio** [comment]
Fixed by f3be19c
