### ISSUE TITLE
interventions#new (ActionView::Template::Error) "undefined method `human_name' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1697]
## Error
An ActionView::Template::Error occurred in interventions#new:

  undefined method `human_name' for nil:NilClass
  app/views/backend/interventions/_product_parameter_fields.html.haml:43:in `block in _app_views_backend_interventions__product_parameter_fields_html_haml___3255247561689486521_69851674662780'

---
## Environment
- **Version :** 2.35.0
- **Server :** production

**Comment by igkyab** [comment]
Can't reproduce this bug on naio instance. Configuration problem ?

**Comment by PH64** [comment]
This bug is always present on naio instance in 3.36.6, for all intervention creation or modification.

**Comment by Nyxelio** [comment]
Fixed on instance.
