### ISSUE TITLE
parcels#create (ActiveRecord::StatementInvalid) "PG::OutOfMemory: ERREUR: mémoire partagée épuisée\nASTUCE ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1701]
## Error
An ActiveRecord::StatementInvalid occurred in parcels#create:

  PG::OutOfMemory: ERREUR:  mémoire partagée épuisée
ASTUCE : Vous pourriez avoir besoin d'augmenter max_locks_per_transaction.
: SELECT  "journal_entries".* FROM "journal_entries" WHERE "journal_entries"."id" IS NULL LIMIT 1
  lib/ekylibre/record/bookkeep.rb:76:in `block in journal_entry'

---
## Environment
- **Version :** 2.35.0
- **Date :** 23/02/2017
- **Server :** production

**Comment by burisu** [comment]
Database configuration to review due to a big number of schemas. Can't fix in current architecture.
