### ISSUE TITLE
interventions#compute (NoMethodError) "undefined method `display_status' for <Procedo::Procedure::GroupParam...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1702]
## Error
A NoMethodError occurred in interventions#compute:

  undefined method `display_status' for <Procedo::Procedure::GroupParameter mechanical_planting#zone>:Procedo::Procedure::GroupParameter
  lib/procedo/engine/intervention.rb:75:in `block in procedure_states'

---
## Environment
- **Version :** 2.36.2
- **Date :** 27/02/2017
- **Server :** production

**Comment by Aquaj** [comment]
Fixed by 9c0bb9a1b.

**Comment by igkyab** [comment]
No, this error is throw still today on the version 2.36.2 which embark this commit of @Nyxelio

**Comment by Aquaj** [comment]
Noted, I'm on it.
