### ISSUE TITLE
Translation Seeding for semis

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#1704]
In the intervention tab, seeding is used, I think a better choice would be sowing or seedling, no ?

**Comment by burisu** [comment]
Planting, seeding, sowing and seedling are quite similar. Historically, we use sowing, then planting, now seeding, but we don't have a consensus on the best name for this intervention.
Although I close the issue, the debate is opened and good arguments for one or another are welcome.
