### ISSUE TITLE
Search bar in accounts doesn't work

### ISSUE THREAD

**Issue by AntoineGrz** [ekylibre/ekylibre#1706]

**Comment by Aquaj** [comment]
Could we have more info? Search bar appears to be working on local tests.

![search_working](https://cloud.githubusercontent.com/assets/2871879/23502289/9580b268-ff37-11e6-9271-6e31dbaa05a5.png)

**Comment by AntoineGrz** [comment]
I talk about the search when you are inside an account
![7](https://cloud.githubusercontent.com/assets/20905413/23502495/5b5bcc16-ff38-11e6-860f-8a2aee5203fb.png)

**Comment by Aquaj** [comment]
Okay. I can reproduce.
