### ISSUE TITLE
instances#create (ActiveRecord::StatementInvalid) "PG::LockNotAvailable: ERREUR: n'a pas pu obtenir un verrou...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1710]
## Error

An ActiveRecord::StatementInvalid occurred in instances#create:

  PG::LockNotAvailable: ERREUR:  n'a pas pu obtenir un verrou sur la relation « instances »
: SELECT  "instances".* FROM "instances" WHERE "instances"."appliance_id" = $1 AND "instances"."unassigned" = $2  ORDER BY "instances"."id" ASC LIMIT 1 FOR UPDATE NOWAIT
  app/models/instance.rb:180:in `block in take!'

---
## Environment
- **Server :** production
- **Date :** 05/03/2017

**Comment by burisu** [comment]
Not related to Ekylibre
