### ISSUE TITLE
last_intervention_cells#show (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERREUR: la valeur d'une ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1727]
## Error
An ActiveRecord::RecordNotUnique occurred in last_intervention_cells#show:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_preferences_on_user_id_and_name »
DÉTAIL : La clé « (user_id, name)=(1, current_campaign.id) » existe déjà.

---
## Environment
- **Version :** 2.36.4
- **Server :** production
- **Date :** 09/03/2017

**Comment by burisu** [comment]
See #1729.
