### ISSUE TITLE
cashes#index (ActionView::Template::Error) "PG::UniqueViolation: ERREUR: la valeur d'une clé dupliquée romp...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1728]
## Error
An ActionView::Template::Error occurred in cashes#index:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_preferences_on_user_id_and_name »
DÉTAIL : La clé « (user_id, name)=(13, list._cashes_list_cashes_tag) » existe déjà.

---
## Environment
- **Version :** 2.36.5
- **Server :** production
- **Date :** 09/03/2017

**Comment by burisu** [comment]
See #1729.
