### ISSUE TITLE
animal_groups#index (ActionView::Template::Error) "PG::UniqueViolation: ERREUR: la valeur d'une clé dupliqu...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1730]
## Error
An ActionView::Template::Error occurred in animal_groups#index:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_preferences_on_user_id_and_name »
DÉTAIL : La clé « (user_id, name)=(1, list._animal_groups_list_animal_groups_tag) » existe déjà.
: INSERT INTO "preferences" ("name", "user_id", "nature", "string_value", "updater_id", "created_at", "updated_at", "creator_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
  app/models/user.rb:216:in `prefer!'

---
## Environment
- **Version :** 2.36.6
- **Server :** production
- **Date :** 11/03/2017

**Comment by burisu** [comment]
See #1729.
