### ISSUE TITLE
attachments#create (Docsplit::ExtractionFailed) "Syntax Error: Couldn't find trailer dictionary\nSyntax Erro...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1732]
## Error
A Docsplit::ExtractionFailed occurred in attachments#create:

  Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

  app/controllers/backend/attachments_controller.rb:12:in `create'

---
## Environment
- **Version :** 2.36.6
- **Server :** production
- **Date :** 13/03/2017

**Comment by Nyxelio** [comment]
It occurs if file is corrupted.
