### ISSUE TITLE
financial_years#generate_last_journal_entry (ActiveRecord::RecordInvalid) "Validations échouées : Le journal...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1747]
## Error
An ActiveRecord::RecordInvalid occurred in financial_years#generate_last_journal_entry:

  Validations échouées : Le journal est clôturé au 31/12/2015 donc vous ne pouvez plus créer, modifier ou supprimer de pièces jusqu’à cette date-là., Élements ne peut pas être vide
  app/models/financial_year.rb:385:in `generate_last_journal_entry'

---
## Environment
- **Version :** 2.36.8
- **Server :** production
- **Date :** 2.36.8

**Comment by burisu** [comment]
Action will disappear in 2.39.2

**Comment by Aquaj** [comment]
Is an action suppression compatible with a Patch release? Shouldn't this be part of the 2.40.0 release instead?
