### ISSUE TITLE
analyses#new (NoMethodError) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1748]
## Error
A NoMethodError occurred in analyses#new:

  undefined method `id' for nil:NilClass
  config/initializers/apartment.rb:52:in `call'

---
## Environment
- **Version :** 2.36.8
- **Server :** production
- **Date :** 18/03/2017

**Comment by thib44** [comment]
Impossible to reproduce this error. I change for the same version with the same db, and i didn't have error.

**Comment by igkyab** [comment]
Okay, this error seems resolved.
