### ISSUE TITLE
Translation is missing on mouse over "leaflet"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1750]
At the bottom of maps, the sentence "a js library for interactive maps" is displayed on mouse over of the world "leaflet" but the translation is missing.

![traduction_leaflet](https://cloud.githubusercontent.com/assets/11627573/24097949/7be4533e-0d68-11e7-9496-8d7ddeb7bca6.png)

### 1- How to reproduce?
On every map view, the text on mouse over of the word "Leaflet" (attributionControl in Leaflet API) is missing translation. The text "A js library for interactive maps" appears.

### 2- What is really expected?
We expect to see the corresponding translation for the logged user.
`fr` : "Une librairie JavaScript pour des cartes interactives"

### 3- How to test it?
Go on any map view, like in Production dashboard for example, and let your mouse over the "Leaflet" attribution word in bottom right corner and see if the translation is done.

**Comment by Aquaj** [comment]
Fixed by #1957
