### ISSUE TITLE
purchases#invoice (ActiveRecord::StaleObjectError) "Attempted to update a stale object: FixedAsset"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1759]
## Error
An ActiveRecord::StaleObjectError occurred in purchases#invoice:

  Attempted to update a stale object: FixedAsset
  app/models/fixed_asset.rb:229:in `add_amount'

---
## Environment
- **Version :** 2.39.1
- **Server :** production
- **Date :** 31/03/2017

**Comment by Aquaj** [comment]
Closed by bbcfd04.
