### ISSUE TITLE
entities#show (ActionView::Template::Error) "Scope `organization` unknown in resource ."

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1766]
## Error
An ActionView::Template::Error occurred in entities#show:

  Scope `organization` unknown in resource .
  app/helpers/navigation_helper.rb:66:in `rescue in navigable'

---
## Environment
- **Version :** 2.37.0
- **Server :** production
- **Date :** 31/03/2017

**Comment by Aquaj** [comment]
Fixed by c8e0effe73.
