### ISSUE TITLE
Bug when we try to attach affairs of different kinds

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1769]
## Error
A RuntimeError occurred in purchase_affairs#attach:

  PurchaseAffair (ID=2) cannot be merged in SaleAffair
  app/controllers/backend/affairs_controller.rb:51:in `attach'

---
## Environment
- **Version :** 2.39.1
- **Server :** production
- **Date :** 03/04/2017

**Comment by igkyab** [comment]
This bug is throw when two affairs are attached and each affair have regularization.

**Comment by burisu** [comment]
How to reproduce?

**Comment by Aquaj** [comment]
Has it been reproduced ?

**Comment by burisu** [comment]
No news, I close for now.
