### ISSUE TITLE
interventions#index (ActionView::Template::Error) "undefined method `parameters' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1771]
## Error
An ActionView::Template::Error occurred in interventions#index:

  undefined method `parameters' for nil:NilClass
  app/models/intervention.rb:452:in `completely_filled?'

---
## Environment
- **Version :** 2.39.1
- **Server :** production
- **Date :** 03/04/2017

**Comment by burisu** [comment]
@thib44 , can you explain how you find the solution in #1774?
