### ISSUE TITLE
parcels#create (ArgumentError) "The usage :invoice_to_create_clients is not implemented in \"pt_snc\""

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1784]
## Error
An ArgumentError occurred in parcels#create:

  The usage :invoice_to_create_clients is not implemented in "pt_snc"
  app/models/account.rb:291:in `find_or_import_from_nomenclature'

---
## Environment
- **Version :** 2.40.0
- **Server :** production
- **Date :** 07/04/2017

**Comment by burisu** [comment]
Fixed by aa9f702344e4c2077ccae0d778912f87d357834b
