### ISSUE TITLE
Cannot generate loans journal entries

### ISSUE THREAD

**Issue by AntoineGrz** [ekylibre/ekylibre#1814]
/backend/loans
![capture3](https://cloud.githubusercontent.com/assets/20905413/25389975/5c9a551a-29d2-11e7-8d33-e2902ed87e81.JPG)

**Comment by thib44** [comment]
In calendar block date > Time.now
Block passage of accounting = true if due_on > Time.today

**Comment by thib44** [comment]
https://github.com/ekylibre/ekylibre/pull/1828
