### ISSUE TITLE
Loss of data when switching from a request intervention to record

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1826]
When switching from a request intervention to record, request intervention stay in "list" but all the data are lost 
![capture du 2017-04-27 10-03-49](https://cloud.githubusercontent.com/assets/12525665/25473731/de42ec58-2b30-11e7-8538-f833ff434caf.png)

**Comment by linuxipho** [comment]
### 1- How to reproduce?
I cannot reproduce the bug, data are well here.
