### ISSUE TITLE
purchases#invoice (ActiveRecord::RecordInvalid) "Validations échouées : Méthode d’amortissement ne peut pas être 

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1834]
An ActiveRecord::RecordInvalid occurred in purchases#invoice:

  Validations échouées : Méthode d’amortissement ne peut pas être vide, Méthode d’amortissement n’est pas inclus dans la liste, Arrêté le ne peut pas être vide, Arrêté le est invalide
  app/models/purchase_item.rb:215:in `update_fixed_asset'

-------------------------------
Environment:
-------------------------------
- Version: 2.41.2
- Server: production
- Date: 27/04/2017

**Comment by burisu** [comment]
No news, I close for now.

**Comment by burisu** [comment]
Similar to #1252.
