### ISSUE TITLE
journal_entries#update (ActionView::Template::Error) "comparison of Fixnum with nil failed"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1835]
An ActionView::Template::Error occurred in journal_entries#update:

  comparison of Fixnum with nil failed
  app/views/backend/journal_entries/_form.html.haml:59:in `block in _app_views_backend_journal_entries__form_html_haml__1906237066325383378_70227112785920'

-------------------------------
Environment:
-------------------------------
- Version: 2.41.2
- Server: production
- 27/04/2017

**Comment by burisu** [comment]
No news, I close for now.
