### ISSUE TITLE
debt_transfers#create (ActiveRecord::RecordInvalid) "Validations échouées : Montant ne peut pas être vide"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1836]
An ActiveRecord::RecordInvalid occurred in debt_transfers#create:

  Validations échouées : Montant ne peut pas être vide
  app/models/debt_transfer.rb:96:in `reflect!'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.0
- Server: production
- Date: 27/04/2017

**Comment by burisu** [comment]
No news, I close for now.
