### ISSUE TITLE
stock_container_map_cells#show (ActionView::Template::Error) "missing interpolation argument :container_name

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1838]
An ActionView::Template::Error occurred in stock_container_map_cells#show:

  missing interpolation argument :container_name in "%{work_number} %{name} (%{number}) - %{container_name}" ({:id=>17, :type=>"BuildingDivision", :name=>"Taupinière", :number=>"P00000000017", :variant_id=>76, :nature_id=>45, :category_id=>35, :initial_born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :initial_dead_at=>nil, :initial_container_id=>5, :initial_owner_id=>1, :initial_enjoyer_id=>nil, :initial_population=>#<BigDecimal:7fd964c5fbf8,'0.0',9(18)>, :initial_father_id=>nil, :initial_mother_id=>nil, :variety=>"building_division", :derivative_of=>nil, :tracking_id=>nil, :fixed_asset_id=>nil, :born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :dead_at=>nil, :description=>nil, :picture_file_name=>nil, :picture_content_type=>nil, :picture_file_size=>nil, :picture_updated_at=>nil, :identification_number=>nil, :work_number=>"S04_D01", :address_id=>nil, :parent_id=>nil, :default_storage_id=>5, :created_at=>Sat, 01 Apr 2017 03:20:12 CEST +02:00, :updated_at=>Sat, 01 Apr 2017 03:20:12 CEST +02:00, :creator_id=>nil, :updater_id=>nil, :lock_version=>0, :initial_shape=>nil, :person_id=>nil, :initial_geolocation=>nil, :uuid=>"7e46563d-c239-46e4-bd69-2903702b1a0c", :initial_movement_id=>17, :custom_fields=>nil, :team_id=>nil, :member_variant_id=>nil, :birth_date_completeness=>nil, :birth_farm_number=>nil, :country=>nil, :filiation_status=>nil, :first_calving_on=>nil, :mother_country=>nil, :mother_variety=>nil, :mother_identification_number=>nil, :father_country=>nil, :father_variety=>nil, :father_identification_number=>nil, :origin_country=>nil, :origin_identification_number=>nil, :end_of_life_reason=>nil, :originator_id=>nil, :population=>#<BigDecimal:7fd97a3fd918,'0.1E1',9(18)>, :unit_name=>"Salle"} given)
  app/models/product.rb:437:in `unroll_name'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.0
- Server: Production
- Date: 28/04/2017

**Comment by burisu** [comment]
Same as #1949. After a look, bug is still present.
https://github.com/ekylibre/ekylibre/blob/2.51.1/app/views/backend/cells/stock_container_map_cells/show.html.haml#L21 refers Product#unroll_name that doesn't give parameter `:container_name`.

**Comment by burisu** [comment]
To test it, you can try to call `unroll_name` method on one record `Product`. If it pass, it's OK.

**Comment by chetannibotechnologies** [comment]
I have checked by calling unroll_name method on Product record and its working fine.
