### ISSUE TITLE
inventories#show (Module::DelegationError) "InventoryItem#unit_name delegated to product.unit_name, but prod

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1839]
A Module::DelegationError occurred in inventories#show:

  InventoryItem#unit_name delegated to product.unit_name, but product is nil
  app/models/inventory_item.rb:57:in `rescue in unit_name'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.0
- Server: Production
- Date: 28/04/2017

**Comment by burisu** [comment]
An `has_many` is missing in `Product` is missing and `protect on: :destroy` block should be updated to take in account inventory_items.

**Comment by chetannibotechnologies** [comment]
Checked all inventories on demo and test sites but could not reproduce a bug on any inventory. Please provide more description and the particular inventory which produced a bug.

**Comment by burisu** [comment]
We can't reproduce now, bu we can prevent it by adding `has_many :inventory_items, dependent: :restrict_with_exception` and updating block `protect` line 394 in model `Product`
