### ISSUE TITLE
outgoing_payment_lists#new (ActionView::Template::Error) "undefined method `supplier_balance' 

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1840]
An ActionView::Template::Error occurred in outgoing_payment_lists#new:

  undefined method `supplier_balance' for #<Entity:0x007fd9862be398>
  app/views/backend/outgoing_payment_lists/_third.html.haml:11

-------------------------------
Environment:
-------------------------------
- Version: 2.43.0
- Server: Production
- Date: 28/04/2017

**Comment by burisu** [comment]
Fixed in 8f790e1.
