### ISSUE TITLE
journal_entries#currency_state (NoMethodError) "undefined method `currency' for nil:NilClass"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1841]
A NoMethodError occurred in journal_entries#currency_state:

  undefined method `currency' for nil:NilClass
  app/controllers/backend/journal_entries_controller.rb:153:in `currency_state'

  * Parameters : {"from"=>"EUR", "on"=>"0201-11-18", "controller"=>"backend/journal_entries", "action"=>"currency_state"}

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 28/04/2017

**Comment by igkyab** [comment]
Same error in #1663
