### ISSUE TITLE
taxes#load (ActiveRecord::RecordInvalid) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1842]
An ActiveRecord::RecordInvalid occurred in taxes#load:

  Validations échouées : Nom a déjà été pris
  app/models/tax.rb:146:in `import_from_nomenclature'

  * URL        : http://demo.ekylibre.farm/backend/taxes/load?redirect=%2Fbackend%2Ftaxes

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 29/04/2017

**Comment by burisu** [comment]
We can reproduce bug, if we create a Tax with same amount, nature and country of an existing tax in the nomenclature and then we click on "load defaults" button in Taxes index.

**Comment by chetannibotechnologies** [comment]
It’s working fine on demo and test after created a Tax with same amount, nature and country of an existing tax in the nomenclature and then we click on "load defaults" button in Taxes index.
