### ISSUE TITLE
exports#show (ArgumentError) "invalid date"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1843]
An ArgumentError occurred in exports#show:

  invalid date
  app/controllers/backend/exports_controller.rb:42:in `new'

  * URL        : http://demo.ekylibre.farm/backend/exports/exchange_accountancy_file_fr

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 29/04/2017

**Comment by burisu** [comment]
No news, I close for now.
