### ISSUE TITLE
debt_transfers#destroy (NoMethodError) "undefined method `delete' for nil:NilClass"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1845]
NoMethodError occurred in debt_transfers#destroy:

undefined method 'delete' for nil:NilClass
app/models/debt_transfer.rb:84:in `block in <class:DebtTransfer>'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 02/05/2017

**Comment by burisu** [comment]
No news, I close for now.
