### ISSUE TITLE
purchases#update (ActiveRecord::InvalidForeignKey) "PG::ForeignKeyViolation: ERREUR: UPDATE ou DELETE

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1846]
An ActiveRecord::InvalidForeignKey occurred in purchases#update:

  PG::ForeignKeyViolation: ERREUR:  UPDATE ou DELETE sur la table « journal_entry_items » viole la contrainte de clé étrangère
« fk_rails_adb1cc875c » de la table « tax_declaration_item_parts »
DÉTAIL : La clé (id)=(510664) est toujours référencée à partir de la table « tax_declaration_item_parts ».
: DELETE FROM "journal_entry_items" WHERE "journal_entry_items"."entry_id" = $1 AND "journal_entry_items"."id" IN (510664, 510663, 510665)
  lib/ekylibre/record/bookkeep.rb:102:in `block in journal_entry'

-------------------------------
Environment:
-------------------------------
- Version: 2.44.0
- Server: Preprod
- Date: 02/05/2017

**Comment by burisu** [comment]
We need at least to prevent exception by protecting `Purchase` update. `protect` block should be completed in `app/models/puchase.rb`.
