### ISSUE TITLE
sales#create (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERREUR: la valeur d'une clé dupliquée

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1847]
An ActiveRecord::RecordNotUnique occurred in sales#create:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_affairs_on_number »
DÉTAIL : La clé « (number)=(A000000003951) » existe déjà.
: INSERT INTO "affairs" ("type", "currency", "third_id", "number", "deals_count", "closed_at", "closed", "updater_id", "created_at", "updated_at", "creator_id", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id"
  app/controllers/backend/base_controller.rb:130:in `block in save_and_redirect'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 02/05/2017

**Comment by igkyab** [comment]
Same as #1808 ?

**Comment by burisu** [comment]
Fixed by #2091.
