### ISSUE TITLE
Translation missing: labels.net_production_sales

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1848]
French translation of labels.net_production_sales is missing in accountancy dashboard.
### 1- How to reproduce?
Go to Accountancy dashboard, a message signifying there is no translation is shown for every language :
> translation missing: eng.labels.net_production_sales

### 2- What is really expected?
We expect to see the corresponding translation:
- `eng`: Net production sales
- `fra`: Ventes nettes de production

### 3- How to test it?
Go again to Accountancy dashboard and check if the translation is done.

**Comment by linuxipho** [comment]
### 1- How to reproduce?
Go to Accountancy dashboard, a message signifying there is no translation is shown for every language :
> translation missing: eng.labels.net_production_sales

### 2- What is really expected?
We expect to see the corresponding translation.

### 3- How to test it?
Go again to Accountancy dashboard and check if the translation is done.
