### ISSUE TITLE
trial_balances#show (Encoding::UndefinedConversionError) "U+2012 to WINDOWS-1252 in conversion from UTF-8 

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1850]
An Encoding::UndefinedConversionError occurred in trial_balances#show:

  U+2012 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
  app/controllers/backend/trial_balances_controller.rb:77:in `block in to_csv'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 02/05/2017

**Comment by igkyab** [comment]
Resolved in  pull request #1881
