### ISSUE TITLE
cultivable_zones#create (ActiveRecord::StatementInvalid) "PG::InternalError: ERREUR: parse error - invalid

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1860]
An ActiveRecord::StatementInvalid occurred in cultivable_zones#create:

  PG::InternalError: ERREUR:  parse error - invalid geometry
ASTUCE : "a" <-- parse error at position 2 within geometry
: SELECT ST_AsEWKT(ST_GeomFromEWKT('a'))
  lib/charta.rb:85:in `select_value'

URL        : http://demo.ekylibre.farm/backend/cultivable-zones
HTTP Method: POST
Parameters : {"cultivable_zone"=>{"name"=>"Test", "work_number"=>"0214", "production_system_name"=>"intensive_farming", "soil_nature"=>"silty_clay_soil", "farmer_id"=>"", "owner_id"=>"", "description"=>"", "shape"=>"a"}

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: production
- Date: 03/05/2017

**Comment by burisu** [comment]
Will be fixed with [charta](https://github.com/ekylibre/charta) rework.
