### ISSUE TITLE
parcels#give (ActiveRecord::StaleObjectError) "Attempted to update a stale object: ParcelItem"

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#1861]
An ActiveRecord::StaleObjectError occurred in parcels#give:

  Attempted to update a stale object: ParcelItem
  app/models/parcel_item.rb:199:in `check'

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 04/05/2017

**Comment by burisu** [comment]
Can't reproduce. I close for now.
