### ISSUE TITLE
Column "derivative_of" is missing in the list of matters

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#1869]
![image](https://cloud.githubusercontent.com/assets/11627573/25892725/91c49de6-3575-11e7-9f17-26e3e4e361a9.png)

### 1- How to reproduce?
Go to Stocks > Matters, the column `derivative_of` is not present in the table nor in the column choice list.

### 2- What is really expected?
The column `derivative_of` have to be present in the column choice list and if ticked, in the table view.

### 3- How to test it?
Go to Stocks > Matters, and check if the column `derivative_of` is visible in table view or optionally selectable in column choice list.

**Comment by linuxipho** [comment]
### 1- How to reproduce?
Go to Stocks > Matters, the column `derivative_of` is not present in the table nor in the column choice list.
### 2- What is really expected?
The column `derivative_of` have to be present in the column choice list and if ticked, in the table view.
### 3- How to test it?
Go to Stocks > Matters, and check if the column `derivative_of` is visible in table view or optionally selectable in column choice list.
