### ISSUE TITLE
outgoing_payments#update (Ekylibre::Record::RecordNotUpdateable) "Record cannot be updated"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1871]
An Ekylibre::Record::RecordNotUpdateable occurred in outgoing_payments#update:

  Record cannot be updated
  app/controllers/backend/base_controller.rb:130:in `block in save_and_redirect'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 10/05/2017

**Comment by chetannibotechnologies** [comment]
Its working fine on demo and test after updated all records of outgoing payments.
