### ISSUE TITLE
What does the number close to the unit mean in the inventory form

### ISSUE THREAD

**Issue by lucolivier** [ekylibre/ekylibre#1872]
![screen shot 2017-05-10 at 5 49 28 pm](https://cloud.githubusercontent.com/assets/20602804/25907886/08373f50-35a9-11e7-8b35-2f91898ea37f.png)

**Comment by Aquaj** [comment]
It's the `unit_pretax_stock_amount`. Which should hold the price value of an unit of the variant, pre-tax.

Could someone confirm this ? @ionosphere @burisu (maybe @AntoineGrz)

**Comment by PH64** [comment]
@Aquaj. Yes, I think that's it. But does it work?

**Comment by burisu** [comment]
I confirm and it don't seems to work as expected. I close the question, an issue to fix that will be written
