### ISSUE TITLE
incoming_payment_modes#new (ActionView::Template::Error) "The usage :pending_deposit_payments is not impleme...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1873]
## Error
An ActionView::Template::Error occurred in incoming_payment_modes#new:

  The usage :pending_deposit_payments is not implemented in "pt_snc"
  app/models/account.rb:291:in `find_or_import_from_nomenclature'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 11/05/2017

**Comment by chetannibotechnologies** [comment]
It's working fine on test and demo sites and can create new record of incoming_payment_modes
