### ISSUE TITLE
interventions#create (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERREUR: la valeur d'une clé dupl...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1883]
## Error
An ActiveRecord::RecordNotUnique occurred in interventions#create:

  PG::UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « index_product_natures_on_number »
DÉTAIL : La clé « (number)=(PN000000000005) » existe déjà.
: INSERT INTO "product_natures" ("name", "variety", "category_id", "population_counting", "abilities_list", "variable_indicators_list", "frozen_indicators_list", "number", "created_at", "updated_at", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"
  app/models/intervention.rb:638:in `block in run!'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 15/05/2017

**Comment by burisu** [comment]
We need to add a uniqueness validation on ProductNature#number at least to prevent exception
