### ISSUE TITLE
activity_productions#create (ActiveRecord::StatementInvalid) "PG::InternalError: ERREUR: geometry requires ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1885]
## Error
An ActiveRecord::StatementInvalid occurred in activity_productions#create:

  PG::InternalError: ERREUR:  geometry requires more points
ASTUCE : "....1104714871762553 44.51939318563518))" <-- parse error at position 923 within geometry
: SELECT ST_AsEWKT(ST_GeomFromEWKT('SRID=4326;MULTIPOLYGON((...)))'))
  lib/charta.rb:85:in `select_value'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 14/05/2017

**Comment by burisu** [comment]
The error seems to be raised when invalid data is drawn or given to ActiveRecord which let it pass to database. We need a HTR.
