### ISSUE TITLE
purchase_affairs#finish (ActiveRecord::RecordInvalid) "Validations échouées : Taux de change réel doit être ...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1889]
## Error
An ActiveRecord::RecordInvalid occurred in purchase_affairs#finish:

  Validations échouées : Taux de change réel doit être plus grand que 0, La pièce n’est pas équilibrée
  lib/ekylibre/record/bookkeep.rb:103:in `block in journal_entry'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 12/05/2017

**Comment by burisu** [comment]
Can"t reproduce, I close for now.
