### ISSUE TITLE
We have error when intervention created date is before input variant born at date

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1892]
## Error
An ActiveRecord::RecordInvalid occurred in parcels#give:

  Validations échouées : Fabriqué le doit être le ou avant le 25/04/2017 08:00
  app/models/parcel_item.rb:233:in `check_outgoing'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 11/05/2017

**Comment by igkyab** [comment]
Stacktrace changed : 

An ActiveRecord::RecordInvalid occurred in parcels#give:

  Validations échouées : Fabriqué le doit être le ou avant le 10/11/2016 19:32
  app/models/parcel_item.rb:199:in `check'

**Comment by chetannibotechnologies** [comment]
Could not reproduced the bug while intervention created date is before input variant born at date.
