### ISSUE TITLE
product_nature_variants#show (ActionView::Template::Error) "0.017l/1000 pl. cannot be parsed."

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1896]
## Error
An ActionView::Template::Error occurred in product_nature_variants#show:

  0.017l/1000 pl. cannot be parsed.
  lib/measure.rb:59:in `initialize'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 18/05/2017

**Comment by chetannibotechnologies** [comment]
Checked all product_nature_variants show pages but could not reproduced the bug.

As it is more than 5 months since the issue was opened and I was not able to reproduce after multiple tries, so I closed the issue?.
