### ISSUE TITLE
accountancy_balance_cells#show (ActionView::Template::Error) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1897]
## Error
An ActionView::Template::Error occurred in accountancy_balance_cells#show:

  Validations échouées : Nom a déjà été pris
  app/models/preference.rb:127:in `get!'

---
## Environment
- **Version :** 2.43.2
- **Server :** production 
- **Date :** 18/05/2017

**Comment by burisu** [comment]
Same as #1729.
