### ISSUE TITLE
activities#varieties (NoMethodError) "undefined method `key?' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1898]
## Error
A NoMethodError occurred in activities#varieties:

  undefined method `key?' for nil:NilClass
  config/initializers/apartment.rb:72:in `call'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 18/05/2017

**Comment by burisu** [comment]
No news, I close
