### ISSUE TITLE
sales#show (ActiveRecord::StaleObjectError) "Attempted to destroy a stale object: Document"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1899]
## Error
An ActiveRecord::StaleObjectError occurred in sales#show:

  Attempted to destroy a stale object: Document
  app/models/document_template.rb:219:in `document'

---
## Environment
- **Version:** 2.43.2
- **Server:** production
- **Date:** 21/05/2017

**Comment by burisu** [comment]
Can't reproduce, I close for now.
