### ISSUE TITLE
exports#show (ActionView::Template::Error) "undefined method `round' for \"0,000 qt/ha\":String"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1900]
## Error
An ActionView::Template::Error occurred in exports#show:

  undefined method `round' for "0,000 qt/ha":String
  app/views/backend/exports/show.html.haml:8:in `_app_views_backend_exports_show_html_haml__3416824964800371185_70061853753680'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 19/05/2017

**Comment by burisu** [comment]
Fixed in 56aa6c4733f01802c47dcb69538202e45ef49879.
