### ISSUE TITLE
loans#confirm (ActiveRecord::StatementInvalid) "PG::UndefinedColumn: ERREUR: la colonne « nan » n'existe pa...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1901]
## Error
An ActiveRecord::StatementInvalid occurred in loans#confirm:

  PG::UndefinedColumn: ERREUR:  la colonne « nan » n'existe pas
LIGNE 1 : UPDATE "loan_repayments" SET "base_amount" = NaN, "remaining...
                                                       ^
: UPDATE "loan_repayments" SET "base_amount" = NaN, "remaining_amount" = NaN, "amount" = NaN, "updated_at" = '2017-05-17 15:11:27.271319', "lock_version" = 1 WHERE "loan_repayments"."id" = $1 AND "loan_repayments"."lock_version" = $2
  app/models/loan.rb:207:in `block in generate_repayments'

---
## Environment
- **Version :** 2.44.1
- **Server :** preprod
- **Date :** 17/05/2017

**Comment by burisu** [comment]
Similar to #1221
