### ISSUE TITLE
[Ekylibre/production] SyntaxError: /home/jbonal/code/aquaj/ekylibre/app/views/backend/interventions/index.html.haml:1: class definition in method body
...; class HelloError < Exception; end
...                               ^

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1905]
## Backtrace

    line 72 of [PROJECT_ROOT]/config/initializers/apartment.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52353/faults/33662825)

**Comment by Aquaj** [comment]
This was a test - executed locally on my desktop. Closing.
