### ISSUE TITLE
[Ekylibre/production] LoadError: cannot load such file -- pry-byebug

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1906]
## Backtrace

    line 113 of [PROJECT_ROOT]/config/initializers/apartment.rb: switch_honeybadger_context
    line 104 of [PROJECT_ROOT]/config/initializers/apartment.rb: connect_to_new
    line 72 of [PROJECT_ROOT]/config/initializers/apartment.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52353/faults/33662891)

**Comment by Aquaj** [comment]
Again, a test.
