### ISSUE TITLE
Cultivable Zone vs Activities - Production System coherence control missing

### ISSUE THREAD

**Issue by lucolivier** [ekylibre/ekylibre#1910]
### 1- How to reproduce?

One can define a non organic cultivable zone in an organic* activity production without any alert or error generation.
*) refers to production system

### 2- What is really expected?

The creation/update process must stopped with a message about the reason why!

### 3- How to test it?

Try to assign a non organic cultivable zone in an organic* activity production > you must get a message an return back to the form.

**Comment by burisu** [comment]
No more reproducible
