### ISSUE TITLE
purchases#invoice (ActiveRecord::RecordInvalid) "Validations échouées : Numéro a déjà été pris, Numéro a déj...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1911]
## Error
An ActiveRecord::RecordInvalid occurred in purchases#invoice:

  Validations échouées : Numéro a déjà été pris, Numéro a déjà été pris
  app/models/purchase.rb:318:in `invoice'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 24/05/2017

**Comment by burisu** [comment]
Fixed by #2091.
