### ISSUE TITLE
sales#new (ActionView::Template::Error) "Couldn't find SaleAffair with 'id'=10 [WHERE \"affairs\".\"type\" I...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1912]
## Error
An ActionView::Template::Error occurred in sales#new:

  Couldn't find SaleAffair with 'id'=10 [WHERE "affairs"."type" IN ('SaleAffair', 'SaleOpportunity', 'SaleTicket')]
  app/views/backend/sales/_form.html.haml:4:in `block in _app_views_backend_sales__form_html_haml___466408137662761704_70117220128640'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 24/05/2017

**Comment by Nyxelio** [comment]
Already fixed in 2.44.1.
