### ISSUE TITLE
activity_productions#create (ActiveRecord::StatementInvalid) "PG::InvalidParameterValue: ERREUR: Geometry t...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1914]
## Error
An ActiveRecord::StatementInvalid occurred in activity_productions#create:

  PG::InvalidParameterValue: ERREUR:  Geometry type (GeometryCollection) does not match column type (MultiPolygon)
: INSERT INTO "activity_productions" ("activity_id", "campaign_id", "started_on", "stopped_on", "support_nature", "usage", "cultivable_zone_id", "support_shape", "irrigated", "rank_number", "size_indicator_name", "size_unit_name", "size_value", "state", "updater_id", "support_id", "created_at", "updated_at", "creator_id", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) RETURNING "id"
  app/controllers/backend/base_controller.rb:130:in `block in save_and_redirect'

---
## Environment
- **Version :** 2.43.2
- **Server :** production
- **Date :** 24/05/2017

**Comment by burisu** [comment]
No news for now. I close.
