### ISSUE TITLE
cultivable_zones#new (ActionView::Template::Error) "PG::UndefinedFunction: ERROR: function st_geomfromewkt(.

### ISSUE THREAD

**Issue by nico-dangerous** [ekylibre/ekylibre#1926]
An ActionView::Template::Error occurred in cultivable_zones#new:

  PG::UndefinedFunction: ERROR:  function st_geomfromewkt(unknown) does not exist
LINE 1: ...WKT(ST_Multi(ST_CollectionHomogenize(ST_MakeValid(ST_GeomFro...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT ST_AsEWKT(ST_Multi(ST_CollectionHomogenize(ST_MakeValid(ST_GeomFromEWKT('SRID=4326;GEOMETRYCOLLECTION EMPTY')))))
  lib/charta.rb:85:in `select_value'

When I launch manually the request "SELECT ST_AsEWKT(ST_Multi(ST_CollectionHomogenize(ST_MakeValid(ST_GeomFromEWKT('SRID=4326;GEOMETRYCOLLECTION EMPTY')))))", I've go no error

**Comment by burisu** [comment]
@nico-dangerous, thanks for the reporting, how can we reproduce it in the app?

**Comment by burisu** [comment]
@nico-dangerous, I close for now, I hope you find a solution. Maybe, you needed to fix your Postgis installation. Feel free to re-open it when you have more infos.

**Comment by nico-dangerous** [comment]
Hi,
I,m back in the game.
I try a new way to install ekylibre with docker.
I have the same problem, the postGIS functions are not found.
When I look into the databases, I can see the functions only in the "template_postgis" database.
In the database ekylibre, schema postgis I have only a few functions (14).

Maybe it's a start.

Thanks,
Nicolas

**Comment by nico-dangerous** [comment]
I think I solved a part of the problem.
I created a schema with first_run command, let's call it "toto".
I had to DROP the postgis EXTENSION with:
`DROP EXTENSION postgis;`

and recreate it on the new schema toto with :

`CREATE EXTENSION postgis WITH SCHEMA toto;`

And now I can see the postgis functions in the schema toto.
