### ISSUE TITLE
ActiveRecord::RecordInvalid: Validations échouées : Fabriqué le doit être le ou avant le 10/11/2016 19:32

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1927]
## Backtrace

    line 199 of [PROJECT_ROOT]/app/models/parcel_item.rb: check
    line 360 of [PROJECT_ROOT]/app/models/parcel.rb: check
    line 370 of [PROJECT_ROOT]/app/models/parcel.rb: give

**Comment by Aquaj** [comment]
Problem occurs when setting Parcel from :draft to :given.
If the parcel is supposed to be merged into an existing product but said product is 'born' at a later date than the parcel's reception date, the ProductMovement can't be created at the required date.

Current system tries to do:
```
           ___________
          |
__________|
          Î Product birth (2 units)
  Î Moment where it tries to insert a ProductMovement (5 units)
```
which leads to an error when trying to build.

It should be reversed in this situation to obtain:
```
           ___________
          |
__________|
          Î New movement (2 units)
  Î Product birth (5 units)
```
which would end up as
```
          ____________
         |
  _______|
 |
 |
 |
 |
_|_________
        Î New movement (2 units)
 Î Product birth (5 units)
```

**Comment by chetannibotechnologies** [comment]
I have added parcel's reception date later than the Product born date., after settled Parcel from :draft to :given but error could not occurred.
