### ISSUE TITLE
Fail to open a new activity: nothing changes on the screen but the option you've selected disappears from the selector the next time

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1934]
Now the button open desappeared and you can only add a new activity.
![image](https://user-images.githubusercontent.com/23054955/26880312-5496dc24-4b94-11e7-94ea-a295efac0c95.png)

**Comment by burisu** [comment]
On the list view, you are right, nothing change, but in the cobbles views, you can access to your activities. The screen should be fixed to give access to activities.
