### ISSUE TITLE
first_run should fail gracefully when postgis is not enabled

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#200]
Instead of displaying message like:
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR: function addgeometrycolumn(unknown, unknown, integer, unknown, integer) does not exist

first_run shoud check if postgis is enabled and display a human understandable message if it's not.

See: http://forum.ekylibre.org/t/first-run-error/121/4?u=coren

NB: It should also fail gracefully if postgis is installed in *public* schema instead of *postgis* schema
See: http://forum.ekylibre.org/t/first-run-error/121/10?u=coren 

NB: Postgres provides method in order to know if it's enabled or not: 
http://www.postgresql.org/docs/current/interactive/functions-info.html
http://www.postgresql.org/docs/current/interactive/functions-info.html#FUNCTIONS-INFO-ACCESS-TABLE

**Comment by burisu** [comment]
PostGIS and other dependencies should be checked outside with a dedicated tool/command.

**Comment by burisu** [comment]
No change on my mind since last year :)
