### ISSUE TITLE
Error in invoice duplication

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#2111]
When an invoice is duplicated and the variant is changed (Ex : Vin -> Aliment en vrac) 
![capture du 2017-08-17 14-53-02](https://user-images.githubusercontent.com/12525665/29413233-f6376996-835b-11e7-96ac-384ed1e50803.png)

The variant is not modified on the invoice (Vin): 
![capture du 2017-08-17 14-53-21](https://user-images.githubusercontent.com/12525665/29413273-1844a33c-835c-11e7-8914-ff483be44c51.png)

But if we make an asset of this last invoice, the variant is well modified (Aliment en vrac) : 
![capture du 2017-08-17 14-53-59](https://user-images.githubusercontent.com/12525665/29413315-4604a268-835c-11e7-99eb-347790ae87ff.png)

**Comment by Zank94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ekylibre:debug/gh#2111-Fix-variant-name-displayed-after-updating-sale-item](https://trello.com/c/p4qlZEFN/314-ekylibredebug-gh2111-fix-variant-name-displayed-after-updating-sale-item)
