### ISSUE TITLE
JS bug for quantities in reception form

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#2129]
## Error
When i select merchandise in ParcelItem form without storage zone, and after i add a storage zone, i have '#' in place of the quantity type.

![purchase_process](https://user-images.githubusercontent.com/1082026/29607307-1dc19ff6-87f1-11e7-9a4f-d823d7f64b31.png)

---
## Branch
feature/add-reception-and-shipment

**Comment by DucMirack** [comment]
Fixed in : 12f2f5df16043272c460c90501a400c5b2027822
