### ISSUE TITLE
Storage zone not displayed in reception edit page

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#2130]
## Bug
When i edit a reception with a storage zone, nothing is displayed in place of the storage zone cell.

---
## Branch
feature/add-reception-and-shipment

**Comment by DucMirack** [comment]
Fixed in 406f46c4637461f0721f61a8ed865f24bb515d26

**Comment by DucMirack** [comment]
Fixed in 96925adcd2afa9e946a45a5d7d99fcebc7ad8817
