### ISSUE TITLE
Add :reference_number and :journal columns to the Journal Entries list in the Journal#show view.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#2145]
The `:journal` column should display the journal's code.

**Comment by Zank94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ekylibre:feature/accountancy-2018/add-reference-and-journal-columns-to-general-ledger](https://trello.com/c/hxZMZJ0R/333-ekylibrefeature-accountancy-2018-add-reference-and-journal-columns-to-general-ledger)
