### ISSUE TITLE
Missing translation in the graph "Transactions by month"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#2161]
In entities view, in the graph "Transactions by month", the translations (all languages) of "purchase_payments" are missing.

![image](https://user-images.githubusercontent.com/11627573/29874220-64910a8e-8d96-11e7-9259-80c77d95ac09.png)

**Comment by thib44** [comment]
https://github.com/ekylibre/ekylibre/pull/2181
