### ISSUE TITLE
restore a tenant error

### ISSUE THREAD

**Issue by bmabma** [ekylibre/ekylibre#2188]
In production mode, when restoring a tenant this error appears:
Ekylibre 2.50.3 
projects@host:~/ekylibre$ rake tenant:drop TENANT=xyz
Drop tenant: "xyz"
projects@host:~/ekylibre$ ARCHIVE=/home/projects/ekylibre/tmp/archives/xyz.zip RAILS_ENV=production rake tenant:restore tenant=xyz
Restoring 
Checking archive...
Resetting tenant Ekylibre::Tenant...
Restoring files...
Restoring database and migrating...
**cat: Ekylibre::Tenant.sql: Aucun fichier ou dossier de ce type**
Done! (14.37s)
projects@host:~/ekylibre$

**Comment by bmabma** [comment]
Ekylibre 2.51.1
today those commands works fine
$ RAILS_ENV=development rake tenant:restore TENANT=xyz ARCHIVE=./tmp/xyz.zip
or
$ RAILS_ENV=production rake tenant:restore TENANT=xyz ARCHIVE=./tmp/xyz.zip

but
$ RAILS_ENV=production rake tenant:restore TENANT=abcd ARCHIVE=./tmp/plants.zip
Restoring plants1
Checking archive...
Resetting tenant plants1...
Restoring files...
Restoring database and migrating...
**cat: abcd.sql: Aucun fichier ou dossier de ce type**
Done! (45.65s)
bernard@asus-stretch:~/ekylibre$

**Comment by burisu** [comment]
Yes, I confirm the bug when I tried to restore an archive with a new name.
I look into the archive and I saw that manifest.yml contains invalid data (tenant name is not what expected...)
There is another big thing for me, the SQL file in archive must have a constant name: `schema.sql`. @Aquaj, is there a special reason to keep tenant name in archive?
@thib44, can you take a look at these points? Thanks

**Comment by burisu** [comment]
#2055 and #2225 contributed to fix issue, but the last one #2251 will close it.
