### ISSUE TITLE
Payslip payment search bar doesn't work

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#2201]
Extracted from #2159.

In the menu HR/payslip-payments the research bar doesn't work (Classic and advanced research)

**Comment by thib44** [comment]
@burisu What do you mean by classic and advanced research ? In wich column do I need to do the search ? Can i have a spec ?

**Comment by burisu** [comment]
For advanced search, I think we talk about the "plus" which permits to add more filters.
A simple textual search can be done on:
- number
- amount
- employee first name
- employee last name

Advanced filters can be removed if any or not working. Is it OK for you, @thib44?

**Comment by thib44** [comment]
Yes it's ok, but i create advanced search :-) 
https://github.com/ekylibre/ekylibre/pull/2207

**Comment by thib44** [comment]
https://github.com/ekylibre/ekylibre/pull/2207
