### ISSUE TITLE
the graph of production costs in activity / production is false

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#2231]
when several crops are on a production, the average costs are added instead of being prorated on the surface of each crop.
Ex : if you seed 2 crops on a production (3ha) :  
- 2ha with 100€/ha of seed cost
- 1ha with 90€/ha of seed cost

The graph displays 190€/ha of seed cost

The chart should show (100x2+90x1)/3=96.66€/ha

**Comment by ionosphere** [comment]
Fixes. need to be test
