### ISSUE TITLE
Error when adding a new tractor

### ISSUE THREAD

**Issue by ptena** [ekylibre/ekylibre#2252]
![screenshot at 2017-11-02 16 41 12](https://user-images.githubusercontent.com/30928503/32336640-1e337ebe-bff0-11e7-9e4a-d40f1a0f39ce.png)
![screenshot at 2017-11-02 16 41 58](https://user-images.githubusercontent.com/30928503/32336658-2731cc50-bff0-11e7-816a-fa274195f037.png)

A NoMethodError occurred in equipments#create:

  undefined method `read_at' for nil:NilClass
  app/models/product_reading.rb:95:in `block in <class:ProductReading>'

* Parameters : {"utf8"=>"✓", "authenticity_token"=>"0VSx73uMaCEViRxSR30b6WakVdENjqPENdYjxexgRt//c+soSCd8i5IrbYr4Ds95OfTTMs5O4eVuIYLDR/84uQ==", "equipment"=>{"variant_id"=>"651", "name"=>"Tracteur", "work_number"=>"TRAC_01", "variety"=>"tractor", "born_at"=>"2017-05-18 16:40", "dead_at"=>"", "initial_owner_id"=>"", "initial_container_id"=>"", "initial_geolocation"=>"{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[1.32106044876702,43.7787709227038]}}", "description"=>"", "readings_attributes"=>{"0"=>{"product_id"=>"", "indicator_name"=>"fuel_consumption", "indicator_datatype"=>"measure", "measure_value_value"=>"8", "measure_value_unit"=>"liter_per_hour"}, "1"=>{"product_id"=>"", "indicator_name"=>"motor_power", "indicator_datatype"=>"measure", "measure_value_value"=>"80", "measure_value_unit"=>"french_horsepower"}, "2"=>{"product_id"=>"", "indicator_name"=>"net_surface_area", "indicator_datatype"=>"measure", "measure_value_value"=>"2", "measure_value_unit"=>"square_meter"}}}, "commit"=>"Créer", "controller"=>"backend/equipments", "action"=>"create"}

* Rails root : /var/www/sheep-prod/releases/20170927165433-ekylibre-2.52.2-2

**Comment by PH64** [comment]
the problem comes from the indicators: this error only occurs if the indicators are entered.
