### ISSUE TITLE
Purchase-process : error when we use the search bar

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#2255]
Views where the search bar fail : 
backend/unreceived_purchase_orders 
backend/purchase_orders 
backend/purchase_invoices

![recherche](https://user-images.githubusercontent.com/11627573/32490405-68b9b89c-c3b3-11e7-99d1-30fd316a7379.png)

**Comment by thib44** [comment]
- [ ] backend/unreceived_purchase_orders
- [ ] backend/purchase_orders
- [ ] backend/purchase_invoices

**Comment by thib44** [comment]
https://github.com/ekylibre/ekylibre/pull/2262
