### ISSUE TITLE
Purchase-process : error when we try to pay a "purchase_invoice"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#2257]
After the selection of the payement_mode (backend/purchase_invoices/1056/payment_mode), error when we try to valid the payment.
![payer mode](https://user-images.githubusercontent.com/11627573/32491504-4094e2f2-c3b7-11e7-8e6c-d9954f72d585.png)

**Comment by DucMirack** [comment]
Fixed in 431930a95b58a8f652fde8f6572f4422d5e58c9c @DucMirack DucMirack committed 2 minutes ago
