### ISSUE TITLE
Purchase-process : error when try to display list view of interventions

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#2258]
![interventions_liste](https://user-images.githubusercontent.com/11627573/32500345-6e1ada06-c3d5-11e7-934c-b1dc0425c61e.png)

**Comment by DucMirack** [comment]
Fixed in c73ae7a69a96fbd71ff7a47941aafdc8fdd0f4ce (look at 'app/models/intervention_input.rb')
