### ISSUE TITLE
Purchase-process : errors on several dashboard cells

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#2268]
Several cells of dashboards can't be displayed : 
- dashboard_stocks/last_outgoing_parcels
- dashboard_stocks/last_incoming_parcels
- dashboard_purchases/last_purchases

For example : 
![tdb_achats2](https://user-images.githubusercontent.com/11627573/32612725-41356ed0-c569-11e7-89db-ba4abf2528fe.png)

**Comment by thib44** [comment]
https://github.com/ekylibre/ekylibre/pull/2272
