### ISSUE TITLE
No VAT in sale invoice while added as a sale tax in product category 

### ISSUE THREAD

**Issue by ptena** [ekylibre/ekylibre#2284]

**Comment by ionosphere** [comment]
OK, i got it.
If the price catalog is all taxe included, even if the user put without taxe, the record will be all taxed included anyway. Same thing without all taxe included. So you have to check the price catalog before.
Anyway i push a fix with a label to avoid missing our users.

**Comment by ionosphere** [comment]
So this is what i made.
When you make a new sale, we catch ordering
1 - the last amount and tax of the last sale for the variant if any
2 - or the amount and tax of catalog item for the variant if any
3 - or the tax of category of the variant if any
4 - or the first current tax

**Comment by ionosphere** [comment]
Same thing with purchase
