### ISSUE TITLE
Net surface area is always 1ha in land parcels list

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#2294]
New land parcels created have always 1ha surface area in the list. But in land parcel view, net surface is right.
![capture du 2018-02-14 13-15-39](https://user-images.githubusercontent.com/12525665/36204096-2e51d8ae-118a-11e8-82e6-b28f1235f2a2.png)
![capture du 2018-02-14 13-15-53](https://user-images.githubusercontent.com/12525665/36204107-36e7a520-118a-11e8-8795-69f0d84745a0.png)

**Comment by bmabma** [comment]
the area is always 1 ha when the land parcel comes from cultivable zone transformed from PAC declaration.
The land parcel area is correct when the parcel is drawed by the user.

**Comment by PH64** [comment]
Land-parcels menu is no more used
