### ISSUE TITLE
Docker installation not described in documentation

### ISSUE THREAD

**Issue by jibe-b** [ekylibre/ekylibre#2436]
A [docker-compose.yml](https://github.com/ekylibre/ekylibre/blob/master/docker-compose.yml) file is available in the master branch but the documentation doest not describe installation using docker-compose.

**Comment by Gspohu** [comment]
There is a docker image in Docker Hub that corresponds to Ekylibre, but I don't know if it's registered by the project developers.
https://hub.docker.com/r/jhsu802701/debian-stretch-rails-ekylibre
If it's an official image, I can propose a PR to complete the documentation for the installation with Docker.

Can some contributors confirm this ?

**Comment by jibe-b** [comment]
Just a hint: the author of the docker image made only one commit to the codebase https://github.com/ekylibre/ekylibre/commits?author=jhsu802701

**Comment by piotaixr** [comment]
To my understanding, the docker-compose file in the Ekylibre repo was not meant to be used for installation as it describe only the external services (postgres/redis) required by the app.
I started 2 month ago (https://github.com/ekylibre/ekylibre/tree/feature/dockerfile-build-config) to create docker images to use for development. It is not complete or, i think, done the correct way.
I am no expert on using Docker, and to use the image for local development, you have to run everything in the container with a user that has the same UID/GID as your local user or you will have root-owned files in your homedir.
As I have a working dev environment working on my computer, i didn't push further, nor did I created a version that can be deployed in production as I have no need for it for now.

If you want to have a go at creating one, I will be happy to assist.

**Comment by fredericgermain** [comment]
I've made install based on docker-compose, and pushed it there https://gitlab.com/fredericgermain/ekylibre-docker-compose

I tried to focus on making a production image, and which would automatically set up an SSL letencrypt certificate. But development with it should be feasible, it just needs documentation.
But actually, it's not fully functional, and by default, it set up a server on localhost with demo data, and that's the only setup that works so far.

By the way, the demo data doesn't import well using the latest app version, or the latest demo data version. I made some hack to the image, but the data doesn't look all right when using the app. Data is pretty old (2016), maybe it would need some work before it works with the newest version of the app?

Precompile assets are not in the image and is generated at bootstrap. Precompiling assets is very long in this environment. I'm not sure why, maybe there is something wrong in the image, I don't know rails so much. But server works OK once fully configured.

The image is available as fredericgermain/ekylibre on hub.docker.com. you might need to change ekylibre:2.54.0-alpine by fredericgermain/ekylibre:2.54.0-alpine in docker-compose-alpine-http.yml

I chose to do an alpine image, which was quite a headache. You could push an ubuntu image, or whatever. The whole rails env seems to make the image big anyway (800MB), and I think the biggest remaining problems do not come from the choice of OS.

It seems hard to document it on https://forum.ekylibre.org or https://wiki.ekylibre.org, as the mailing systems seem down and I cannot register. Documentation is available on the README of the ekylibre-docker-compose though.

There are many ways to use docker, I just used it the way I found more appropriate after several years of casual practice. Please feel free to make comments about it.

**Comment by piotaixr** [comment]
That's great! You seem to have spent quite a lot on time on this!

> I tried to focus on making a production image, and which would automatically set up an SSL letencrypt certificate. But development with it should be feasible, it just needs documentation.
The problem i noticed about using a docker image for development is that having root executing the server is not a good idea as you will have root-owned files in hour homedir. And if you create a user with the same uid/gid as you in the image, its easier to have a rvm or rbenv-installed ruby. So the dev image is really different than the prod one.

> It seems hard to document it on https://forum.ekylibre.org or https://wiki.ekylibre.org, as the mailing systems seem down and I cannot register.
Oops, we will look into that!

> I chose to do an alpine image, which was quite a headache.
Yes, and the fact that the dependencies are quite outdated. We are working on compatibility with ruby 2.5.x or 2.6.x. Aside from some warning, it seems ready but i am still apprehensive about putting it on production officially.
It seems also that you are missing some dependencies in your image. You will have problems when importing attachments as it seems that you won't have the tesseract-ocr package. I also don't see libreoffice that is used in addition to odfreport to generate some documents (and more to come as we are moving away from jasper reports and rjb)

> You could push an ubuntu image, or whatever. The whole rails env seems to make the image big anyway (800MB), and I think the biggest remaining problems do not come from the choice of OS.
Yes, we have an awful lot of big dependencies. I've created a docker image for personal use based on ubuntu and with all dependencies, its bigger that 3GB.

Few comments about your compose config:
- You will want to also have a volume mounted in /app/private as uploaded and generated documents are put here
- There is a rake task to restore/dump your instance (tenant:dump/restore), as the file is by default exported to /app/tmp/archives, you may also want to have a volume there.
- For imports ans export (and some documents) you will need to have a sidekiq instance running, i don't see one in your compose file, maybe i missed it? In my experience, using the same base image as the rails app is fine. Don't forget to have both instance share the /app/private volume ;-)

**Comment by fredericgermain** [comment]
I think we could use this image for development: rails process is not supposed to write in the source directory (except logs, assets, ... which are in volumes). So we could mount the git source folder as /app/current, and we shouldn't get root-owned files in the git folder. Restarting the process is done by restarting the container, if you want to change Gemfile, you can exec bundle as root in the container, ... I'll have a look when I start debugging. For now, I need to get used to the app with my own data :)

From what you say, it might just be better to have a ubuntu image for now. And maybe aim at having a slimmer, alpine-compatible image later... Having docker image size as a reference would make it easier to know where to improve on the size maybe?

I will regenerate the image with the missing volumes. As for sidekiq, I still have no idea how to integrate it, I will have a look too...

Thanks for the helpful comment!

**Comment by piotaixr** [comment]
> From what you say, it might just be better to have a ubuntu image for now. And maybe aim at having a slimmer, alpine-compatible image later... Having docker image size as a reference would make it easier to know where to improve on the size maybe?

I have 2 images that run in prod for my personal use:
- rails (for rails and sidekiq), based ruby:2.6: 3.12GB
- web, (for assets) based on abiosoft/caddy:no-stats: 112MB
The assets are compiled at image build time (and burned in the web image)
