### ISSUE TITLE
Improve use of redirect

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#250]
When one validates a form from somewhere else in Ekylibre, he should be redirected to this place after edit.

For instance:
When one create an incident from a cow (in cow view), he is redirected to incident list instead of being redirected to its cow.

See http://forum.ekylibre.org/t/ergonomie/127/3 for further explanation.

**Comment by burisu** [comment]
Considered as solve after generalization of `redirect` parameter use across tool_to, tables and controllers.
