### ISSUE TITLE
Filter intervention type

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#253]
As Vivien noticed, backend/interventions/new is quite confusing. 
http://forum.ekylibre.org/t/ergonomie/127/2?u=coren

Maybe we can list all possible interventions, without any categories, and allow users to filter them.

And maybe we can put those filters in account preferences, in order to filter this all over Ekylibre.

**Comment by PH64** [comment]
a new classification system was adopted in v2.0
