### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by paulinK** [ekylibre/ekylibre#2565]
Hi everyone

I am new to using ruby. I found this wonderful application, ekylibre, and wanted to install it to explore it.
Only, since I tried, the installation tutorials seem incomplete or old.

I finally found this, [https://wiki.ekylibre.org/fr/guides/installation-on-ubuntu-18-04](https://wiki.ekylibre.org/fr/guides/installation-on-ubuntu-18-04) But after installation, I ended up with the following messages when the server started:

> /home/paulin/code/ekylibre/app/concepts/readings_coder.rb:14: warning: constant ::Bignum is deprecated
/home/paulin/code/ekylibre/app/concepts/readings_coder.rb:15: warning: constant ::Fixnum is deprecated
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: already initialized constant RestfullyManageable::Backend_AnimalGroupsActions
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: previous definition of Backend_AnimalGroupsActions was here
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: already initialized constant RestfullyManageable::Backend_PurchasePaymentsActions
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: previous definition of Backend_PurchasePaymentsActions was here
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: already initialized constant RestfullyManageable::Backend_SaleNaturesActions
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: previous definition of Backend_SaleNaturesActions was here
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: already initialized constant RestfullyManageable::Backend_SaleOpportunitiesActions
/home/paulin/code/ekylibre/app/controllers/concerns/restfully_manageable.rb:364: warning: previous definition of Backend_SaleOpportunitiesActions was here
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop

> Started GET "/" for 127.0.0.1 at 2020-02-26 18:46:58 +0000
  ActiveRecord::SchemaMigration Load (1.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
[ElasticAPM] Couldn't establish connection to APM Server:
"#<HTTP::ConnectionError: failed to connect: Connection refused - connect(2) for \"localhost\" port 8200>"
Processing by PublicController#index as HTML
  Preference Load (1.0ms)  SELECT  "preferences".* FROM "preferences" WHERE "preferences"."name" = $1 LIMIT 1  [["name", "language"]]
Redirected to http://localhost:3000/sign-in
Completed 302 Found in 53ms (ActiveRecord: 3.3ms)

By the way, here is an overview of the web display I get : [image](https://www.zupimages.net/viewer.php?id=20/09/88mc.png)

Could someone help me, by offering me a more complete or more recent tutorial.

Thank you in advance !

@piotaixr

**Comment by piotaixr** [comment]
Hello,

It seems that you managed to install the base app correctly.
For the warning messages at the begining, they are not important. The first two about Fixnum and Bignum are there because you are not using ruby 2.3.x but a more recent version. No worries, though, ekylibre seems to work fine for ruby up to 2.6.x even with the warnings.
Everything about RestfullyManageable can be ignored for now.

Ekylibre is built with multi-tenancy in mind (one installation can handle multiple different farms, each with their own set of users), once the app installed, you need to create a tenant to start using it.
That's what the `rake tenant:create TENANT=demo` means: It creates a tenant names demo and initializes it with an admin user (admin@ekylibre.org/12345678) hint: change the password :-D

For ekylibre to know which tenant you want to use, two possibilities:
Either start the server with the TENANT env variable set to your tenant name:
`TENANT=demo rails s -b 0.0.0.0`
Or, you can use the multi-tenancy system that directly looks for the subdomain name.
For this you will need to edit the `/etc/hosts` file and ass the lines (for example):
`127.0.0.1 demo.ekylibre.lcom`
You will then be able to access the demo tenant at the address `https://demo.ekylibre.lcom:3000` locally.

For your error message, it seems that you tried to create a new account.
I must admit that we are not using it internally to create users so its totally possible that its not working. Just try to log-in with the admin user and create new users from the farm interface.

**Comment by paulinK** [comment]
Hi @piotaixr 

Thank you very much for responding. I set to work, to adjust the installation according to your recommendations. And I will give you feedback.
cordially

**Comment by paulinK** [comment]
good evening

I tried to reinstall ekylibre, and advanced to the first_run stage.
When trying to run the following command line

`JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 rake first_run name=demo folder=demo max=80 `

I am faced with the following error.

> ✔ Ekylibre settings (manifest.yml)                                                     21 done in 14s
 ✔ Ekylibre visuals (background.jpg)                                                      1 done in 1s
 ∅ Ekylibre backup (backup.zip)                                                                       
 ✔ Ekylibre accounts (accounts.csv)                                                      80 done in 0s
 ✔ Ekylibre variants (variants.ods)                                                       4 done in 9s
 ✔ Ekylibre entities (entities.csv)                                                      29 done in 4s
 ∅ La graine informatique vinifera entities (entities.zip)                                            
 ✔ Ekylibre georeadings (cultivable_zones.zip)                                           37 done in 0s
 ✔ Ekylibre georeadings (zones.zip)                                                      59 done in 0s
 ∅ Ekylibre land parcels (land_parcels.csv)                                                           
 ✔ Ekylibre cultivable zones (cultivable_zones.csv)                                      30 done in 0s
 ∅ Telepac v2014 cap land parcels (ilot.zip)                                                          
 ∅ Telepac v2014 land parcels (parcelle.zip)                                                          
 ∅ Telepac v2015 cap land parcels (ilot.zip)                                                          
 ∅ Telepac v2015 land parcels (parcelle.zip)                                                          
rake aborted!
ActiveRecord::RecordInvalid: Validations échouées : Type n’est pas inclus dans la liste
/home/paulin/ekylibre/app/models/import.rb:72:in `launch!'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:188:in `import!'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:236:in `import'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:121:in `import_file'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:67:in `block (2 levels) in run_loader'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:58:in `each'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:58:in `block in run_loader'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:54:in `run_loader'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:45:in `block (2 levels) in run'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:44:in `each'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:44:in `block in run'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:82:in `secure_transaction'
/home/paulin/ekylibre/lib/ekylibre/first_run/base.rb:43:in `run'
/home/paulin/ekylibre/lib/ekylibre/first_run.rb:60:in `block in launch'
/home/paulin/ekylibre/lib/ekylibre/first_run.rb:77:in `block in secure_tenant'
/home/paulin/ekylibre/lib/ekylibre/tenant.rb:228:in `switch'
/home/paulin/ekylibre/lib/ekylibre/first_run.rb:76:in `secure_tenant'
/home/paulin/ekylibre/lib/ekylibre/first_run.rb:56:in `launch'
/home/paulin/ekylibre/lib/ekylibre/first_run.rb:23:in `launch!'
/home/paulin/ekylibre/lib/tasks/first_run.rake:46:in `block in <top (required)>'
Tasks: TOP => first_run
(See full trace by running task with --trace)


If I try to continue, with starting the server, I cannot sign in.

Do you have any idea that could help me, to correctly execute this command line.

Thank you in advance !

**Comment by paulinK** [comment]
Hi @piotaixr 

I hope you feel well. After looking for a solution, I notice that the error come from the demo dataset. I think we have to update the dataset. Maybe it contains some obsolete data.

Would it be possible, that I obtain a dataset, adapted to the current version of ekylibre

Cordially

**Comment by piotaixr** [comment]
Sorry for the delay. Working on it as soon as I have the time to do it :s
