### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [ekylibre/ekylibre#2589]
Hey there!

I belong to an open source security research community, and a member (@asura-n) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
Just for reference, all reports can be found here:

https://huntr.dev/bounties/55117ebb-93e2-4fe4-ac87-0c627bf735dc/
https://huntr.dev/bounties/77204576-00d4-4044-ab69-7a6c35b4307f/
https://huntr.dev/bounties/b7b45b6f-1461-47fe-ba34-0d1c47fca668/
https://huntr.dev/bounties/b0802f50-fbf8-4368-bca7-41d85ff29e1e/
