### ISSUE TITLE
Error when running docker version of Ekylibre

### ISSUE THREAD

**Issue by pchg** [ekylibre/ekylibre#2600]
After following instructions in ekylibre/docker/README.md , I got my Ekylibre docker-compose up and running.

So I began to discover Ekylibre, from a user's point of view.  Everything went fine, until the moment when I tried to enter a new "Zones cultivables" ("Cultivable Zone": sorry for the French, I tried to set "English" as default language, but it obviously had no immediate effect; anyway, I suppose that most people out here speak some French...) within this URI:

 http://default.ekylibre.lan:3000/backend/cultivable-zones

I clicked on "Nouveau" ("New"), digitized my field, and when I cliked on "Créer" ("Create"), I got the following error:
```
Errno::ENOENT in Backend::CultivableZones#show
Showing /eky/app/views/backend/cultivable_zones/show.html.haml where line #9 raised:
No such file or directory @ rb_sysopen - /usr/share/proj/epsg

Extracted source (around line #32):

         if hash[:shape]
           global = (global ? global.merge(hash[:shape]) : Charta.new_geometry(hash[:shape]))
           hash[:shape] = Charta.new_geometry(hash[:shape]).transform(:WGS84).to_json_object
         end
         hash
      end

Rails.root: /eky
```
The line with the call to transform() is highlighted in red.

It looks like there is no proj installed, and it seems to be happening within one of the containers, as proj is definitely installed on my physical machine, and ./usr/share/proj/epsg does actually exist on my system.

**Comment by SiM** [comment]
Hi,
Same error here.

**Comment by pchg** [comment]
When looking at ekylibre/docker/dev/Dockerfile , I can see that there is an installation of libproj-dev:

```
RUN
[...]
    apt-get -y install netcat build-essential libreadline-dev libssl-dev zlib1g-dev \
		nodejs \
        graphicsmagick \
        postgresql-client \
        libproj-dev libgeos-dev libgeos++-dev `#rgeo` \
        openjdk-11-jdk  `#rjb` \
        libicu-dev `#charlock_holmes` \
        libpq-dev `#pq` \
        libreoffice \
        libsodium-dev \
        poppler-utils tesseract-ocr tesseract-ocr-fra tesseract-ocr-ara tesseract-ocr-eng  `#ocr` \
        tesseract-ocr-jpn tesseract-ocr-osd tesseract-ocr-spa  `#ocr` && \
```
I'll try to add the proj package to that line, and see what happens.

Not these days though, sorry: I'm way too busy with many other tasks.

**Comment by ThibautGrx** [comment]
Hi, 
Sorry for the delay.
One of our dependencies (Rgeo) depends on proj 4. But, by default proj 7.2.1-1 is installed so there is a workaround described in the install doc : https://github.com/ekylibre/ekylibre/wiki/Base-ubuntu-20-04#d-proj
It will be fixed in the next release. 
Thanks for reporting this issue.

**Comment by pchg** [comment]
Hello,

> One of our dependencies (Rgeo) depends on proj 4. But, by default proj 7.2.1-1 is installed so there is a workaround described in the install doc : https://github.com/ekylibre/ekylibre/wiki/Base-ubuntu-20-04#d-proj

Thanks for the answer, sorry I didn't see it earlier...  I'll try to see if I can implement this workaround in the docker stuff.

**Comment by HLFH** [comment]
ok
