### ISSUE TITLE
API Web Service for data integration automation ?

### ISSUE THREAD

**Issue by kyo06** [ekylibre/ekylibre#2606]
Hello,

Thank you for you work.
We are very happy to use it.

But We have a question : 
Is there an API webservices to integrate data (API REST or SOAP) ?

Thank you for your answer in advance.

**Comment by ThibautGrx** [comment]
Hi Kyo06,

API is still under development, but there are already some available end points. 
He is the documentation: https://ekylibre.stoplight.io/docs/eky/751aacde8cec8-ekylibre

I hope this answers your question. 

Just out of curiosity, what kind of integration would you like to do ?
