### ISSUE TITLE
How to install Ekylibre in production mode on VPS ?

### ISSUE THREAD

**Issue by ThibautGrx** [ekylibre/ekylibre#2619]
Start by  ordering a new VPS  with ubuntu 20.04 on your cloud provider.

# 1/ Set up user

* Log into yout vps, with the root user. You should received username and password form your cloud provider. 

`$ ssh <username>@<vps_ip>`

# 2/ Configure ssh access

`$ ssh-copy-id <username>@<vps_ip>`
`$ ssh-copy-id ekylibre_user@<vps_ip>`

# 3/ Install ekylibre

`$ ssh <root_user>@<vps_ip>`

* Follow [install steps](https://github.com/ekylibre/ekylibre/blob/main/doc/Installation/Global/Ubuntu%2020.04%20LTS.md) 

* Create production database
RAILS_ENV=production rake db:create db:migrate

* Load lexicon
RAILS_ENV=production rake lexicon

* Compile assets
RAILS_ENV=production rake assets:precompile

# 4/ install nginx

`$ sudo apt-get install nginx`

Start by checking the status of the Nginx service:

`$ sudo systemctl status nginx`

If Nginx is not running, use the following command to launch the Nginx service:

`$ sudo systemctl start nginx`

To set Nginx to load when the system starts, enter the following:

`$ sudo systemctl enable nginx`

update Nginx config:

`$ sudo vim /etc/nginx/sites-enabled/default`

```
upstream ekylibre_upstream {
    server 127.0.0.1:3000 fail_timeout=0;
}

server {
    listen      80;
    server_name ekylibre;
    access_log /var/log/nginx/ekylibre.access.log;
    error_log  /var/log/nginx/ekylibre.error.log;
    root /home/ubuntu/ekylibre/public;

    client_max_body_size 10M;
    resolver 8.8.4.4 8.8.8.8;

    location ~ "^/([0-5]{3}.html|system|images|assets|favicon.ico|robots.txt)"  {
        gzip_static   on;
        expires       max;
        add_header    Cache-Control public;
        break;
    }

    location ~ ^/cable {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_pass http://ekylibre_upstream;
        break;
    }

    location / {
        error_page 404              /404.html;
        error_page 422              /422.html;
        error_page 500 502 503 504  /500.html;
        error_page 403              /403.html;
        try_files $uri @app;
    }

    location @app {
        proxy_pass http://ekylibre_upstream;
        proxy_redirect off;
        proxy_read_timeout 600s;
        proxy_connect_timeout 1200;
        proxy_send_timeout 1200;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port  443;
        proxy_set_header X-Forwarded-Ssl   on;
    }
}
```

Reload: 
`$ sudo systemctl reload nginx`

**Comment by HLFH** [comment]
up

until setup is fixed
