### ISSUE TITLE
Add some field products

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#263]
See http://forum.ekylibre.org/t/creation-des-produits/78/17:

- [ ] Cresson
- [ ] Courgette
- [x] Concombre
- [x] Cornichon
- [ ] Courge
- [ ] Patisson
- [x] Pastèque
- [ ] Epinard
- [x] Melon
- [ ] Fenouil
- [ ] Fève
- [ ] Haricot vert
- [ ] Haricot beurre
- [ ] Laitue
- [ ] Batavia
- [ ] Mâche
- [ ] Panais
- [x] Poireau
- [x] Pois
- [x] Radis
- [ ] Patate douce
- [x] Persil
- [ ] Ciboulette
- [ ] Thym
- [ ] Chayotte

**Comment by PH64** [comment]
All this add have been done
