### ISSUE TITLE
Translation of yaml reserved words

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#266]
As explained [here](http://juliankniephoff.wordpress.com/2012/09/01/reserved-words-in-yaml-and-translating-booleans-in-rails/), one cannot translate true into "Vrai", but only "true" into "Vrai".

Since config/locales/fra/support.yml is re-written by _rake clean_, _rake clean_ needs to re-write in a YAML-compliant way all [reserved words](http://www.rubymagic.org/posts/ruby-and-rails-reserved-words).

**Comment by burisu** [comment]
Not receivable because we don't want to have boolean or non-string values as keys in translations files, because it will be source of errors in some i18n tasks
