### ISSUE TITLE
How to upload a (prescription) file and link it to an intervention

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#300]
*User Case
in order to have a good medicine traceability, i have to scan my prescription and add it to the animal medicine intervention
see http://forum.ekylibre.org/t/gestion-des-documents/182/2

*Todo
adapt document and document archive model and add an "upload" button when creating an external document.

**Comment by burisu** [comment]
We can upload files on prescription records, issue records and intervention records. I consider that feature is done.
