### ISSUE TITLE
Cannot perform home_coming ([driver] moves in default storage) when driver has no default storage in intervention run

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#330]
Add required field 'initial_container ' in order to avoid mistakes during interventions

see http://forum.ekylibre.org/t/production-intervention-transport-de-grain/230

**Comment by burisu** [comment]
Not the real problem. A enhancement on procedure will solve problem.

**Comment by burisu** [comment]
Will be fixed on 2.0.0

**Comment by burisu** [comment]
Fixed :facepunch: !
