### ISSUE TITLE
Unable to export general_ledger in CSV Excel

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#331]
see http://forum.ekylibre.org/t/comptabilite/271

Encoding error:
Encoding::UndefinedConversionError in Backend::JournalsController#list_general_ledger
U+2012 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252

To reproduce this bug:

1/ Go to ...backend/journals/general_ledger
2/ Clic on Export to CSV Excel on the list

**Comment by burisu** [comment]
Bug in active_list fixed with ekylibre/active_list@e8db22b55a0352df26ebe5c873bddb16cdd5392b.
