### ISSUE TITLE
When missing owner during new incoming delivery, the show view of the concerning product is buggy

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#332]
When missing owner during new incomming_delivery, no default owner was create at all

To reproduce

1/ Create a new incoming delivery with one product without mentionning the owner
2/ Go to this delivery and clic on the product line

**Comment by Nyxelio** [comment]
No way to reproduce this issue, still alive ?

**Comment by ionosphere** [comment]
OK i confirm,  no way to reproduce this bug now
