### ISSUE TITLE
List build from nomenclatures must be ordered by default in current user langage

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#346]
![list](https://cloud.githubusercontent.com/assets/1838491/6381506/e237cb3a-bd41-11e4-81a0-11f40b4f1d8d.png)

**Comment by burisu** [comment]
It's a problem with enumerize which don't sort. Indeed enumerize is supposed to be used with little list which is not so problematic in this case. Sorts are done when collections are set manually (< 10% of cases).

**Comment by burisu** [comment]
Since introduction of `f.referenced_nomenclature` in 7125148c53f22e80a21234915ccc4483062a3ab9 for `refers_to` relations, I consider problem as solved. As it's quite difficult to detect which `f.input` should be converted, you should re-open it when you find one or open a new issue.
