### ISSUE TITLE
InterventionRegistry export doesn't work

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#352]
An ActionView::Template::Error occurred in exports#show:

  undefined method `variety' for nil:NilClass
  app/models/production_support.rb:228:in `block (2 levels) in grains_yield'

-------------------------------
Request:
-------------------------------

  * URL        : http://demo.ekylibre.farm/backend/exports/intervention_registry
  * HTTP Method: GET
  * IP address : 46.29.126.58
  * Parameters : {"controller"=>"backend/exports", "action"=>"show", "id"=>"intervention_registry"}
  * Timestamp  : 2015-03-10 10:50:01 +0100
  * Server : ma001
  * Rails root : /var/www/sheep-demo/releases/20150308192415-ekylibre-1.1.0.rc1
  * Process: 6902

-------------------------------
Backtrace:
-------------------------------

  app/models/production_support.rb:228:in `block (2 levels) in grains_yield'
  app/models/production_support.rb:227:in `block in grains_yield'
  app/models/production_support.rb:226:in `grains_yield'
  app/views/backend/exports/show.html.haml:9:in `_app_views_backend_exports_show_html_haml___3929935778702822069_70018484085340'
  app/controllers/backend/base_controller.rb:42:in `respond_with_with_template'
  app/controllers/backend/exports_controller.rb:38:in `show'

**Comment by Nyxelio** [comment]
InterventionRegistry seems to work now.
