### ISSUE TITLE
Removes state_label methods in models

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#361]
`state_label` is not a valid way to get human name of a state (of state machine). Localization must do the job as usual like `state.l` or `state.human_name`.

**Comment by Aquaj** [comment]
Seems to have been fixed. 
- Example of current implementation :
 app/models/purchase.rb:235 : `self.class.state_machine.state(self.state.to_sym).human_name

Changes brought by 686f4a70.
