### ISSUE TITLE
No way to add an intervention from production_support list

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#366]
ActionController::UrlGenerationError in Backend::Interventions#new

Showing /home/djoulin/projects/ekylibre/app/views/backend/interventions/_form.html.haml where line #6 raised:

No route matches {:action=>"new", :controller=>"backend/production_supports"}

Extracted source (around line #55):

53
54
55
56
57
58
              

	

return input(reflection.foreign_key, options.merge(wrapper: (options[:wrapper] == :nested ? :nested_append : :append), reflection: reflection)) do
self.input_field(reflection.foreign_key, html_options.deep_merge(as: :string, id: input_id, data: {selector: @template.url_for(choices), selector_new_item: @template.url_for(new_url), value_parameter_name: options[:value_parameter_name] || reflection.foreign_key}))
end
end

Trace of template inclusion: app/views/backend/base/new.html.haml

![screenshot - 13032015 - 16 10 14](https://cloud.githubusercontent.com/assets/1838491/6641007/7b177912-c99b-11e4-82c2-ca4e06a9ac32.png)

**Comment by Nyxelio** [comment]
This issue is fixed.
