### ISSUE TITLE
Error when updating animal budget with 

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#370]
Something when wrong with support_variant_unit

![animal_budget_2](https://cloud.githubusercontent.com/assets/1838491/6658295/c96e438c-cb64-11e4-8850-92cd40ab75c8.png)

![animal_budget](https://cloud.githubusercontent.com/assets/1838491/6658297/cd7c98f2-cb64-11e4-8c3c-1f891128de11.png)

**Comment by burisu** [comment]
Fixed with 1356343446cb971020c402270b68d0bf278829f6.
