### ISSUE TITLE
Need to check if entity exist before creating it during first_run

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#371]
From V.LEVAVASSEUR
the fact to register his name in alamano and the third file creates twice the third. However, the address is not filled in Alamano and features of thirds may not be recordable in the third file.

**Comment by burisu** [comment]
How do you identify thirds ?

**Comment by ionosphere** [comment]
by full_name

**Comment by burisu** [comment]
As we can see in the demo, the problem is not here because first and last name are the same.
The names in `manifest.yml` and `alamano/entities.csv` don't match.
