### ISSUE TITLE
invalid byte sequence in UTF-8 during first run georeadings import

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#377]
[earl-masle] Telepac land parcels (parcelle.zip)                  37 done in 11s
Ekylibre georeadings (cultivable_zones.zip) ||||||||||||||||||||||||||||| 35% 1srake aborted!
ArgumentError: invalid byte sequence in UTF-8

ArgumentError: invalid byte sequence in UTF-8

I haven't found special caracters.

**Comment by burisu** [comment]
Cannot reproduce bug with same data. @ionosphere, feel free to re-open it when it fails again.
