### ISSUE TITLE
An ActionView::Template::Error occurred in crumbs

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#380]
An ActionView::Template::Error occurred in crumbs#index:

  undefined method `read_at' for nil:NilClass
  app/models/crumb.rb:168:in `intervention_path'

-------------------------------
Request:
-------------------------------

  * URL        : http://haurigot.ekylibre.farm/backend/crumbs
  * HTTP Method: GET
  * IP address : 87.100.83.154
  * Parameters : {"controller"=>"backend/crumbs", "action"=>"index"}
  * Timestamp  : 2015-03-24 13:06:19 +0100
  * Server : ma001
  * Rails root : /var/www/sheep-beta/releases/20150323233758-ekylibre-1.1.0

-------------------------------
Backtrace:
-------------------------------

  app/models/crumb.rb:168:in `intervention_path'
  app/models/user.rb:242:in `interventions_paths'
  app/views/backend/crumbs/index.html.haml:4:in `_app_views_backend_crumbs_index_html_haml___3294851134622233570_70158352472880'

**Comment by burisu** [comment]
The bugs seems to come from invalid data pushed from Zero.
