### ISSUE TITLE
An ActionView::Template::Error occurred in crumbs

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#384]
An ActionView::Template::Error occurred in crumbs#index:

  undefined method `human_name' for nil:NilClass
  app/models/crumb_set.rb:41:in `human_name'

-------------------------------
Request:
-------------------------------

  * URL        : http://scea-daspe.ekylibre.farm/backend/crumbs
  * HTTP Method: GET
  * IP address : 78.234.135.3
  * Parameters : {"controller"=>"backend/crumbs", "action"=>"index"}
  * Timestamp  : 2015-03-24 16:00:12 +0100
  * Server : ma001
  * Rails root : /var/www/sheep-prod/releases/20150323234055-ekylibre-1.1.0

-------------------------------
Backtrace:
-------------------------------

  app/models/crumb_set.rb:41:in `human_name'
  app/views/backend/crumbs/index.html.haml:6:in `block in _app_views_backend_crumbs_index_html_haml___453527967170501972_69922102705820'
  app/views/backend/crumbs/index.html.haml:5:in `each'
  app/views/backend/crumbs/index.html.haml:5:in `_app_views_backend_crumbs_index_html_haml___453527967170501972_69922102705820'

**Comment by burisu** [comment]
The bug is due to invalid procedure name unknown in actual [nomenclature](http://open-nomenclature.org/nomenclatures/procedure_natures).
