### ISSUE TITLE
No way to add an incoming delivery item

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#397]
When selecting a variant, the "Add" button produce nothing
in backend/incoming_deliveries/new
![incoming_delivery_none](https://cloud.githubusercontent.com/assets/1838491/6918075/acc7b7e8-d7aa-11e4-9312-63cde0895a15.png)

**Comment by burisu** [comment]
Side effect of 4c555d861ba18cd8aaa7ae69d31d56537b2c0e89.
