### ISSUE TITLE
1 cent error on total appears in purchase

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#407]
when making a purchase, 1cent error appearing in total. see example below

![purchase_1cent](https://cloud.githubusercontent.com/assets/1838491/7220104/6f8075d4-e6bc-11e4-95b8-3adfff549aed.PNG)

**Comment by burisu** [comment]
I can reproduce and don't find any problem:
  - 11.82 x 4 = 47.28 (pretax amount)
  - 47.28 x 1.10 = 52.008 ≈ 52.01 (total amount)

To get 52.00, 3 ways:
  1. Round cents to floor of VAT amount before sum it to total pretax amount
  2. Round cents to floor of total amount
  3. No it's cool, 52.01 is what we really want

**Comment by burisu** [comment]
All computation processes have been reviewed with f3869bd9040777398695c3b6de5cd4e1e328d6ad.
