### ISSUE TITLE
i18n - Translation for portuguese

### ISSUE THREAD

**Issue by danimaribeiro** [ekylibre/ekylibre#411]
Hi Guys, I'd like to translate to portuguese, but rails is not my best.
Should I just copy 'locales/eng' to locales to 'locales/por' and start translate?

**Comment by ionosphere** [comment]
Hi @danimaribeiro , you're welcome to translate. I let the lead developper @burisu answer to your question but i know it's as simple as you describe in 4/5 files in YML.

**Comment by burisu** [comment]
Hi I see the request and I prepare base files for portuguese translation. I hope this will help.
To do this, I add the translation code `:por` in `config/application.rb` and I ran `rake clean`. I added manually the conf file `config/locales/por/i18n.rb`.
Ask if it's OK for you @danimaribeiro

**Comment by danimaribeiro** [comment]
Thanks for the quickly answer.
Already made a PR for the first part, in the next few days I'll keep working on the rest of translation.

**Comment by Aquaj** [comment]
I'm closing the issue since the whole process moved to PRs and that a good part of the translation is here already.
