### ISSUE TITLE
No route matches [GET] "/backend/map" when accessing to map then list

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#416]
Bug on clic in list then map in interventions#index view
No route matches [GET] "/backend/map"

![screenshot - 04062015 - 22 21 38](https://cloud.githubusercontent.com/assets/1838491/7993675/19060a0a-0b08-11e5-822b-12a597443978.png)

**Comment by burisu** [comment]
No way to reproduce bug for now

**Comment by burisu** [comment]
The bug is still present. It can be reproduced on productions#show view after a production creation.
