### ISSUE TITLE
No way to duplicate sale

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#424]
When we try to duplicate sale, an error appears. undefined method `build' for #<Class:0x007f6726792cc0>

![clone_sale](https://cloud.githubusercontent.com/assets/1838491/8116597/3312febe-1083-11e5-9b81-9ce0432045f8.png)

**Comment by burisu** [comment]
This bug was introduced in same time as the product_nature_variants was... a long time ago...
