### ISSUE TITLE
Highcharts is non-free software

### ISSUE THREAD

**Issue by rdoursenaud** [ekylibre/ekylibre#426]
Highcharts is creative commons only for non-profit and/or non-commercial use. See: https://shop.highsoft.com/highcharts.html

Free alternatives exist and should be supported such as [C3js](http://c3js.org/) based on the powerful D3 library.

**Comment by ChristopheRaix** [comment]
Thanks for this feedback. We will look forward C3js. It seems to be a powerfull tool.
Next version will try to fix it.
We will keep you and community in touch about this issue.

**Comment by ionosphere** [comment]
From now we have Highchart working well in Ekylibre and we have subscribe a licence for this.
It's true that we have to select only free alternatives, in a perfect world. In debate for Ekylibre 2.0, if

**Comment by rdoursenaud** [comment]
@ionosphere No problem. I was just surprised as this is not obvious and can lead to very painful legal issues. I don't think it's compatible with the advertised AGPLv3 license either.
In the meantime, a bit of documentation could help mitigating the issue.
