### ISSUE TITLE
An error occurred on animal moving intervention

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#431]
This errror spawns when I want to register a new intervention through an animal drop on a new container:
{:reference_name=>"base-animal_changing-0", :production_support=>#<ProductionSupport id: 58, production_id: 19, storage_id: 305, created_at: "2015-06-07 14:38:33", updated_at: "2015-06-07 14:38:33", creator_id: nil, updater_id: nil, lock_version: 0, production_usage: "fodder", quantity: #<BigDecimal:7fe8d7c24d28,'0.0',9(27)>, quantity_indicator: "members_population", quantity_unit: nil>, :started_at=>"2015-06-17 17:45", :stopped_at=>"2015-06-18 13:45", :natures=>"animal_moving"}

 NoMethodError (undefined method `variables' for nil:NilClass):
  app/models/intervention_cast.rb:143:in `reference'
  app/models/intervention_cast.rb:83:in `block in <class:InterventionCast>'
  app/models/intervention.rb:329:in `add_cast!'
  app/models/intervention/recorder/cast.rb:16:in `save!'
  app/models/intervention/recorder.rb:17:in `block in write!'
  app/models/intervention/recorder.rb:15:in `each'
  app/models/intervention/recorder.rb:15:in `write!'
  app/models/intervention.rb:363:in `block in write'
  app/models/intervention.rb:353:in `write'
  app/controllers/backend/animals_controller.rb:192:in `change'

**Comment by burisu** [comment]
The problem was due to invalid reference use. Fixed with 349622eefb9246b2dd6150ff6b2c1df5c28485ff.
