### ISSUE TITLE
mistake on purchase item

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#443]
there a prob,;dg,dpnvgld 

https://demo.ekylibre.farm/backend/purchases/1

![screenshot - 31072015 - 15 47 00](https://cloud.githubusercontent.com/assets/1838491/9008551/68a06fdc-379b-11e5-8fa5-4223dd083210.png)

**Comment by burisu** [comment]
What's the problem ?

**Comment by PH64** [comment]
There's no problem. It's just a test for the maintenance department

**Comment by burisu** [comment]
OK :smile:
