### ISSUE TITLE
undefined method `human_name' for nil:NilClass in land parcel list

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#448]
red page in production when having access to show view in land_parcel

An ActionView::Template::Error occurred in land_parcels#show:
  undefined method `human_name' for nil:NilClass
  app/views/backend/land_parcels/show.html.haml:14

![human_name_landparcel_nil class](https://cloud.githubusercontent.com/assets/1838491/9219854/3e02beb4-40de-11e5-8885-d51520314485.png)

**Comment by Nyxelio** [comment]
Some landParcel soil natures don't match with nomenclature:
Ex: parcel.soil_nature return "red_chesnut_soil' but Nomen::Item seems to be "chesnut_red_soil"
