### ISSUE TITLE
One of the following schema(s) is invalid: "ec2-52-XX-XX-XX" "public", "postgis"

### ISSUE THREAD

**Issue by trax44** [ekylibre/ekylibre#452]
Hi,

on a fresh install, following 
https://github.com/ekylibre/ekylibre/blob/master/doc/guides/installation.rdoc
on an Ubuntu 14.04 (and using ubuntu packages for postgis)
When I run the application I got the following error: 

      rescue *rescuable_exceptions
        raise TenantNotFound, "One of the following schema(s) is invalid: \"#{tenant}\" #{full_search_path}"
      end

      #   Create the new schema

In apartment (1.0.2) lib/apartment/adapters/postgresql_adapter.rb:92:in `rescue in connect_to_new'

Any idea on how to fix that? (not really fluent in RoR/psql/)

regards 
trax

**Comment by burisu** [comment]
Hello Trax,

By default you need to use a subdomain like demo.ekylibre.lan. The system detects the "demo" in the subdomain. Else you need to specify env variable TENANT with the tenant name you created to be independent of your domain.
```bash
rake first_run:default TENANT=mytenant
```
So, for example:
```bash
rails server TENANT=mytenant
```
