### ISSUE TITLE
Missing toolbar allowing printing on exports

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#460]
Missing print button on:
- manure management plan
- provisional manure management plan
- exchange accountancy file
- income statement
- products sheet

**Comment by PH64** [comment]
Salut Nicolas, 

N'est-ce pas lié au fait que les modèles de
documents correspondants ne sont pas chargés dans l'instance ? 

A+


Pierre 

--

 PIERRE HAURIGOT
 Farmer expert - Expert AgroTIC

EKYLIBRE - Connecting farms to the world 
 Tel. +33 (0)6.68.53.71.79
[2]
 ekylibre.com [3] - Facebook [4] - Twitter [5] - LinkedIn [6] -
Google+ [7] 

Le 19/10/2015 11:01, Nicolas PROCUREUR a écrit : 

>
Missing print button on: 
> 
> * manure management plan
> * provisional
manure management plan
> * exchange accountancy file
> * income
statement
> * products sheet
> 
> --
> Reply to this email directly or
view it on GitHub [1].
 

Links:
------
[1]
https://github.com/ekylibre/ekylibre/issues/460
[2]
tel:+33(0)6.68.53.71.79style=
[3] http://www.ekylibre.com
[4]
http://www.facebook.com/ekylibre
[5] http://www.twitter.com/ekylibre
[6]
http://www.linkedin.com/company/ekylibre
[7]
https://plus.google.com/+EkylibreOfficial

**Comment by burisu** [comment]
No templates are designed for these exports. So it's not a bug but we miss these reports.
