### ISSUE TITLE
In stock / delivery of parcels, the list doesn't filter on transporters only

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#463]
In stock / delivery of parcels, the list doesn't appear transporters

![capture du 2015-10-29 16-05-29](https://cloud.githubusercontent.com/assets/12525665/10822329/fa41aa44-7e56-11e5-8839-83b42b893ed6.png)

**Comment by burisu** [comment]
After a look in the code and the logs, there is no filter at all. @PH64 for now, I close the issue but you can reopen it if you find a way to reproduce it.
