### ISSUE TITLE
Cannot perform work_number input during equipment creation

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#465]
NO way to add work number in equipement form view

**Comment by burisu** [comment]
Work number is for animals only ? We need to make difference between work_number and number. 2 numbers on all product form/pages are not acceptable for comprehension of all.

@ionosphere, we have 3 ways:
 1. Restores use for animals only
 2. Extend use to equipment only
 3. Merge number and work_number

Which one seems the good to you ? for me, I prefer in the order: 3, 2, 1.

**Comment by burisu** [comment]
For now, I opt for method 2, because no many changes and bug will be fixed.
