### ISSUE TITLE
Missing constant GoogleVisualr Error in placeholder cells

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#466]
A NameError occurred in placeholder_cells#show:

  uninitialized constant Backend::Cells:placeholderCellsController::GoogleVisualr
  app/controllers/backend/cells/placeholder_cells_controller.rb:5:in `show'

-------------------------------
Request:
-------------------------------

  * URL        : http://demo.ekylibre.farm/backend/cells/placeholder_cell?beehive=dashboards_settings&type=placeholder&layout=true
  * HTTP Method: GET
  * IP address : 41.138.96.169
  * Parameters : {"beehive"=>"dashboards_settings", "type"=>"placeholder", "layout"=>"true", "controller"=>"backend/cells/placeholder_cells", "action"=>"show"}

**Comment by burisu** [comment]
The placeholder cell was already removed. The error is generated by a old version.
