### ISSUE TITLE
LWGEOMCOLLECTION operation error while adding an intervention

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#468]
An ActiveRecord:tatementInvalid occurred in interventions#compute:

PG::InternalError: ERROR:  Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.
HINT:  Change argument 2: 'GEOMETRYCOLLECTION(POLYGON((7.40882456302643 48.1158768860692,7.4067968130111...'
CONTEXT:  SQL function "st_equals" statement 1
: SELECT NOT ST_Equals(ST_MakeValid(ST_GeomFromEWKT('SRID=4326;MULTIPOLYGON(((7.40679681301117 48.1167274678089,7.40882456302643 48.1158768860692,7.40882456302643 48.1158679325024,7.40678608417511 48.1167220957579,7.40679681301117 48.1167274678089)))')), ST_MakeValid(ST_GeomFromEWKT('SRID=4326;GEOMETRYCOLLECTION(POLYGON((7.40882456302643 48.1158768860692,7.40679681301117 48.1167274678089,7.40678608417511 48.1167220957579,7.40882456302643 48.1158679325024,7.40882456302643 48.1158768860692)))')))
  lib/charta/geometry.rb:252:in `select_value'

**Comment by burisu** [comment]
Although it looks like #293 the problem is located more inside `Charta::Geometry`. `ST_CollectionHomogenize` seems better in that case: http://postgis.net/docs/ST_CollectionHomogenize.html
