### ISSUE TITLE
Fullscreen dashboards should match between browsers

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#479]
Dashboards have not the same rendering on fullscreen view: See Firefox (left), Chrome (right).
![2015-11-03_15-19-12](https://cloud.githubusercontent.com/assets/9863590/10910355/4292828c-823f-11e5-8ab6-81e14116d0a9.png)

**Comment by PH64** [comment]
The problem is it still relevant ?

**Comment by Nyxelio** [comment]
Still relevant, but same dashboard is displayed. The difference is due to browser rendering and not to Ekylibre.

**Comment by Aquaj** [comment]
Could not reproduce.
Config : Ubuntu / Firefox 47.0 - Chrome 51.0.2704.106 (64-bit)

![firefox-chrome-dashboard-comparison](https://cloud.githubusercontent.com/assets/2871879/16454758/40ffe75e-3e12-11e6-85b4-67d1224b560f.png)
