### ISSUE TITLE
The unroll parameters from form are not considered

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#493]
When trying to add a new entity from an unroll name with parameters, the parameters are not considered.

= f.referenced_association :transporter, source: :transporters, **new: {transporter: 1}**

![missing_parameter](https://cloud.githubusercontent.com/assets/1838491/12512780/8162a0ea-c11a-11e5-8eef-76679147a385.png)

**Comment by burisu** [comment]
@Nyxelio All parameters should be transmitted through "new" URL to be independent of form strategy. With d275123234290df28e9cac6fd3dc467838bb6f9c, we depend on form builder and it will break on updates (because `backend/base/edit.html.haml` hasn't be changed too). Can you look at that ?
