### ISSUE TITLE
display problem when creating a product

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#499]
In intervention, when you want create a product, there's a display problem
![capture du 2016-02-24 11-59-20](https://cloud.githubusercontent.com/assets/12525665/13285128/3239fbb4-daf9-11e5-9798-4828865ac42c.png)

**Comment by burisu** [comment]
@PH64, do you still have the problem ? it seems to work here

**Comment by PH64** [comment]
@burisu it's very difficult to use the scrollbar : the combo close when you use the scrollbar

**Comment by Nyxelio** [comment]
Browsers considered click on scrollbar outside clipped content, causing focus out and closing items list
