### ISSUE TITLE
ISTEA doesn't import entries properly

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#504]
All entries imported through ISTEA General ledger are invalid : Bad test file or bad code ?

**Comment by ionosphere** [comment]
I am going to remove this exchanger because i think that we have not enough good data to make the job.

**Comment by burisu** [comment]
Close it when fixed, not before :)

**Comment by burisu** [comment]
Fixed with 1a6151393fabe4cca098b2b6fb9d8e944162bdee
