### ISSUE TITLE
Error message are not humanized

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#505]
Is it possible to have the validation error message in a human response.

Not 
```
#<ActiveModel::Errors:0x0055a818e74198 @base=#<Intervention id: nil, issue_id: nil, prescription_id: nil, procedure_name: "fertilizing", state: "undone", started_at: nil, stopped_at: nil, created_at: nil, updated_at: nil, creator_id: nil, updater_id: nil, lock_version: 0, event_id: nil, number: "2", description: "", working_duration: 0, whole_duration: 0, actions: [:fertilization], custom_fields: nil>, @messages={:"inputs.quantity_population"=>["Quantité population ne peut pas être vide"]}> 
```

But just 

"Quantité population ne peut pas être vide" in a red background like in the other view.

![screenshot at 2016-03-15 16 32 32](https://cloud.githubusercontent.com/assets/1838491/13783430/c2e5bdf6-eacb-11e5-8a08-3336358b317a.png)

**Comment by Nyxelio** [comment]
ActiveModel::Errors are only displayed on development environment
