### ISSUE TITLE
How to see a movement after updating a parcel

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#506]
When we add a quantity and update this quantity on a parcel, the product movement doesn't change anymore.

![parcel1](https://cloud.githubusercontent.com/assets/1838491/13786853/d7ee15a0-ead9-11e5-861d-b35d20dabbaf.png)

![parcel2](https://cloud.githubusercontent.com/assets/1838491/13786858/db6018e6-ead9-11e5-93ef-ae4636b8fda6.png)

**Comment by burisu** [comment]
Oooooooooooh yeaaah

**Comment by Aquaj** [comment]
Fixed by new Parcel system.
