### ISSUE TITLE
Add a way to sort status in list

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#513]
Add the ability to sort status or icon (see bellow)

![list](https://cloud.githubusercontent.com/assets/1838491/13987067/20ec5a0a-f106-11e5-9213-62a759e63af3.png)

**Comment by Aquaj** [comment]
Not possible yet due to ActiveList limitations. See comments on #769.

Maybe we should open an issue on the ActiveList repo so we can keep track of the issue once the Lexicon is done and we can get on that.
