### ISSUE TITLE
Add an attachment to incoming payments

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#523]
When an attachment (PGN format or JPG format) is add to a new incoming payment, it's impossible to save it.
![incoming_payments](https://cloud.githubusercontent.com/assets/11627573/14136488/5a6d22fc-f663-11e5-8608-cbfae80f2ddb.png)

**Comment by Nyxelio** [comment]
Only occurs on production environment.

**Comment by burisu** [comment]
Like #571 and @Nyxelio said.
