### ISSUE TITLE
Cannot add a new equipment_item_replacement intervention

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#524]
Impossible to save a new tool maintaining intervention with a piece addition.
Nothing happened after clicking on the button "create".

**Comment by Nyxelio** [comment]
#<ActiveModel::Errors:0x005574f9c771a8 @base=#<Intervention id: nil, issue_id: nil, prescription_id: nil, procedure_name: "equipment_item_replacement", state: "undone", started_at: nil, stopped_at: nil, created_at: nil, updated_at: nil, creator_id: nil, updater_id: nil, lock_version: 0, event_id: nil, number: "33", description: "", working_duration: 0, whole_duration: 0, actions: [:troubleshooting], custom_fields: nil>, @messages={:"inputs.quantity_population"=>["Quantité population ne peut pas être vide"]}>

**Comment by burisu** [comment]
The problem seems similar to #652

**Comment by PH64** [comment]
The problem seems to be resolved in v2.0 RC18
