### ISSUE TITLE
Error of calculation in the age of matter

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#529]
For a product of 02-04-2015 (we are the 31-03-2016) the age is 12 month and 4 days instead of 11 month and 27 days

![capture du 2016-03-31 10-58-00](https://cloud.githubusercontent.com/assets/12525665/14170737/7fb34506-f72f-11e5-8a31-076c91f3d8c4.png)

**Comment by burisu** [comment]
The difference comes from the duration is basically in seconds and converted in seconds, minutes, hours, days, months and years.
I'll fix `human_age` and adds `human_interval` to keep original method.
