### ISSUE TITLE
List of transporters is not displayed when creating a new delivery

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#530]
Even if there are transporters registered in entities, the drop-down list is empty in the deliveries view.
![transporters_deliveries](https://cloud.githubusercontent.com/assets/11627573/14171292/6bf9c8ac-f732-11e5-93ab-be68275d11d3.png)

**Comment by burisu** [comment]
Only "necessary" transporters are displayed. Identified transporters are clearly missing.
