### ISSUE TITLE
Can not enter an issue on a land parcel

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#531]
No way to enter an issue on a land parcel.
Maybe, it should be added a sub-menu under "analyses" in the view "productions".
![issue_landparcels](https://cloud.githubusercontent.com/assets/11627573/14172220/4869e03e-f737-11e5-9803-25662ab8c899.png)

**Comment by Aquaj** [comment]
There is a way actually, through the index of all Land Parcels : 
![issue_on_land_parcel](https://cloud.githubusercontent.com/assets/2871879/16457123/a6a725f6-3e1a-11e6-8905-50372e02d42d.png)

But I agree we need a more obvious one, esp since this one is fully dependent of the cartography.
