### ISSUE TITLE
Entry number with decimal in parcels (comma, not point)

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#536]
In parcels, decimal numbers must be entered only with comma et not point.

![capture du 2016-04-01 08-38-13](https://cloud.githubusercontent.com/assets/12525665/14199483/1dbbe89c-f7e5-11e5-9633-4bc909acc754.png)

**Comment by PH64** [comment]
The problem is from Firefox, not Ekylibre. There's no problem with Chrome

**Comment by Nicephore17** [comment]
v2.0.0rc24

On Firefox (with French settings): every screens show point but we need to use comma for floats.

![commafirefox](https://cloud.githubusercontent.com/assets/17082331/16522530/ccab538c-3f9e-11e6-99c5-76b23836d7ee.PNG)

If i use an point in Firefox (as available in the _pavé numérique_)...

![commafirefox2](https://cloud.githubusercontent.com/assets/17082331/16522667/859a61da-3f9f-11e6-8b8d-c5efb879b0dc.PNG)

On Edge (MS new browser) it is the opposite. Every screen show point and only point works (as with  _pavé numérique_) but comma is not working...

![commaedge](https://cloud.githubusercontent.com/assets/17082331/16522557/e3bfbb9e-3f9e-11e6-99a1-938d903435f8.PNG)

For info, my settings:

![commasettings](https://cloud.githubusercontent.com/assets/17082331/16522567/f0fd3a48-3f9e-11e6-9660-5eaa92f9ef62.PNG)

@ionosphere should you update locales depending of navigator ?
