### ISSUE TITLE
Word usage in worker

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#539]
In Production / Worker / New worker : "variant" sound strange. What about "catergory" or "type" instead ?

**Comment by burisu** [comment]
A _(product nature) variant_ is a _Sub-type of product_. It's used in stock management by some software. 
Example for Ekylibre:

- Product Category: Textile
- Product Nature: T-Shirt
- Product Nature Variant: Blue T-Shirt XXXL

**Comment by Nicephore17** [comment]
OK
