### ISSUE TITLE
"born at" and "dead at" labels

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#542]
Those label are use for human ressources and equipment.
I hope we don't kill worker when the leave the company ;-)

What about "arrival date" and "departure date" ?

**Comment by burisu** [comment]
`born_at` and `dead_at` are the good terms IMO. Arrivals and departures may be multiple in the professional carrier and so managed elsewhere.
`born_at` permits to store real birth date of the worker and `dead_at` can be simply ignored.

**Comment by Nicephore17** [comment]
OK for human being.
But in "Equipement"... "born at" should be either "build at" or "purchase date" ?
Also, "born at" should introduce a place instead of a date ( -> "born the").
Should I ask my english native communication consultant ?

**Comment by burisu** [comment]
I wrote previous lines only for human begins. For equipment, I'll replace it by `built_at` and `scrapped_at` which match with the meaning of that fields.

**Comment by Nicephore17** [comment]
OK. Thanks.

**Comment by Nicephore17** [comment]
Please notice that in english : 
born **at** Paris
born **on** 11/02/1976

;-)
