### ISSUE TITLE
Translation problem "planting"

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#543]
Word "planting" is not relevant for farming.
Please mind using "seeding" instead.

**Comment by burisu** [comment]
I found the both terms, but seeding won't work very well for tree growing. The term planting is form all plant kingdom.

**Comment by Nicephore17** [comment]
Sorry, misunderstanding, you can close this issue.

**Comment by Nicephore17** [comment]
Good in v2.0.0rc24
(**Plantation** for the family and **Seeding** for the intervention type)
