### ISSUE TITLE
Missing equipment

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#545]
Some equipement type are missing such as:
 - bale collector
 - telehandler
 - wheel loader

There is no irrigation equipement such as pivot or rewinders.

Is it possible to add custom equipments ?

**Comment by burisu** [comment]
Yes, you can add your own equipment with the variety `equipment` for now. 
I think all the given equipment: `telescopic_handler`, `bale_collector` and `wheel_loader` must be added to nomenclature. I'll see this

**Comment by Nicephore17** [comment]
Thanks.

**Comment by Nicephore17** [comment]
For this type of request, should I post issue in https://github.com/ekylibre/open-nomenclature.org/issues instead of here ?
