### ISSUE TITLE
Map control button error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#546]
In New Equipement / Container
When clicking on add new record / new product

There in a overlay problem with the control button of leaflet.
Zoom button are on top of the new product div.

Seen on Google Chrome and Firefox on a Mac.

**Comment by burisu** [comment]
@Nicephore17, can you add a screenshot please? I can't reproduce it with Firefox on Debian Jessie
![capture](https://cloud.githubusercontent.com/assets/240595/14226235/68eb89ec-f8dc-11e5-8814-8fbf58178839.png)
Although I found another view bug: label is added but not wanted

**Comment by Nicephore17** [comment]
![ekylibre](https://cloud.githubusercontent.com/assets/17082331/14226324/6242e42a-f8df-11e5-9742-0f8274ac1be5.jpg)

**Comment by burisu** [comment]
OK, thanks, I can see clearly now
