### ISSUE TITLE
Remove an intervention fails

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#550]
Error message when trying to remove an intervention.
![suppression _intervention](https://cloud.githubusercontent.com/assets/11627573/14208884/e70ffe0e-f821-11e5-8ec8-dcffdfbc6211.png)

**Comment by burisu** [comment]
Tried to fix that with b846dd347ffc86b4eb03c20d383526cf84e62fdf, but I'm not sure to reproduce the bug "correctly"...

**Comment by EmmaDorie** [comment]
Error persist.
![suppression_intervention](https://cloud.githubusercontent.com/assets/11627573/14489258/6a829672-016c-11e6-9c9c-92b012c9bb1c.png)

**Comment by burisu** [comment]
It's different that time:

> Can't modify frozen hash
>   [app/models/intervention_output.rb:63](https://github.com/ekylibre/ekylibre/blob/2.0.0.rc11/app/models/intervention_output.rb#L63):in `block in <class:InterventionOutput>'
>
