### ISSUE TITLE
Add a way to help the user to enter an analysis geolocation

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#560]
At creation of a new analyse, to enter the geolocation, add a solution to zoom in on map with filters like land parcels or buildings.

![analyse_geolocation](https://cloud.githubusercontent.com/assets/11627573/14251263/6b699c34-fa82-11e5-9f91-fe778abccf43.png)

**Comment by PH64** [comment]
seems to be identical to issues #688
