### ISSUE TITLE
Isacompta exchanger is not up-to-date

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#564]
Import of Isacompta files fails.
Exchanger is certainly not up-to-date.

![ekylibre-erreur-isacompta](https://cloud.githubusercontent.com/assets/11627573/14283044/bce579c4-fb41-11e5-8967-2193227c2c50.jpg)

**Comment by EmmaDorie** [comment]
The problem still persist.

Notification error :
L’import Export isacompta ‒ Isagri a échoué : undefined method `strip' for nil:NilClass

**Comment by burisu** [comment]
The file seems to be corrupted. We need to clarify error messages.

**Comment by Aquaj** [comment]
Update on this issue :
Working on our side.
@EmmaDorie has contacted the user whose file was not working to get the file that didnt work so we can debug.
Waiting on this file to start debugging.

**Comment by PH64** [comment]
@Aquaj, I put on owncloud, files from the last version to test exchanger

**Comment by Aquaj** [comment]
@PH64 : We have files to test the exchanger already, but this issue is about a specific user whom for it doesn't work - but last time they sent us their file they were corrupted by their anonymization process, so now we're waiting for them to send us a non-corrupted version.

**Comment by EmmaDorie** [comment]
@Aquaj, the exchanger doesn't work with the file of @PH64 .
I think the exchanger is not up-to-date with the last version of isacompta so the issue is the same for all users.

**Comment by Aquaj** [comment]
I thought @burisu said it was up-to-date, I'll check that out.

**Comment by burisu** [comment]
I tried @PH64's file on empty tenant and it appears e bug still remains. I'll fix what is going with this file

**Comment by burisu** [comment]
My existing test file seems very bad... I'll have to inspect why test pass with it

**Comment by burisu** [comment]
@PH64, Can I put your file to Ekylibre project as a public test file in a future commit?

**Comment by PH64** [comment]
Yes, of course, you can

**Comment by burisu** [comment]
Thank you

**Comment by EmmaDorie** [comment]
Error : 
L’import Export isacompta ‒ Isagri a échoué : uninitialized constant Isagri::Isacompta::ExportExchanger::NotWellFormedFileError

**Comment by burisu** [comment]
I close for now without no more news
