### ISSUE TITLE
Quantity of plant in matters

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#566]
It isn't possible to ento quantity of plant in "matter"

![capture du 2016-04-06 10-32-55](https://cloud.githubusercontent.com/assets/12525665/14310581/f29ea04e-fbe2-11e5-8236-690a5a4a483b.png)

**Comment by Nyxelio** [comment]
@burisu This variant has no quantity indicator, should we add one ?

**Comment by burisu** [comment]
There is no "quantity"/"population" indicator anymore. Only `initial_population` can be used to set quantity at creation.

**Comment by burisu** [comment]
Fixed with 9f8b0582d148bff48a5ee455486f121dce9d2282.
