### ISSUE TITLE
Multiplication of cultivable zones when create activities from telepac

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#570]
When cultivable zones are registered with first run and then, activities are created from Telepac, lot of new cultivable zones are created (more than double). These cultivable zones overlaps the first, created with the first run.
![multiplication_cultivable_zone](https://cloud.githubusercontent.com/assets/11627573/14319518/cfe8d842-fc11-11e5-9dde-9595c5e87994.png)

**Comment by burisu** [comment]
Sorry not a bug of Rails, maybe of your "Telepac" code
