### ISSUE TITLE
Add a column with the name of the company attached to the pacage number

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#573]
In tools/cap_statement, a column with the name of the company linked to the pacage number needs to be added.
![nom_npacage](https://cloud.githubusercontent.com/assets/11627573/14323680/ccbb0f22-fc21-11e5-8647-ee4037f90283.png)

**Comment by Aquaj** [comment]
Is the "name of the company" the farm name?

Ex: Would it be GAEC DUPONT in this Cap Statement?
![Cap statement example](https://cloud.githubusercontent.com/assets/11627573/14255230/59a1939c-fa93-11e5-818a-70bf07cefea5.png)

**Comment by PH64** [comment]
@Aquaj , Yes that's right

**Comment by Aquaj** [comment]
Added it. It seems awfully close to Declarant though.
