### ISSUE TITLE
Add a way to sort activities

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#581]
Activities should be sorted to avoid mixing SNE, maintaining and vegetal crops for example.

![tri_activites](https://cloud.githubusercontent.com/assets/11627573/14347663/8e494456-fcb8-11e5-9477-ea58d705fd8e.png)

**Comment by Nyxelio** [comment]
@EmmaDorie I split the layout into subzones. Sounds better ?
![screenshot](https://cloud.githubusercontent.com/assets/9863590/14464767/8a5742d2-00d0-11e6-804d-4d1ae7c19f88.png)

**Comment by EmmaDorie** [comment]
Add a way to hide some activities.

**Comment by burisu** [comment]
What type of activity do you want to hide ?

**Comment by Aquaj** [comment]
@EmmaDorie Do you mean like toggling the menu open/closed or do you think we should add a way to hide specific activities ? If so, what do you have in mind?

**Comment by burisu** [comment]
I think that no activities are hide-able for now. I close the issue until we have a precise idea of what is needed. @EmmaDorie, feel free to re-open this issue when you have more details to give.
