### ISSUE TITLE
Add production systems

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#583]
A new information "production_system" (organic farming, conventional farming, sustainable farming,...) should be added in open nomenclature.
This information should be attached to cultivable zones and activities.

**Comment by burisu** [comment]
French reference: https://fr.wikipedia.org/wiki/Syst%C3%A8me_de_production_agricole
No article found on english wikipedia.

**Comment by EmmaDorie** [comment]
Production systems are added in nomenclatures.
Now, this information must be attached to cultivable zones and activities.
@burisu is it possible for the millestone 2.0.0 ?

**Comment by burisu** [comment]
@EmmaDorie updated nomenclature with 39543b5d88495e6b602938dd55e95f0c21f2b18e

**Comment by ionosphere** [comment]
Already done with cb4aa112f0537216abdd4ecc47d37a8e404a05b9 in grading branch
