### ISSUE TITLE
Is it possible to merge javascripts translation data into action.yml files ?

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#584]
Translations are not related to any language (Ruby, JS...) or techno, so we must not use that to organize translations. It would be better to remove "javascripts" keys from translations.

**Comment by Nyxelio** [comment]
We can merge javascripts translations into action.yml file, but for performance issues, we should keep a dedicated root key (to avoid generate unused translations). What about 'frontend' ?
