### ISSUE TITLE
Local search bar in backend/product is not made on name

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#586]
When making a research in product natures with a key work, nothing happened.
![recherche_type_produit](https://cloud.githubusercontent.com/assets/11627573/14421204/95841e1a-ffd0-11e5-9816-d97cae130fd5.png)

**Comment by EmmaDorie** [comment]
related to #574

**Comment by EmmaDorie** [comment]
The research is making on the product nature variant but it should be on the name of the product.

**Comment by burisu** [comment]
@EmmaDorie , it's not expected by user to search product natures by product's names.
