### ISSUE TITLE
Button "New" is missing in product nature variants

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#587]
![bouton_nouveau_variant](https://cloud.githubusercontent.com/assets/11627573/14421796/d478b510-ffd3-11e5-8558-ce6b2b23626e.png)

**Comment by PH64** [comment]
If you create variant from the new button, you don't have indicator of the product type : 

- with new button :
![capture du 2016-04-12 18-21-01](https://cloud.githubusercontent.com/assets/12525665/14467503/e8199450-00db-11e6-8be4-3c20da83c2c1.png)

- from the type of product -> new variant
![capture du 2016-04-12 18-24-23](https://cloud.githubusercontent.com/assets/12525665/14467530/06ebf530-00dc-11e6-955a-0628878608d8.png)

**Comment by Nyxelio** [comment]
My mistake, so the new button in product nature variants index makes no sense.
