### ISSUE TITLE
Display of informations in setting/edit fail

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#588]
![affichage_configuration](https://cloud.githubusercontent.com/assets/11627573/14429020/e2a6b34e-fffb-11e5-9f8b-ddd58078f55f.png)

**Comment by burisu** [comment]
We need to harmonize this form with other classical forms. 
And yes, we can (and have to) remove `force_interventions_st???ed_at` preferences.

**Comment by burisu** [comment]
Since `force_interventions_st???ed_at` preferences have been removed, we will wait total setting layout refactory to manage "harmony".
