### ISSUE TITLE
Translation error Production / Analyses

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#589]
"Analyses" should be "Tests".
cf. http://www.larousse.fr/dictionnaires/anglais-francais/test/617805 point n°2

**Comment by burisu** [comment]
We found these examples on Linguee:
- http://www.linguee.fr/francais-anglais/traduction/analyse+de+terre.html
- http://www.linguee.fr/francais-anglais/search?source=auto&query=analyse+d%27eau

And according to Word Reference, "Analysis" seems to be the best word: http://www.wordreference.com/fren/analyse and http://www.wordreference.com/enfr/analysis
"Test" seems to be for biological purpose.

@Nicephore17, are you okay with that?

**Comment by Nicephore17** [comment]
OK of **Analysis**. Thanks.
Cf. Oxford dictionnary : http://www.oxforddictionaries.com/definition/english/analysis

**Comment by Nicephore17** [comment]
@burisu I still have "Analys**e**s" instead of "Analys**i**s" in 2.0rc23
