### ISSUE TITLE
French translation "Rhodes Grass"

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#595]
In french the translation "Herbe de Rhodes" is not used (except in Wikipedia).
It is better new as _Rhodes Grass_ or _Chloris gayana_ even in France.

Example in French commercial context : http://www.ics-agri.com/reclaimer-variete-performante-chloris-gayana.html
Canadian : http://www.cbif.gc.ca/acp/fra/siti/regarder?tsn=41565

**Comment by burisu** [comment]
May be we can add latin name alongside with its localized name? Moreover, name of activity can be changed as wanted.

@Nicephore17, your canadian link seems dead.

**Comment by Nicephore17** [comment]
As Rhodes Grass is almost not cultivated in France, this not very important :D

**Comment by burisu** [comment]
Perfect!
