### ISSUE TITLE
Bad label "land parcel"

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#596]
In **Settings**, **Production** : **Land pacel** label is not relevant.

_Parcel_ in english usually means _colis_ in french. It is almost not used for _parcelle_.

Best translation for _parcelle_ is _plot_.
cf. http://www.larousse.fr/dictionnaires/francais-anglais/parcelle/57727

I a _parcelle_ is a part of a _champ_, then a _plot_ is a part of a _field_.
Using _plot_ would be nice (without the word _land_)

**Comment by burisu** [comment]
The term "Land parcel" is unambiguous because we never separate "land" from "parcel". With only one meaning behind "land parcel", we think it's more clear for every one.

**Comment by Nicephore17** [comment]
OK. As long as we are testing Ekylibre I dont mind. Later on, I will check with native english speakers and custommers ;-)

**Comment by burisu** [comment]
Yes, it's good for me!
