### ISSUE TITLE
English labels in "new intervention" page are not all coherent

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#597]
In **Productions** / **Interventions** / **\+ New**

Button label are not coherent. It mixes US english and UK english, noons and verbs etc.
Please, finde below, a harmonization suggestion:

Animal faming -> **Lifestock farming** or **Breeding**
Installation modification -> **Facilities modification**
Fertilizing -> **Fertilization**
Harvesting -> **Harvest**
Soil working -> **Soil preparation**
Energy supplying -> **Power supply**

**Comment by Nicephore17** [comment]
An addition:
**Sowing **(under **Planting**) is not mainstream. Please use **Seeding **instead.

**Comment by burisu** [comment]
Yes, **sowing** have to be renamed, IMO. @EmmaDorie, @ionosphere, @PH64, @byneoseb, what do you think of these suggestions?

**Comment by Nicephore17** [comment]
Largely updated in v2.0.0rc24

Still to consider for next revisions:
Harvesting -> **Harvest**
Energy supplying -> **Power supply**

Animal treating sounds bad. **Animal care** ?
What about changing Habitat maintenance to **Housing maintenance** ?
Why do we have 2 facilities management: in Animal farming and Tool maintaining.

Families can be change as well:
- Animal farming -> **Lifestock farming** or **Breeding**
- Processing -> **Transformation**
- Tool maintaining -> **Tool maintenance** or **Hardware maintenance**
