### ISSUE TITLE
Sowing interventions needs doers

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#598]
In **Production** / **Intervention** / **+New** / **Plantation** / **Seeding**.
We need to add worker in addition with the drive.
In large scale farm we need at least 1 or 2 worker for seed supplying and seeder check (to avoid jams).

**Comment by burisu** [comment]
@EmmaDorie, can you look at that?

**Comment by Nicephore17** [comment]
What about adding a **doer** entry in the seeding template (like in harvesting intervention) ?
