### ISSUE TITLE
Labels in Sowing intervention

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#599]
When creating a sowing intervention.
In Cultivation list, the word crop is useless.

Ex. Apple, Arezzo wheat, Asparagus, Bean etc. instead of Apple crop, Arezzo wheat crop, Asparagus crop, Bean crop and so on.

![crop](https://cloud.githubusercontent.com/assets/17082331/14529425/d1b97b38-0254-11e6-955d-f352e1227e8f.PNG)

**Comment by burisu** [comment]
As far as we ask for a cultivation type (and not a species/variety), the words "crop", "orchards" or equivalent will be kept in this labels.

**Comment by Nicephore17** [comment]
OK
