### ISSUE TITLE
Missing operation in production/operation/harvesting

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#608]
Sometime we don't have a **windrower** so we fist **mow** and then **rake**.
Can we add **rake** to the list ?

**Comment by EmmaDorie** [comment]
It's a translation issue.
We had to enhance this.

**Comment by PH64** [comment]
The issue seems to be solved in V2.0 RC20

**Comment by Nicephore17** [comment]
Yes. It's OK.
