### ISSUE TITLE
Bad EN translation in Production/Interventions/Harvesting

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#609]
**Straw bunching** (for _pressage de fourage_) don't make sense.
If its purpose is to make some hay bales, the actions should be **baling**.

cf. http://starlingagriculture.com/products/baling

**Comment by burisu** [comment]
_Straw bunching_ aims to be a generic expression. Baling seems to be more comprehensive when I take a look on Linguee. @ionosphere, @EmmaDorie , do you validate ?

**Comment by Nicephore17** [comment]
Not corrected in 2.0rc23 (in "farmplus" instance).
@EmmaDorie can you check ?
