### ISSUE TITLE
scope don't work on refers_to nomenclature

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#612]
When we try to filter some nomenclature item using refers_to in a model, nothing appends.

in my model

``` ruby
refers_to :size_indicator, -> { where(datatype: :measure) }, class_name: 'Indicator'
```

in my view, the list is not great as expected

![screenshot at 2016-04-26 23 02 22](https://cloud.githubusercontent.com/assets/1838491/14834121/0ad64b1e-0c03-11e6-8337-2f76a2c44e5f.png)

**Comment by burisu** [comment]
Scope is not a base functionality of `refers_to`
