### ISSUE TITLE
Campaign deletion error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#615]
Hello, I have destroyed some "compaign" but they are still available in **Production / Campaign / Open**.
How to get rid of them ?

**Comment by EmmaDorie** [comment]
Hello, it's impossible to destroy a campaign. A campaign is just a year.
Do yo mean that you want to destroy an activity in a campaign ?

**Comment by Nicephore17** [comment]
Not very sure. I don't understant the meaning of "Campaigns" specially with aflafa (1 seeding for up to 20 harverst during 2 years). Maiby I sould not use Campaigns at all...?

**Comment by EmmaDorie** [comment]
With the last rc, activities can be closed in a campaign when you click on "manage activities".
Is it Ok for you ?
Can we close it ?

**Comment by Nicephore17** [comment]
Yes, it's OK for me @EmmaDorie
