### ISSUE TITLE
Sort missing in new products

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#616]
When creating a new product type.
**Frozen indicators list** and **variable indicators list** should be sorted alphabetical of ease of use.

**Comment by Aquaj** [comment]
Hi @Nicephore17 : it appears sorted on my side, but maybe this is just a system/browser thing or even just a random happenstance.
Is this issue still relevant on your side or has it been fixed and just needs to be closed?

**Comment by Nicephore17** [comment]
Hi, actually we talked with @EmmaDorie.

Actually it is shorted from left to right and top to bottom like this:

`A B C`
`D E F`
`G H I`
`J K L`
`M N O`
`P Q R`

As the listing is **very long** and only few columns wide (depending of used display), I would be more user friendly to short from top to bottom and left to right like this:

`A G M`
`B H N`
`C I O`
`D J P`
`E K Q`
`F L R`

For this reason, the first time I used it I didn't feel like it was shorted ;-)

**Comment by Aquaj** [comment]
Thanks! 
It is indeed sorted that way. I'll look into that column-ordering idea, it might be worth a try !

**Comment by Aquaj** [comment]
So, we gave it a try - on the technical side it's surprisingly complex, putting it aside for now, we'll  maybe consider it back later on when CSS specs have more adequate tools.

Closing for now.

**Comment by Nicephore17** [comment]
OK. Nevermind.
