### ISSUE TITLE
The term "campaigns" is not very understandable in productions menu

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#618]
In productions menu, the term "campaigns" is not well adapted because this menu is use for manage activities by campaign.
It should be renamed "activities".

**Comment by Nicephore17** [comment]
Specially withou help files :-(

**Comment by Aquaj** [comment]
Activities is also the name of the menu group, I'm not sure calling that menu item Activities would be a great idea. 
I was going to suggest "current campaign" but I realized it's not only the current campaign that's available through that view.
Maybe "Assign to campaign" ? "Manage" ?

**Comment by Nicephore17** [comment]
Activit**ies** and Activit**y** ?
Campaigns could be Activities and gather several Activity ?

**Comment by Aquaj** [comment]
Oh yes actually the menu group is called Activit*y* not Activit*ies*, I still think that would be confusing to have "Activity > Activities".

**Comment by EmmaDorie** [comment]
@Aquaj 
A proposition had already been made in a monday board, we have to validate it again with @burisu .

**Comment by Aquaj** [comment]
Oh alright! :+1:

**Comment by EmmaDorie** [comment]
Proposition writing in issue #978
