### ISSUE TITLE
Backup solution

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#619]
Hello,

As Ekylibre is an Open Software that insure that all datas remains the property of its user, do you plan a backup solution ?

Every user should be able to downlod a local backup (such a .zip or .tar.ge file with SQL extraction an files).

Thanks you

**Comment by burisu** [comment]
Yes, you can get a backup of your data with one command:
```
rake tenant:dump TENANT=my-sweet-farm
```
It builds a zip file into `tmp/archives` directory of your ekylibre path.

**Comment by Nicephore17** [comment]
I was writing about the SaaS edition ;-)

**Comment by burisu** [comment]
It's a matter of time to get the feature on the SaaS, it will be done for autumn 2016.
