### ISSUE TITLE
Duplication of the field "work number" in the form "edit equipment"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#620]
The field `work_number` is duplicate in this form.
The first field doesn't work, only the field in `identification` works.
![work_number_equipment](https://cloud.githubusercontent.com/assets/11627573/15108924/074919e2-15d9-11e6-8c91-6288ebad4da4.png)

**Comment by burisu** [comment]
The `initial_geolocation` and the reading `geolocation` are in the same page and its not really good too
