### ISSUE TITLE
"Storage" and "sender" required but not labeled as required

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#622]
![capture d ecran_2016-05-09_21-38-38](https://cloud.githubusercontent.com/assets/8056027/15126098/ade49c2a-1630-11e6-935c-bab604eb72f9.png)

While making a new parcel, these two fields are not labeled as required with a red " * "

**Comment by Nyxelio** [comment]
Good observation, we'll get it on v3

**Comment by Aquaj** [comment]
Fixed by ec41598 (+ 3693808) on Parcel rework branch.

**Comment by Aquaj** [comment]
Closing since Parcel rework branch has been merged.
