### ISSUE TITLE
Question : relation type

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#624]
Hi,

In relation, when adding a contact in **relationship** we can choose between **Active**, **Prospect**, **Client**, **Supplier** or **Transporter**.

When the contact is a part of the team, what should we use ?

Is it relevant to add a **team** field ?

**Comment by Nicephore17** [comment]
Actually, we can record staff in Setting / Production / Workers but is supposed to be linked with a person from **relationship**.

If so, is it mandatory to fill un 2 time the name fied (in relationship and in worker) ?

**Comment by EmmaDorie** [comment]
@Nicephore17 is it OK for you after our email discussions ?
Can we close this issue ?

**Comment by Nicephore17** [comment]
Yes @EmmaDorie
