### ISSUE TITLE
Bug importing workers

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#627]
Impossible to import workers with **Tools / Import / Ekylibre workers**

Error message : _Import Ekylibre workers failed: Validations failed: Full name can't be blank, Last name can't be blank_

Same error when trying with demo file : https://github.com/ekylibre/first_run-demo/blob/master/alamano/workers.csv

**Comment by Nicephore17** [comment]
Maybe a right problem...

**Comment by burisu** [comment]
I test the import of that file type with: https://github.com/ekylibre/ekylibre/blob/master/test/fixture-files/imports/ekylibre_workers.csv without bugs. I don't how you get that

**Comment by EmmaDorie** [comment]
It was a problem of comma-separator, link to the csv format.
