### ISSUE TITLE
No way to confirm user after sign_up

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#631]
I don't know how to confirm a user who sign up in an instance of Ekylibre ?
I suppose there no action for this, for the moment ?

![screenshot at 2016-05-11 11 15 07](https://cloud.githubusercontent.com/assets/1838491/15176066/a4b5d7ba-1769-11e6-9a23-fa3d9d97c127.png)

**Comment by burisu** [comment]
No, all is here, go to "Inscriptions" to see registrations.

**Comment by ionosphere** [comment]
OK. We have to update the form 'Inscriptions' in order to confirm user ?
