### ISSUE TITLE
Wrong journal entry items currency in bank statement point

### ISSUE THREAD

**Issue by lcoq** [ekylibre/ekylibre#634]
The journal entry items displayed in the bank statement point are in a wrong currency:

* The currency displayed is the [`Preference[:currency]`](https://github.com/ekylibre/ekylibre/blob/master/app/helpers/application_helper.rb#L80-L83)
* The value is in the `journal_entry_item.journal_entry.currency` ([`journal_item.debit`, `journal_item.credit`](https://github.com/ekylibre/ekylibre/blob/master/app/views/backend/bank_statements/point.html.haml#L63-L64))

**Comment by Aquaj** [comment]
Not relevant since the bank statement rework.
