### ISSUE TITLE
Crash on export Interventions

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#641]
In **Tool/Export**
"We're sorry, but something went wrong" error when trying to export **Intervention register**

**Comment by Nicephore17** [comment]
Same problem with rc16

**Comment by Nyxelio** [comment]
This occurs when no mail address is supplied for your company. Could you check if an address exists for your account, in Relationship > entities ?

**Comment by Nicephore17** [comment]
Same problem, sorry.
