### ISSUE TITLE
Function resquest - Adding intervention/issue button

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#645]
In **production / campaign** when selection campaign.

Normal behaviour for adding an activity is to choose **production** and the add intervention.

Will it be possible to add intervention directly from map ?

@clegris

**Comment by EmmaDorie** [comment]
When you click on a land parcel on the map of production dashboard, you can choose intervention.
Similary, you can do it from de map in plant menu.

Is it what you want @Nicephore17 ?

**Comment by Nicephore17** [comment]
Yes, it could be nice to have the same intervention and issue from every maps in production dashboard (including in production/campaign) ortherwise user have to _learn_ where is the quick access.

**Comment by Nicephore17** [comment]
In **Production Dashboard**

<img width="370" alt="actioninproductiondashboard" src="https://cloud.githubusercontent.com/assets/17082331/15389050/3814a436-1db5-11e6-89da-5058b76452be.png">

In **Production Dashboard / Campaign**

<img width="370" alt="actionsincampaign" src="https://cloud.githubusercontent.com/assets/17082331/15389061/4cb27d8c-1db5-11e6-9eea-812a0cc04fd7.png">

In **Production Dashboard / Cutivable zones**

<img width="201" alt="actionincultivablezones" src="https://cloud.githubusercontent.com/assets/17082331/15389074/603ae07e-1db5-11e6-8a9a-bd3ff7a2fce0.png">

In **Production Dashboard / Plant**

<img width="296" alt="actionsinplant" src="https://cloud.githubusercontent.com/assets/17082331/15389087/6dd6aefc-1db5-11e6-9a6c-a292147fb3b2.png">

**Comment by EmmaDorie** [comment]
We can't standardize it like your post because interventions and issues are not registered everywhere. For example, an intervention is registered on a land parcel or on a plant, but not on a cultivable zone.
So, it will be inconsistent if we add the "intervention" button on the cultivable zone map.

**Comment by Nicephore17** [comment]
@EmmaDorie I agree but we may consider adding the Intervention in **campaign** as campaign shows actual crop/plant ? Also, what about adding Issue for both **campaign** and **production dashboard** ?

**Comment by Nicephore17** [comment]
Nota is there a real difference between **Production dashboard** and **Production dashboard / Campaign** ?

**Comment by EmmaDorie** [comment]
I'm not sure for **campaign** in the 2 firsts points. 
@burisu what is your opinion ?

However, issues can't be registered on a cultivable zone. In your example, "stone detected" is on the land parcels.

**Comment by PH64** [comment]
I don't know opinion of @burisu but for me, the Production dashboard represents visualization of interventions (time, number of tools, yield...and entry of intervention) while Production dashboard/campaign represents only one crop and its features (and modifications). the objective of the dashboard are different.
Even if it's possible in campaign/activity, the entry of interventions should be made in production/intervention

**Comment by PH64** [comment]
see #707
