### ISSUE TITLE
Function resquest : price conversion in catalog

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#646]
When setting a catalog price from intervention panel : is it possible to add currency ?
Ex : farm accounting in € but salary in SDG (Sudanese pounds).

![operatorprice](https://cloud.githubusercontent.com/assets/17082331/15316545/cd959d56-1c1d-11e6-8658-66623291c533.PNG)

**Comment by EmmaDorie** [comment]
@ionosphere what do you think about it ?

**Comment by burisu** [comment]
Currency is configurable at catalog level. All items of a catalog are in the same currency. You can find currency here: https://demo.ekylibre.farm/backend/catalogs/new

Although this, we need to add currency symbol near amount to clarify that for users.

**Comment by Aquaj** [comment]
Everything seems to have been resolved here. 
The need for a currency symbol @burisu noted has already been reported in #621 so I'm closing this for now.
