### ISSUE TITLE
Intervention problem with Windrower

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#648]
We use windrowers to harvest Rhodes Grass (as for Alfalfa). The windrower is a all-in-one unit that mow hay.

Cf. http://www.macdon.com/products/category/self-propelled-windrowers-and-headers

As windrowers are not avaiblale in Ekylibre, we define it as a **Reaper** product variant.

Problem : when adding **Harversting/Plan mowing** intervention, selecting a tractor is mandatory.
As we don't use tractor but only the windrower, what should we do ?

**Comment by EmmaDorie** [comment]
@ionosphere we had to set up a solution to manage automotive equipments in lot of interventions

**Comment by PH64** [comment]
@EmmaDorie, As spaying intervention, it shouldn't be required to enter a tractor in all harvest interventions

**Comment by PH64** [comment]
I think it's OK and it can be closed. Are you agree ?

**Comment by Nicephore17** [comment]
I check...
