### ISSUE TITLE
Irrigation activities shows both cultivation and production

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#654]
When adding irrigation activities, **cultivation** field shows both campaign cultivations (ex. _Pivot 7 Rhodes Grass 2015_) and productions (ex. _RG_P07_2015_).

![irrigation_cultivation](https://cloud.githubusercontent.com/assets/17082331/15349940/934ea1ec-1cd6-11e6-84db-53cb0de68eed.png)

**Comment by EmmaDorie** [comment]
@ionosphere Is there a reason that we can choose between plant or land parcel in an irrigation intervention ?

**Comment by Nicephore17** [comment]
If irrigation targets a crop, it will be easier to computer total cost of a production including water price.

**Warning:** in some crops (thanks to the arid zones), we irrigate before seeding so it will be difficult to set the good target as cultivation target is only available after seeding intervention.
