### ISSUE TITLE
All crops have yields grain even if they do not produce grain

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#655]
Rhodes Grass produce hay, not grain.
Should be corrected in **activity** map.

![grainproduction](https://cloud.githubusercontent.com/assets/17082331/15350004/f3760baa-1cd6-11e6-91a3-7b5c79c700ad.PNG)

**Comment by Nicephore17** [comment]
Same in rc16

**Comment by PH64** [comment]
The problem is the same with all crops which don't produce grain : potatoes, vine, beet, meadow

**Comment by Nicephore17** [comment]
Same in rc24.

What about connect this information with **production's usage** 

![productionusage](https://cloud.githubusercontent.com/assets/17082331/16112170/7931a042-33b6-11e6-97f7-01735be3a754.PNG)

- Grain Yield for **Grain**,
- Hay production for **Fodder** (or Fodder production as well),
- Liter for **Milk**..

**Comment by Nicephore17** [comment]
in v2.0.0rc25

Fodder yield do not pop for fodder production.
@PH64 @ionosphere 

![fodderyield](https://cloud.githubusercontent.com/assets/17082331/16552134/c6ce9858-41be-11e6-8857-92e29ccb7d56.PNG)
