### ISSUE TITLE
Traduction error in production dashboard

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#660]
**Plants** (under **Land parcel**) do not make sense.

English word **plants** means _plantes_, _installations_ or _usines_ in french.
For _cultures_ you should use **crops**.

**Comment by Nicephore17** [comment]
@Aquaj, your commit had no effect in v2.0.0rc23 and v2.0.0rc24

![engplant](https://cloud.githubusercontent.com/assets/17082331/16110568/b0a477c8-33ae-11e6-84e1-6aa796baa6bf.PNG)
**(Production dashboard)**

**Comment by Aquaj** [comment]
Indeed, it was not the Plants on the Production Dashboard that I had corrected. Fixing this as we speak.

**Comment by Nicephore17** [comment]
Working well in 2.0.1 since long ;-)
