### ISSUE TITLE
Map error on new issue page

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#661]
See below missing image in the middle of the map: 
Similar with https://github.com/ekylibre/ekylibre/issues/653 ?

![newissue](https://cloud.githubusercontent.com/assets/17082331/15392931/834b5714-1dca-11e6-867d-8aea902fdf99.PNG)

**Comment by Nyxelio** [comment]
Fixed by 6db4df7d0b8ea90c30091101e6020ac19e5aa8fe

**Comment by PH64** [comment]
The problem is reappeared in v2.0.0 RC20
