### ISSUE TITLE
No currency symbol return in sale or purchase report

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#662]
When trying to have the currency in report, the symbol is blank.

in /sale/1.xml

```xml
<currency name="EUR">  </currency>
```
in the past version, we have

```xml
<currency name="EUR">€</currency>
```

**Comment by burisu** [comment]
Not fully exact, in the past version, we have:
```xml
<currency name="EUR">EUR</currency>
```
The difference comes from use of Enumerize through added `refers_to` in models. So bugfix will make return:
```xml
<currency name="EUR">Euro</currency>
```
