### ISSUE TITLE
Unit not showing when adding new ParcelItem - Parcel creation

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#664]
While making a new parcel and adding an element to it, its unity is not imediately visible
![issue parcel](https://cloud.githubusercontent.com/assets/8056027/15483066/25d8cf00-2133-11e6-96b8-5d2b05f94653.png)

**Comment by ionosphere** [comment]
Hi,

What kind of variant do you use ?

**Comment by AlexisLeC** [comment]
Hi,

in that case that was from variant Bonanza that derived from type "Semence" (Seeds ?)
In my opinion that a minor issue of dynamicity as the unity is displayed when I want to modify the Parcel

**Comment by PH64** [comment]
Hi,
As @AlexisLeC, I have the same issues with every type of variant, only when I create a parcel. In modification of the parcel, the unity is displayed.

**Comment by Nyxelio** [comment]
Seems resolved ?

**Comment by PH64** [comment]
In rc22, problem seems not solved in creation of parcel

**Comment by Nyxelio** [comment]
Unity is displayed for me...
![screenshot](https://cloud.githubusercontent.com/assets/9863590/15716182/92ad76b8-2821-11e6-963c-0070410b3862.png)

**Comment by PH64** [comment]
@Nyxelio, I have the same screen as you in modification, and the same screen as @AlexisLeC in creation. 
@Nyxelio, is it solved for you ?

**Comment by Nyxelio** [comment]
Oh ok, it works locally but not on demo due to a bad request. I'm investigating.

**Comment by AlexisLeC** [comment]
@Nyxelio It still doesn't work with my current version RC23

**Comment by Nyxelio** [comment]
It will be fixed soon by a new parcel mechanism.
