### ISSUE TITLE
Add filter on land parcel/cultivation field in production/new intervention

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#666]
In production/new intervention, all the land parcels or cultivations (depend on intervention) are displayed in the list.
A filter should be add to display only those of the campaign chosen before.

**Comment by EmmaDorie** [comment]
After the discussion with @PH64, better filter should be the end of the production.
After the date of the end of a production, land parcels and crops related to this production must be considered as finished.
At creation of a new intervention, only "active" land parcels and crops at the date of the intervention have to be displayed.

**Comment by EmmaDorie** [comment]
Validated with @ionosphere : There are 2 additions to do for plants.
1) In the form of edition of a plant, add the possibility to registered the "death date" of the plant
2) Add the possibility to "kill" a plant after an intervention

Then, at creation of a new intervention, the date of intervention have to be pass in parameter in the scope of the filter of the product. Only the active plants at the date of intervention have to be displayed.

**Comment by Aquaj** [comment]
Partially resolved : Scope Product.alive_at(date) now exists (and plants have a dead_at field in their edit form).

The possibility to "kill a plant" through an intervention needs the add of a new column in the Interventions table so it'll have to wait for the 2.0.0 release.

**Comment by EmmaDorie** [comment]
The filter works when selecting the first land parcel or plant in a new intervention, but if an other is added in the same intervention, the filter doesn't work any more.

**Comment by EmmaDorie** [comment]
Issue separated between #982 and #983.
