### ISSUE TITLE
Equipment choice with combine harvester

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#673]
In **Intervention / Harvesting / Mechanical Harvesting** it is not possible to choose an equipment for the combine harvester.

Ex. When you farm both corn and wheat you can use the same combine harvester but with a different header. How can we define this in the software.

Please consider adding headers as accessories for combine harvester.

**Comment by PH64** [comment]
You can create new variants for corn heads, grain table or other pick-up from Product type "combine", and create new equipment for this heads which can be used in intervention.

**Comment by Nicephore17** [comment]
When I choose **Harvesting / Mechanical Harvesting** I can only select a cropper.
If I use a generic Combine, I have no field to select the appropriate head.
Should I use **Harvesting / Harvesting** instead ?

**Comment by PH64** [comment]
In cropper, you choose your combine and and your head.
![capture du 2016-05-26 15-48-39](https://cloud.githubusercontent.com/assets/12525665/15576718/73ccb640-2359-11e6-92d5-5e87f9932a0e.png)

**Comment by Nicephore17** [comment]
OK then. It was almost obvious :dancer:

**Comment by Nicephore17** [comment]
I have no "Combine" product type...

**Comment by EmmaDorie** [comment]
I think the name of "combine" in product type is "reaper" in your instance.

I change the translation in nomenclature few days ago but it don't change for you because the name was already load in your instance.

**Comment by Nicephore17** [comment]
Yep, thanks. I gonna update to "combine".

**Comment by EmmaDorie** [comment]
Just a precision, in the corrections that you sent, the new translation is "combine harvester".

**Comment by Nicephore17** [comment]
OK
