### ISSUE TITLE
"Mechanical harvesting" traduction

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#674]
In **Production / Intervention / Harvesting / Mechanical harvesting**.
_Combine harvesting_ might be clearer the _Mechanical harvesting_.

**Comment by burisu** [comment]
Yes, it seems we planned this, it will be OK soon

**Comment by Nicephore17** [comment]
Thanks.

**Comment by Nicephore17** [comment]
Same in v2.0.0rc24

**Comment by Aquaj** [comment]
c0158a8 merged Mechanical Harvesting with Harvesting.
No need for new translation anymore.
