### ISSUE TITLE
Bad time counting in Campaign

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#678]
My campaign 2016 don't show the sum of all my activities....

![interventioncount01](https://cloud.githubusercontent.com/assets/17082331/15571209/d77de850-2339-11e6-95c1-0f7dac999c9e.PNG)

![interventioncount02](https://cloud.githubusercontent.com/assets/17082331/15571208/d77c4c0c-2339-11e6-986b-8f8bf6f9145a.PNG)

**Comment by PH64** [comment]
Hi,
In your first screen, there are 2 strange things : the Rhodes grass area = 0 and the time work.
In your campaign 2016, could you verify that you have fields in your Rhodes grass 2016 production.
And could you post a large screen of you intervention (like your 2nd screen but with the field's name).

thanks in advance

**Comment by Nicephore17** [comment]
Actually, the crops are seeded in 2015 so they are started on campaign 2015. The seeding was on 2015 and the time used and covered area is recorded correctly for 2015. The harvest was done in 2016 but it is not counted on 2016 campaign nor in 2015. What should be the normal behaviour ?

**Comment by PH64** [comment]
I'm not very sure because I don't know Rhode grass crop, but I suppose you have seeded in 2015 and you harvest in 2015, 2016, 2017... 
If it's right in campaign 2015, edit Activity Rhode Grass and mark "Production cycle" as "Perennial" and "Production campaign" as "At cycle start". 
It should work. 
Keep me informed

**Comment by Nicephore17** [comment]
Rhodes Grass (on arid irrigated zones): 1 seeding, up to 18 harvest in the 2 years following the seeding.
I updated as follow and closed the 2016 campaign but it did not update the labour time...

![rhodescampaign](https://cloud.githubusercontent.com/assets/17082331/15577742/18752ae8-235e-11e6-8a2f-ee563d036938.PNG)

**Comment by Nicephore17** [comment]
Even if we solve my problem. I think it shloud be reported as a bug: a pluriannual campaign sould be available for each year between the defined start and end date. ;-)

**Comment by Nicephore17** [comment]
https://github.com/ekylibre/ekylibre/issues/684
