### ISSUE TITLE
Missing translation in Production / Plants

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#681]
On the map, missing eng.labels.watering_concentration as below:

![missingtranslationplants](https://cloud.githubusercontent.com/assets/17082331/15578530/1879c3ca-2361-11e6-836b-a2b532437e08.PNG)

**Comment by Nicephore17** [comment]
Why is everythin empty ? Cf. after some updates data updates:

![plants](https://cloud.githubusercontent.com/assets/17082331/15650958/9d4527a2-267c-11e6-8a13-6d0d03e76ebb.PNG)

**Comment by EmmaDorie** [comment]
What do you mean with "everything" is empty ?
Is the problem the display of colors ?

**Comment by Nicephore17** [comment]
All white, nothing "ready to harvest".
Also, where does the density should come from?

**Comment by EmmaDorie** [comment]
You can change the layers displayed if you click on the top right button.
For the moment, the layer "watering concentration" hide the others, and all is white because you don't have irrigation interventions.
If you uncheck this layer, the variety layer will appear.

**Comment by Nicephore17** [comment]
OK, then. I get it. What is the **ready to harvest** and **plantation density**?

**Comment by EmmaDorie** [comment]
There are indicators which are filled in a plant_analysis

**Comment by Nicephore17** [comment]
OK for all this but not user friendly see : https://github.com/ekylibre/ekylibre/issues/690

**Comment by Nicephore17** [comment]
OK in 2.0rc22
