### ISSUE TITLE
rc21 purchase error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#683]
"The page you were looking for doesn't exist"
on page https://farmplus.ekylibre.farm/backend/purchases

**Comment by PH64** [comment]
An ActionView::Template::Error occurred in purchases#index:

  Couldn't find User without an ID
  app/views/backend/purchases/index.html.haml:10:in `block (2 levels) in _app_views_backend_purchases_index_html_haml___1111498404567799268_69912083810060'
