### ISSUE TITLE
Perennial campaign bug

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#684]
When opening a new activity in a perennial campaign on year Y...

User is asked to define a period.
When choosing a **end** date for the period, _Y + 2 for example_, the production will not pop in Y+1; Y+2 campaign and so on.

@burisu, is it clear ? Need screenshots ?

**Comment by Nyxelio** [comment]
Still relevant ? My perenial production seems to appear in the right period.

**Comment by Nicephore17** [comment]
I did not test since then...

**Comment by PH64** [comment]
Yes it works

**Comment by Nyxelio** [comment]
Thanks @PH64
