### ISSUE TITLE
Inventory problem

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#691]
When **matter** have no **container**, they don't show up in **inventory**.
Also, it is not possible to correct container for the matters...

**Comment by PH64** [comment]
see also issues #623 and #514

**Comment by Nyxelio** [comment]
Matter with no container appears in "undefined container" section.
But matter has to have its initial owner set to be shown in inventory.

**Comment by Nicephore17** [comment]
Any way to setup default owner ?
As well, who is the owner of a matter produced by an Intervention (such hay bales) ?

**Comment by Nyxelio** [comment]
Your matter should be linked to your organization.
