### ISSUE TITLE
Intervention "facilities modifications" is wrong

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#698]
The procedure "facilities modifications" is not generic but it correspond to the procedure "standard_enclosing".
This procedure have to be renamed and other procedures with in category "facilities modifications" should be add.

**Comment by Aquaj** [comment]
After discussion with @EmmaDorie :
The problem appears to be that "standard_enclosing" is the only procedure in its category, therefore it is selected when Facilities modification is clicked - which might be confusing to the user.
A solution would be to make it a list even though there'd only be one entry in it.
Another solution would be to add another procedure to the category so we'd have 2+ and therefore a menu would appear.

**Comment by burisu** [comment]
Best solution is to add a new valid procedure to this category. @EmmaDorie, can you write a simple one of this category?
