### ISSUE TITLE
Fertirrigation

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#700]
How do you handle fertirrigation ?
Is it possible to have a simple way to **add fertilizer** in irrigation Intervention as we have **add water** ?

As well il se "spreader" (in irrigation intervention) mandatory ?
When using pivot for irrigation, the irrigation system always stay in the same field how to connect both of them ?

**Comment by PH64** [comment]
Fertirrigation need a specific intervention, like irrigation with water and fertilisant

**Comment by Nicephore17** [comment]
All right, I hope adding fetilizer to irragation will be available soon :D

**Comment by ionosphere** [comment]
I think that we could add optionnal fertilizer as input during this intervention.

**Comment by Nicephore17** [comment]
Working well since last update
