### ISSUE TITLE
Cannot find water variety

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#702]
Water is a variety used for irrigation but it's missing in **Settings / Product categories**.

I **variety** and **product categories** differents items ?

**Comment by PH64** [comment]
Water (irrigation) is present in setting/ product categories, product types and variants.

![capture du 2016-06-02 10-21-47](https://cloud.githubusercontent.com/assets/12525665/15738616/670db15e-28ac-11e6-85ac-3841c77bde73.png)

**Comment by Nicephore17** [comment]
This is what I have in Product Type:

![producttype](https://cloud.githubusercontent.com/assets/17082331/15738746/fc815506-28ac-11e6-8afb-2e902c7db53b.PNG)

But, in stock it is related to **Water** not **Irrigation water**.

![instock](https://cloud.githubusercontent.com/assets/17082331/15738768/1e345f9a-28ad-11e6-8f48-a9849f9d2aa2.PNG)

As well, where do I track the nitrogen input ?
