### ISSUE TITLE
Quick acces to "issue" button

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#707]
Could you consider adding a **Issue** button in **Production** instead (on in addition with) the on in **Tools** ? It shloud be more convenient.

@clegris

**Comment by EmmaDorie** [comment]
Production menu is expected to be changed in the next weeks.
The button will be moved at the same time.

**Comment by Nicephore17** [comment]
Wonderfull \o/

**Comment by Nicephore17** [comment]
Same in v2.0.0rc24. Waiting for next production menu revision ;-)
