### ISSUE TITLE
On cultivable zones, when we toggle between map and list views, map backgrounds disappear

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#708]
![capture-default zones cultivables - mozilla firefox](https://cloud.githubusercontent.com/assets/240595/15805439/c886ea4c-2b2a-11e6-93c6-73128cbc88c7.png)

**Comment by Nyxelio** [comment]
Fixed by c504ba1f57627558dae4efb79cbcf926ac30f6ff
