### ISSUE TITLE
Intervention list is missing in activities

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#714]
v2.0.0rc23

In **Production / Campaign** 
When I click on a **Campaign** and open a specific **Production** I am supposed to have a list of **interventions** at the bottom of the page.

This list is always empty.
Connectig intervention to activity should be very intersting but if it is not working now you may consider hyding the **Interventions** bloc

![interventionsinactivity](https://cloud.githubusercontent.com/assets/17082331/15822416/ef0f38f6-2bf5-11e6-84bf-d8b500df0d4f.PNG)

https://farmplus.ekylibre.farm/backend/activity_productions/56

**Comment by EmmaDorie** [comment]
Duplicate with #528

**Comment by Nicephore17** [comment]
OK ;)
