### ISSUE TITLE
First-run : Arable Area - loading files

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#715]
v 2.0.0rc23

For my farm with 27 fields I get following problems (all files exported from QGIS with every file including whole farm):
- Importing from KML: freeze (KML checked on Google Earth, all fine)
- Importing from GML: freeze
- Importing for GeoJSON: create unwanted land parcel (more than 180!) on wrong place.

Only working solution: make on KML file per field and upload one by one.

Note: "liwa" Instance

**Comment by Nicephore17** [comment]
Nota : I can mail you my KML, GML and GeoJSON files if needed ;)

**Comment by Nyxelio** [comment]
@Nicephore17 , i really appreciate if you can mail me your files

**Comment by Nicephore17** [comment]
I don't have tour mail adresse. Can I send them to @EmmaDorie ?

**Comment by Nicephore17** [comment]
Sent !

**Comment by Nyxelio** [comment]
- [x] Geojson: Use specified CRS, if any
- [x] KML: Import multiple geometries
- [ ] GML:  Use specified CRS + Import multiple geometries

**Comment by Nicephore17** [comment]
So, it was supposed ti work with my GeoJSON and KML but not with the GML because of CRS ?

**Comment by Nyxelio** [comment]
It will on the next release.

**Comment by Nicephore17** [comment]
OK. Mind adding a help page or inline precisions ;)

**Comment by Nyxelio** [comment]
It works on first-run. 8ae133ac8453e6368aab4ddf39ecf67a87e5f67f

**Comment by Nicephore17** [comment]
Good luck @Nyxelio !

**Comment by Nicephore17** [comment]
Should I try ?
