### ISSUE TITLE
First-run : map enhanchment

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#717]
For the first run, please consider adding a full screen option for the maps in order to draw easily area (land parcel, buildings etc.).

**Comment by Nyxelio** [comment]
Maps on first run already have a fullscreen button, it doesn't work for you ?

**Comment by Nicephore17** [comment]
It is back. I probably had a bug when adding GeoSJON files.
If problem occurs again, I will try to be be precise on my report !

**Comment by Nyxelio** [comment]
Thanks for your report, i close this issue but don't hesitate to reopen if it's relevant.
