### ISSUE TITLE
Save some interventions fail

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#719]
When we try to save some interventions, nothing happened.
Interventions concern by this issue :
- covering
- net_installation
- net_removing
- lifting
- hilling
- hilling for sifting

**Comment by Aquaj** [comment]
Commit 5bb4fb gives actions to the procedures whose lack of `mandatory_actions` blocked the creation of new interventions - i.e. those who don't have any optional actions.
Those are :
  - hilling (associated action: hilling - already existing in nomenclature)
  - hilling_for_sifting (associated action: hilling - already existing in nomenclature)
  - lifting (associated action: lifting - already existing in nomenclature)

**Comment by Nicephore17** [comment]
Same problem with **Soil preparation / Subsoiling**.

**Comment by PH64** [comment]
What is the problem in Subsoiling ? I don't reproduce any problem

**Comment by Nicephore17** [comment]
When I click **Create** button, nothing appends and I get back in the same page instead of having intervention list page.

**Comment by Nicephore17** [comment]
I was trying with 2 working period and it failed.
With 1 working period it works.
Different bug ?

**Comment by PH64** [comment]
I don't reproduce problem

**Comment by Nicephore17** [comment]
No idea... Finally I created the intervention with one working period and edited it to add the second one.

**Comment by PH64** [comment]
With two period, I have no problem, one period edit to add a second period, no problem.

**Comment by EmmaDorie** [comment]
@Aquaj I don't add some `mandatory_actions` because there are procedures where users must choice between the `optional_actions` to know the objective of the intervention.

@Nicephore17 your issue is different, there is no problem with the actions.
If you reproduce your bug, please create a new issue.

**Comment by Aquaj** [comment]
Duly noted. As long as everybody's got either an optional or a mandatory, everything's fine code-wise! :+1:

**Comment by Nicephore17** [comment]
OK
