### ISSUE TITLE
Missing translation in Tools

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#720]
In **Tools / Listing and Mailing / New**.

![translationmissingtools](https://cloud.githubusercontent.com/assets/17082331/15858087/0c3e5230-2cbf-11e6-8460-f1bbb7bcfc65.PNG)

v2.0.0rc23

**Comment by Aquaj** [comment]
Confirmed some are missing in French too.

![missing_translationg](https://cloud.githubusercontent.com/assets/2871879/15887647/a3f48c12-2d63-11e6-9f79-6ef7c4f005c1.png)

**Comment by Nicephore17** [comment]
Thank you @Aquaj

**Comment by Nicephore17** [comment]
Works in v2.0.0rc24
