### ISSUE TITLE
Auto-numeration of product natures doesn't work

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#724]
When creating a new product nature , if number is left blank, form cannot be validated automatically. Need add number before validation maybe.

Maybe same bug on product nature variants.

**Comment by Nicephore17** [comment]
Thank you @burisu :D

**Comment by Aquaj** [comment]
Fixed for product natures but it doesn't seem blocking on product nature variants since the number presence isn't mandatory for them.
