### ISSUE TITLE
Bad translation on soil operations // Abilities list

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#726]
v2.0.0rc23

In abilities list (for product types), in english the following actions are available: **plough** and **plow superficially**. This is not accurate:
- Plow (in US english) = Plough (in UK english),
- Plow superficially don't make sense as plow has not the same effect on soil as surface works !

My suggestions (based en French version of Ekylibre):
- Labourer -> **Plow** (US english sounds better to me)
- Travailler le sol superficiellement -> **Shallow cultivating** (not totally sure for this one but makes sense).

Nota: does **uncompact** relies to soil ?

@EmmaDorie I think we already talk about this but I wasn't clear for me until now.

**Comment by Nicephore17** [comment]
@burisu if I had access to the code, I could submit an patch. I've found the correct files of the nomen in /lang ;-)

**Comment by Aquaj** [comment]
I agree on the *Plough* > *Plow* change but I don't think *Shallow cultivating* is quite appropriate here : the "superficially plowing" tools are really there to affect the ground itself more than the cultivation, ex: hoe, harrow, ...  
Maybe "work topsoil" ?

**Comment by PH64** [comment]
I'm not sure but it seems to me it 's "seedbed preparation"

**Comment by Nicephore17** [comment]
I will check with the team tomorrow !

**Comment by Nicephore17** [comment]
Soil cultivation (EN) = Préparation du sol (FR)
Cf. [Cultivating the Soil: Why it’s Important and How it Differs from Tilling](https://mantis.com/cultivating-the-soil-why-its-important-and-how-it-differs-from-tilling/) & [Soil Cultivation](http://www.landscape-america.com/landscapes/soil/cultivation.html)
Please note that Plowing = Tilling

**Comment by Nicephore17** [comment]
Any choice for next revision. @ionosphere ?
