### ISSUE TITLE
Repayments dates of yearly-paid loans are still monthly

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#728]
When making a loan with annual payment. We have a monthly list of payments.

![1](https://cloud.githubusercontent.com/assets/1838491/15912667/00b5d3d0-2dd6-11e6-832a-15fd7646fff4.png)

![2](https://cloud.githubusercontent.com/assets/1838491/15912670/03f2c2f6-2dd6-11e6-819d-f1cc38d6f2c9.png)

**Comment by burisu** [comment]
What is the problem? It's not clear

**Comment by burisu** [comment]
Sorry I read too fast
