### ISSUE TITLE
Campaing info in Production tab

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#729]
v2.0.0rc23

This how my campaign is defined:

![campaignedit](https://cloud.githubusercontent.com/assets/17082331/15930389/fad75ce0-2e52-11e6-814e-c2ccf2b0d89b.PNG)

This is the information user can see in **production** tab:

![campaignview](https://cloud.githubusercontent.com/assets/17082331/15930400/0ac535b4-2e53-11e6-8461-b37b003f06bb.PNG)

It would be nice to see more information in this panel.
In my case, displaying campaign description would be great.

Thanks.

CC @pdurancy

**Comment by PH64** [comment]
Activity is a generic term, like, corn, wheat, orchard... there is no concept of campaign in activity.
Activity en 2015 or 2016 is always the same.
Production = Activity + campaign
Corn 2016 = Corn + 2016

**Comment by Nicephore17** [comment]
For one field I will seed, harvest several times, disk and re-seed.
Does my initial activity stops at the end of the first crop and restart on second seeding intervention if it is the same crop or will it be a new activity ?

**Comment by PH64** [comment]
A production start and stop on one or more campaign.
Activity are always the same on the farm (corn, wheat, barley...). Activities have no start and stop.
You affect an activity on a field to have a production in a campaign
"it is the same crop or will it be a new activity" : it's a new production

**Comment by Nicephore17** [comment]
OK
