### ISSUE TITLE
Stock management (while creating interventions)

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#732]
In seeding intervention, input seed are based on individual instead of variant. Is it normal ?

Example: I need 50 bags of seed but I had 20 on stock so I buy 30 more. At the en I will have -20 bag of one sort and 20 of the other instead of 0.

As the 20 and the 30 are the same, the minus operation should be done on the variant no ?

**Comment by PH64** [comment]
Yes, it's normal. Interventions consume products, no variants. When you seed , you use a product and you choose it in your stock

**Comment by Nicephore17** [comment]
So I must specify a work number every time in get stock to know which on I can use ?
Nota: any function to avoid negative stock ?

**Comment by Nicephore17** [comment]
Usually, on stock management system we use several tools like FIFO (first in, fist out). In this cas, if the qtt needed is bigger than the older stock in, it empty it and start getting on the second one.

Example:
January: +20 bags
February: +30 bags
March: +20 bags
April: -27 bags (automatically calculated like -20 bags from January and -7 bags from February, stock available after intervention = 43 bags).

Then, for inventory, operator will know he should find 43 bags in the stock (not X from January, Y from February etc.).

As well, counting system can be based on "prix moyen podéré": the price of one bag at "l'instant t" is an average calc based on buying price and actual stock.

**Comment by PH64** [comment]
Ekylibre works by product, mainly because of lot number. So when you seed, you can use the product you want and not necessary the first in. The goal is to ensure the traceability of production, you know as well as you have sown variety 1 of Lot A in a field, and the same variety of lot B in another field.

You can know the stock of each product, and each variant with its weighted average price.

**Comment by Nicephore17** [comment]
OK.

**Comment by Nicephore17** [comment]
Please consider - at least - a control when validation an intervention to avoid negative stocks.
In my example it should be impossible to take 27 bags form the product we get in January.

I think there is 2 options:
- error message when validating intervention like "impossible to create intervention : insufficient stock of XX"
- during the setting of the intervention, in the input part, show the actual stock to pick the right product(s).

**Comment by PH64** [comment]
You are quite right in the inventory management of reasoning. It should be done in FIFO and it should never be negative stock. In fact, I'm not sure that many farmers do FIFO.
Block negative inventory may be inconvenient for the user who does not register regularly or record the stock from the month-end invoices.
Show the actual stock to pick the right product(s) is a good idea

**Comment by Nicephore17** [comment]
Concerning FIFO, it might be interesting, if the function is developed, to add an option in **Settings / Configuration** such as:

[] Allow negative stock
[x] Use consolidated inventory based on FIFO

So user will have the choice between using FIFO (and picking variant in intervention) or picking products from actual sock for traceability !

**Comment by Nicephore17** [comment]
Concerning the ones who do not _register regularly or record the stock from the month-end invoices_...

If I don't have any seed recorded in stock and want to use 20 bag for a intervention, my stock will be **-20 bags**.
Then, because I want to correct my stock, I record my incoming parcel of 20 bags. But, the incoming 20 bags will get a new product reference. So I will have a **-20 bags** line AND a **20 bags** line. This is not representative of the actual stock.
To correct this, the only solution is to edit the intervention and change the input to the new 20 bags... Still a bit complex no ?

**Comment by PH64** [comment]
These problems are no longer relevant with the new management package
