### ISSUE TITLE
Windrower abilities error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#736]
v2.0.0rc23

Windrower product type should not have **tow** ablility.

**Comment by EmmaDorie** [comment]
In our nomenclature, windrower have just the ability **mow**.
http://open-nomenclature.org/nomenclatures/product_natures/items/mower

If you have the ability **tow**, it's probably because you had add it.

**Comment by Nicephore17** [comment]
Sorry, I mixed up 2 instance. It was my mistake in _farmplus_ (has I have hand made it) but it's correct in "Liwa" withe the lase Nomen.

However, please note that nomen in your link is not correct, there is no **mower** in the last version for Ekylibre but a **windrower**. Should I report bug in  https://github.com/ekylibre/open-nomenclature.org ?

**Comment by EmmaDorie** [comment]
In nomenclature the term is still mower. We change only the translation to windrower in english.
