### ISSUE TITLE
Soil loosener indicator error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#737]
v2.0.0rc23

Soil loosener product type should be **geolocation** indicator.

**Comment by Nicephore17** [comment]
As well, when creating a Susoiler (variant for Soil loosener), some fields are missing in **Settings / (Production) Equipment**.

![subsoiler](https://cloud.githubusercontent.com/assets/17082331/16002841/f44ee19a-3159-11e6-858c-ec6c86fa6577.PNG)

**Comment by EmmaDorie** [comment]
I don't reproduce this issue
![screenshot - 13062016 - 11 35 13](https://cloud.githubusercontent.com/assets/11627573/16003042/1319a2da-315b-11e6-9c2f-4a93eef65683.png)

**Comment by Nicephore17** [comment]
What should I test. Delete subsoiler an create again ?

**Comment by Nicephore17** [comment]
For info: Equipment -> Soil loosener -> Subsoiler -> SS1

**Comment by EmmaDorie** [comment]
The informations that you want are available at creation of equipment. Not in the edition form.
The issue is in the form, not with indicators.

**Comment by Nicephore17** [comment]
Sorry but location, birth and death date are available in edition for my other equipments:

![equipementedit](https://cloud.githubusercontent.com/assets/17082331/16006786/382dab52-316f-11e6-8ba1-bac76ee3aa72.PNG)

Note: I have no problem when creating a second subsoiler.

**Comment by Nicephore17** [comment]
Actually, all this fields are no more available when the equipment is involved in an intervention.

**Comment by Nicephore17** [comment]
Death field should be always available as we don't know, at the creation date, when the equipment will be out of order ;-)

**Comment by Nicephore17** [comment]
See #751
