### ISSUE TITLE
Question : what is the "state" of an intervention ?

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#738]
v2.0.0rc23

In **Production / Intervention**, what is the **state** ? For all my intervention, it is in orange.

![intervnetiongeneralinfo](https://cloud.githubusercontent.com/assets/17082331/16006993/4e2e07de-3170-11e6-8b0d-a4ee7d38daa0.PNG)

**Comment by Nicephore17** [comment]
Same in v2.0.0rc24
Something to do with https://github.com/ekylibre/ekylibre/issues/686 ?

**Comment by burisu** [comment]
The status of an intervention is non-sense now. I'll remove it.

**Comment by Nicephore17** [comment]
OK in v2.0.0 thank you.
