### ISSUE TITLE
Any available pump and water supply abilities?

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#741]
v2.0.0rc23

Does the nomen as any entry for pump systems with associated abilities.
Our goal is to track pump maintenance as it is possible for workshop (tractors, equipments etc.).

If not, any idea of what abilities I should set to this type of equipement ?

**Comment by PH64** [comment]
Every equipments can be use in maintenance intervention and whatever the abilities are. 
CMMS will improve traceability of maintenance equipments.

**Comment by Nicephore17** [comment]
Actually, there is no maintenance intervention.

Are available: **Equipment item** replacement and **Oil replacement**.

**Comment by PH64** [comment]
What are maintenance operation on this equipment ? to ensure that the CMMS correctly handle this equipment.

**Comment by Nicephore17** [comment]
Sometime we can fix it by cleaning for example (no item nor oil remplacement).
We would like to track event. Maybe the good idea is to:

1. Create pump as equipment,
2. Log issue in Setting/Equipment ?

**Comment by PH64** [comment]
Yes you could create an equipment "Pump" and create an intervention item replacement without item and add en description "cleaning"

**Comment by Nicephore17** [comment]
OK. **Equipment item replacement** label could became **Equipment maintenance** ?

**Comment by PH64** [comment]
CCMS seems to solve this issue
