### ISSUE TITLE
Building is not displayed when drawing building divisions

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#742]
At creation of a new building division, the building selected as the container in not displayed.
A good solution would be to reproduce the way to draw a new production (= building division) from a cultivable zone (= building).

**Comment by Nicephore17** [comment]
+1 !

Also it could be nice to copy the building polygon easily when building division = building.
Ex.: open storage areas such as hay pads.

**Comment by EmmaDorie** [comment]
Yes, it's what happened when you draw a new production ...
