### ISSUE TITLE
Bad timing on matter tracking (stocks)

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#749]
v2.0.0rc24

When processing an intervention, the stock update is not recorded at the actual intervention date but when the intervention is logged in Ekylibre.

For example : I created today a fertilizing operation for the 15th of March but the stock decreases today instead of March.

Can it be corrected to fit reality ?

![stockevolution](https://cloud.githubusercontent.com/assets/17082331/16118098/bb9382ba-33d5-11e6-935e-45810c72c30a.png)

**Comment by PH64** [comment]
see #774
