### ISSUE TITLE
Qestion : lot management in stock.

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#750]
v2.0.0rc24

Is it possible to have different weight for a same variant but a different product ?

When pressing bales, the equipment is suppose to create 250 Kg bales. Actually, after weighting the production, we make an average weight per field between 240 and 160 Kg.

Is it possible to record all harvested bale as **250 Kg Hay Bale** fand then correct the weight as each product number corresponds to a particular field ?

Related to https://github.com/ekylibre/ekylibre/issues/721

**Comment by PH64** [comment]
Waouh ! it's a complicated question...
It isn't possible to have different weight for a variant but it's possible for products. Nevertheless, it is not easy to change the weight of a product.
I think it's got to be simple : 
- Hay bale unity could be kg or t
- In intervention, number of bale could be converted in weight (x bales*250kg)
- so the stock will be in weight and you could make an inventory to adjust the stock.

The only inconvenient is that the number of boots will always be proportional to the weight defined in the variant (4 boots per tonne if 250kg).

Is it enough?

**Comment by Nicephore17** [comment]
Well... I think I'm looking for the opposite !

My idea: _counting in bales_. If so, the **250Kg Hay Bale** could be counted in **unity** instead of weight. Then in could count the stock in unity (but not accurately on tons) on my farm.

Later, when selling (and weighing the shipment), I could add the weight information to the corresponding lot. Then, after few campaign, il will be able to track mean weight of every harvest.

Possible ?

We should had a phone chat tomorrow.

**Comment by PH64** [comment]
Yes, it's possible to count in bale and now it works like this.
- the variant unit is bale, and variable indicator of product type is net mass.
- In matter you could see nb of bale and weight 
- you change the weight in "analysis"
- adjust nb of bales in inventory

On the other hand, invoicing will be in nb of bales (unity of the variant)

**Comment by Nicephore17** [comment]
OK, I'll try tomorrow then.

**Comment by Nicephore17** [comment]
We will probably need to hack something somewhere as the price depends if the total actual weight of the truck, not the number of bales...

**Comment by PH64** [comment]
That's why I think it's more simple to work in weight (actually intervention don't convert bale in weight)

**Comment by Nicephore17** [comment]
It is impossible to have a constant bale weight for a harvest. Depending of ETP, baler settings, speed and other factors we can get more than 5% error. That why we think on adapting weight depending of lot (1 field = 1 lot) based on average weight of the harvest. Keep in mind that, for us, a field can be harvested up to 10 times a year and can have large variation ms from a cut to another !

**Comment by PH64** [comment]
That's exactly why it will be easier to work in weight rather than number of bales in Ekylibre. Nb of bale could give only a indication of weight and you can adjust it when you 'll have weighted them.

Don't forget unit of the variant is the unit of sale and you can't convert unities other than interventions
