### ISSUE TITLE
Installations are not displayed in the dropdowwn list "container"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#752]
At creation of a new product, only the building divisions are displayed in the container list and installations are missing.

**Comment by Nyxelio** [comment]
Settlements are the easy way to group building / building divisions, so they are only availables if you add one of these product nature variant.

**Comment by EmmaDorie** [comment]
An installation with the product_nature_variant "settlement" (which is not a building or a building_division, parking for example) is not display while it can contain an equipment for example.

**Comment by igkyab** [comment]
Fixed with 3d4396ae9cf1c79b1b85f57dfe386e64e2b3f6fd
