### ISSUE TITLE
Question : changing connexion screen backgound

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#756]
v2.0.0rc24

Is it possible to change the image background of the connection screen like with http://demo.ekylibre.farm page ?

**Comment by Nyxelio** [comment]
Yes, all you need to do:
* Go to the Tool menu > Import section
* Create a new import and choose the 'Visual - Ekylibre' type.
* Select your image and create.
* Then, don't forget to execute your import.

**Comment by Nicephore17** [comment]
Thanks !

**Comment by Nicephore17** [comment]
Additional question : is it possible tu remove it (and revert to default login background) ? Should I log a new request ?

**Comment by EmmaDorie** [comment]
If you want, I can send you the picture of the default background by mail. Send me a mail if you want it ;)
