### ISSUE TITLE
Cropping plan widget feature

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#757]
v2.0.0rc24 @clegris

Is it possible to add some abilities to the cropping plan widget ?

![widget_croppingplan](https://cloud.githubusercontent.com/assets/17082331/16149267/e709c6d8-348f-11e6-9250-f2eef2152eab.PNG)

It would be great to add a link from parcel to its production page.

**Comment by Nicephore17** [comment]
Note: any ways to show also not cultivated parcels ?

**Comment by PH64** [comment]
Cropping plan is made form production. If there isn't production, there isn't cropping plan.
To have them in cropping plan, you can create fallow production in those field.

**Comment by Nicephore17** [comment]
OK

**Comment by Aquaj** [comment]
Everything seems in order here. Closing the issue.

**Comment by Nicephore17** [comment]
What about initial request: _add a link from parcel to its production page_ ?

**Comment by EmmaDorie** [comment]
Open a new enhancement issue specifically for this enhancement request.
