### ISSUE TITLE
Error on display of map at creation of a new intervention

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#759]
At creation of a new intervention :
1) The map disappear when updating the working_period
![screenshot - 17062016 - 14 23 51](https://cloud.githubusercontent.com/assets/11627573/16150455/8cda38e8-3497-11e6-92b4-bb5f10002985.png)

2)The map is not update if user begins by typing the name of the land parcel instead of selected it directly in the drop-down box
- Exemple :
Cultivable zone "A côté de la vigne maïs 2014" has been selected directly in the drop-down box
![screenshot - 17062016 - 14 24 09](https://cloud.githubusercontent.com/assets/11627573/16150502/d0e608dc-3497-11e6-949d-82899d6ac4c1.png)
Cultivable zone "Bernessard Orge d'hiver 2015" has been selected by tying the first letter "b" and the map displayed is not update
![screenshot - 17062016 - 14 24 20](https://cloud.githubusercontent.com/assets/11627573/16150552/25eb4f18-3498-11e6-91c8-7c8ac3d367bf.png)

**Comment by Nyxelio** [comment]
1) is closed by 6bcbe0e
2) is due to two concurrent events: First event with the letter typed and the second with the item selected. The issue here is the first event locks ajax logic until it gets a response.
