### ISSUE TITLE
Subsoiling : crop target is not available

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#760]
v2.0.0rc24 @clegris like #748 

In **Production / Soil preparation / New / Subsoiling**, it is not possible to set a crop as a target but only a land parcel. As Subsoiling can be used to clean a field after its production it will be interesting to link intervention and activity.

Can you consider allow both target like in Subsoiling intervention ?

**Comment by EmmaDorie** [comment]
@ionosphere I don't understand consistency for agriculture.
Subsoiling is on the soil, not on a crop.

@Nicephore17 if you make this intervention on the land parcel it will be link to the production and the production is link to activity, so I don't understand the problem.

**Comment by Nicephore17** [comment]
Subsoiling can be used to kill a crop so it can be linked to the crop as well.

Until now, I am not able to know if an intervention is correctly linked to a production because of #528.
Also, in **Production/Interventions** it is not possible to sort all operation done for a same production as targets are land parcel _or_ crops but intervention should gather land parcel interventions _and_ crops interventions...

FYI : @Clegris and @Pdurancy

**Comment by EmmaDorie** [comment]
Yes, you can't see it because of the #528 but interventions are correctly linked to production even if it's not displayed.

In Ekylibre the logic is : if the target is really the crop and not the land parcel, for example "foliar spray", crops are available. But if it's on the "soil" the target is the land parcel.

**Comment by PH64** [comment]
Yes, we can see the link in list of interventions in Production/intervention and you can filter this list.

**Comment by Nicephore17** [comment]
Filter though _support_ ?

**Comment by PH64** [comment]
For example

**Comment by Nicephore17** [comment]
Let's have an example: I grow Rhodes Grass (the crop is RG_P15_2015) in my land parcel (Pivot 15). Then I have several intervention for the same production: subsoiling, seeding, fertilize and harvest.

**If I filter through RG_P15_2105** I will only get operations targeting the crop: fertilize and harvest.
**If I filter through Pivot 15** I will only get operations targeting land parcel: subsoiling en seeding.

Where can I control that this 4 interventions rely to the same production ?
What about adding a production column in the list ?

**Comment by PH64** [comment]
It's the same between in activity/production and land parcels/plants. It depend if your target is production or culture.

Activities column is already present in the production/intervention list

**Comment by Nicephore17** [comment]
The activity column relies to the campaign so to all the activities of the same type. My purpose it to get all the intervention on one field to compare cost and profit. In I get 10 fields in the same activity I can't easily compare them.

Reading your last post, I realize it it difficult to get the difference between an activity as a campaign and an activity as **a part of** a campaign. So, the label in interventions list should be more accurate if it was **campaign** instead of **activity**.

**Comment by PH64** [comment]
What do you mean by : 
- _an activity as a part of a campaign ?_ activity is for example _corn_ and a campaign _2016_
- _So, the label in interventions list should be more accurate if it was campaign instead of activity._ ?

**Comment by PH64** [comment]
What do you mean by : 
- _an activity as a part of a campaign ?_ activity is for example _corn_ and a campaign _2016_
- _So, the label in interventions list should be more accurate if it was campaign instead of activity._ ?

**Comment by Nicephore17** [comment]
I mixed up _Activity_ and _Production_.
So: an activity = a campaign. In an activity their is several production.

My need: summarize cost of a **production**.

**Comment by PH64** [comment]
OK

**Comment by Nicephore17** [comment]
OK in v2.0.0rc25

**Comment by EmmaDorie** [comment]
Changes reverted because is different with logic of other procedures.
If your real need is to summarize cost of a production, please open an other enhancement issue.
