### ISSUE TITLE
Search bar in interventions doesn't work as expected

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#763]
The research in a list of interventions doesn't work as expected.
For example, when typing the word "sowing", there are no result even if some sowing interventions are registered.

**Comment by burisu** [comment]
Fixed by 839ce7b2b5cad26d2ff738ee8704983f38e5f477.

**Comment by EmmaDorie** [comment]
Add the possibility to search on intervention parameters (input, tools...).
