### ISSUE TITLE
Piece replacement can be fill without any component

### ISSUE THREAD

**Issue by Guichevrat** [ekylibre/ekylibre#765]
A piece replacement intervention can have no piece to replace.  To resume the field piece is not mandatory and must be

**Comment by Nicephore17** [comment]
Actually, no. If the field not mandatory, we can use the intervention to record a operation that need no replacement !

Please check our discussion with @PH64 on #741.

IMO, the piece field could be mandatory and then we could have another type of maintenance operation with no item. What do you think @ionosphere ?

**Comment by Nicephore17** [comment]
@Guichevrat please note that "pièce" is translated by "item" in english version of Ekylibre ;)

**Comment by Guichevrat** [comment]
My bad @Nicephore17 but we'v checked on linguee the first time, and piece seems to be correct aswell :)

**Comment by burisu** [comment]
Component won't be mandatory to register replacements when no component defined on product nature variant. For repairs #1038 will implement wanted feature.
