### ISSUE TITLE
Fieldset in inspections view gets out of screen when zoomed on in then back out.

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#766]
Fieldset "stock in ground" is not responsive and graphs comes out of the screen.

![agreage_2016-06-21 13-27-50](https://cloud.githubusercontent.com/assets/11627573/16227935/18ba9dc0-37b4-11e6-90ec-cf17e3e1f4ab.png)

**Comment by Aquaj** [comment]
Could not reproduce, is the problem still there ?

**Comment by EmmaDorie** [comment]
Yes, try to zoom on the screen.

**Comment by burisu** [comment]
@Aquaj, Should we forget `<table>` use definitively?

**Comment by EmmaDorie** [comment]
Issue still exists in the plant view : 
![chasse-aux-bugs culture zc_02 courtade 2 carotte n 1 2016-08-05 11-16-56](https://cloud.githubusercontent.com/assets/11627573/17432199/47a1e04a-5afe-11e6-9da4-6c167a49ef31.png)
