### ISSUE TITLE
Translation update : "item" in maintenance intervention

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#767]
v2.0.0rc24

In **Intervention / Equipment maintenance / Equipment item replacement**.
_Item_ in used for the french word _pièce_ as a part of an equipment.
In english, _item_ mean _un article_, like a _thing_.
The correct world should ba **part** like for _spare parts_ (_pièces de remplacement_).

cf. http://www.dictionary.com/browse/part?s=t

**Comment by Guichevrat** [comment]
i had checked this, you are actually right. the term "Parts" is used aswell in "fleet-maintenance" and "DIMO Maint" for example ! I'll fixe it soon

**Comment by Nicephore17** [comment]
Thank you.

**Comment by PH64** [comment]
Maintenance intervention has been changed in 2.3.0
