### ISSUE TITLE
Display the shadow of plants when drawing a sowing intervention

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#768]
At creation of a sowing intervention, user need to see the shadow of the other **active** (#666) crops.
For the moment, land parcel are displayed but if there are several crops on one land parcel, it's difficult to draw it without overlap.

**Comment by EmmaDorie** [comment]
Same issue with **cultivable zones** and **productions**.
When adding a new cultivable zone, user need to see other cultivable zones.
When adding a new production, user need to see other active land parcels.

**Comment by Nyxelio** [comment]
Fixed by 0a655a7ddfd3a71c637c400bc015d89911ef09a8
