### ISSUE TITLE
Unpredictable sorting behavior in views because some columns are 'sortable' when they shouldn't be.

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#769]
sorting activities and target in the list of interventions doesn't work as expected

![capture du 2016-06-23 12-52-16](https://cloud.githubusercontent.com/assets/12525665/16300671/5d49fb3c-3941-11e6-90a8-926658243208.png)

**Comment by Aquaj** [comment]
Current system shouldn't allow us to sort some columns due to technical limitations.
Removing the sorting options on those for now. Sorting on these will come later when the "Lexicon" rework will be done.
