### ISSUE TITLE
Calculation errors in stocks

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#774]
- When processing an intervention, the stock update is not recorded at the actual intervention date but when the intervention is logged in Ekylibre (if intervention is updated, it's OK)
- the stock is displayed 0 instead of the actual value
- On the graph, at the date + 7 days after the recording of the intervention in Ekylibre, stock = 0
- On the graph, before buying, the stock is equal to the quantity purchased

![capture du 2016-06-25 15-26-21](https://cloud.githubusercontent.com/assets/12525665/16356969/4201f65a-3ae9-11e6-8074-abd12100aa2c.png)

![capture du 2016-06-25 15-06-40](https://cloud.githubusercontent.com/assets/12525665/16356971/487f54c8-3ae9-11e6-895c-a79ddc1d9100.png)

**Comment by EmmaDorie** [comment]
This point still persist : 
On the graph, at the date + 7 days after the recording of the intervention in Ekylibre, stock = 0
