### ISSUE TITLE
Plant density abaci is not finished

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#776]
![plant_density_abaci](https://cloud.githubusercontent.com/assets/11627573/16386011/6d353506-3c8f-11e6-9a87-5bdb64a6b4a6.png)

**Comment by Aquaj** [comment]
Plant Density Abaci now integrated with Activity (as of 66dbd49). Show view will be implemented as Zero advances and requirements get more defined.

**Comment by burisu** [comment]
Not sure of your commit ID

**Comment by Aquaj** [comment]
Technically the form was integrated within the activities/_form with commit 7eba540. Commits 3ea71d2 and 3369c2a made it cleaner and fixed some links, cb6bafe introduced a show.json view to avoid errors (esp on rake clean).

**Comment by burisu** [comment]
Fixed with 7307d1c62b7ef6c2c09ca33e16479b1846d9617f and 50729f6a3698d6434e04657ecc4dcccb6804f144.
