### ISSUE TITLE
Stewardship label errors

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#780]
v2.0.0rc24

![stewardship](https://cloud.githubusercontent.com/assets/17082331/16454618/b3da3b0e-3e11-11e6-87ed-cd4991aa7fd0.PNG)

**amenities** should be renamed **Equipment** to be consistent with Ekylibre langage.
**arable areal** should become **Arable areas** (with "A" upper case) or **Land parcel**

**Comment by Nicephore17** [comment]
"amenities" is not corrected in v2.0.0rc25

![stewardship2](https://cloud.githubusercontent.com/assets/17082331/16542232/7c3989ca-40a0-11e6-9c89-1b365875cf8c.PNG)

**Comment by Nicephore17** [comment]
"amenities" is not corrected in v2.0.0rc30
@EmmaDorie

**Comment by burisu** [comment]
I found it! this translation comes from a plugin in production

**Comment by Nicephore17** [comment]
\o/
