### ISSUE TITLE
Last intervention widget

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#781]
v2.0.0rc24

Last intervention widget displays no data...

![lastinterventions](https://cloud.githubusercontent.com/assets/17082331/16454780/5c511be0-3e12-11e6-9eee-ae2768a41bdb.PNG)

**Comment by Nicephore17** [comment]
It works in "demo" instance but not in "liwa" :-(

**Comment by PH64** [comment]
It doesn't work in demo : The widget displays an intervention but not the last

**Comment by burisu** [comment]
The cell shows the last intervention of the current campaign by default in dashboard if any. It depends entirely on target distribution. Since target distribution interface has been added in 2.0.0.rc25, I consider question is closed.
