### ISSUE TITLE
Update the form of inspection creation

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#782]
In the form of inspection creation, the red star is missing on several fields :
- implanter_application_width
- implanter_rows_number
- sampling_distance
- product_net_surface_area

Furthermore, it's possible to registered inspection even if the field product_net_surface_area is empty whereas this value is required.

**Comment by Aquaj** [comment]
product_net_surface_area is not required because it's automatically set to the selected product's net surface area if empty on validation

Adding validation on sampling_distance.

**Comment by burisu** [comment]
If `product_net_surface_area` is really optional, others fields are really required. I'll check that
