### ISSUE TITLE
Building definition: double area system

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#787]
v2.0.0rc24 @ionosphere 

When creating a building in **Settings / Building / New**: area is automatically calculated in the map. However, **Net surface area** (in **Indicators**) is not automatically updated.

![superficie](https://cloud.githubusercontent.com/assets/17082331/16517866/060e8776-3f80-11e6-8007-40c0cb8db49c.PNG)

**Comment by PH64** [comment]
it is useful to be able to record a surface different of the calculate surface. the useful area may be different from the total area of the building

**Comment by Nicephore17** [comment]
Autofill + possible update ?

**Comment by PH64** [comment]
Don't think it's possible. Net surface area is an indicator from product type "building".
 If you don't want 2 surfaces, delete the indicator Net Surface in Product type

**Comment by Nicephore17** [comment]
I meant : what about auto fill net surface from Leaflet data but allow modification before validation ?

**Comment by Nicephore17** [comment]
@ionosphere told me that the field may be useless...

**Comment by PH64** [comment]
Indicators from Product type can't be autofill because they are complementary information. 
In this case, Net surface is usefull exactly because it's different and exact compared of calculate area and . (You can record surface equal to the building permit that is more difficult to draw)
You could add also height, volume...

**Comment by EmmaDorie** [comment]
Yes, I agree with @PH64, the field allows to be more precise if it's necessary. 
Futhermore, the value is in the context of the map and it's difficult to take it out. So, it represents lots of development for a minor improvement (draw a new building is not so common) .
