### ISSUE TITLE
Blocking bugs in the sales/purchase section

### ISSUE THREAD

**Issue by bainacitron** [ekylibre/ekylibre#788]
I've been using the sales/purchase and the accounting sections of Ekylibre for the management of my accounting for several months. Since about 1 month the "Sales" button in the interface, which was going to the section where one can create invoices is no longer working. It now goes to a page saying "this page does not exist anymore". Impossible to create invoices for my sales anymore which is quite blocking. 

On the other side, when I enter some purchases for my company, the interface does not allow me to select the VAT rate anymore. The field is shown but when I click on it, it does not show any menu while I checked and all my VAT rates are well configured in the "configuration" section and my product price catalogue is filled as well.  

I've been always using this service with Chrome browser, and it was working ok until about 1 month ago. Thank you in advance for your quick help to resolve this issue.
Ewa

**Comment by burisu** [comment]
The error came from an "old" responsible which is no more responsible:
```
An ActionView::Template::Error occurred in sales#index:

  Couldn't find all Entities with 'id': (102, 2) [WHERE "entities"."nature" = ?] (found 1 results, but was looking for 2)
  app/views/backend/sales/index.html.haml:11:in `block (2 levels) in _app_views_backend_sales_index_html_haml__3005660722300155624_70253454481920'
```
It have been fixed in 2e561d2d10046f3c8c0742f7b4407814791c06ba which is in 2.0.0.rc25.
