### ISSUE TITLE
Impossible to change a parcel from the status "in preparation" to the status "prepared"

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#789]
When I try to change one of the parcels to the status "prepared", I have error messages.

The error mail is :

> An ActiveRecord::RecordInvalid occurred in parcels#check:
> 
>   Validations échouées : Numéro d’identification ne peut pas être vide
>   app/models/product_nature_variant.rb:292:in `create_product!'

@Aquaj ask me if you want to see the datas 
![le changement que vous avez demande a ete rejete 2016-07-04 10-19-13](https://cloud.githubusercontent.com/assets/11627573/16554714/d4db35c0-41d0-11e6-87a1-1eb765bf7cca.png)

(please note to add a space : " quelque chose" in the message)

**Comment by Aquaj** [comment]
Bug has been identified, is being fixed.
As a specific fix instance's data has been *slightly* modified (switched parcel contents product nature from "Mouche variety Bombus" to "Larve de Mouche variety Preparation derivative of Bombus") to ensure proper functioning of the parcel.
