### ISSUE TITLE
Error on activity show

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#790]
in backend/activities :

![nous sommes desoles mais quelque chose s est mal passe 2016-07-04 10-29-56](https://cloud.githubusercontent.com/assets/11627573/16554934/4a551a90-41d2-11e6-8c61-b296fb473d4e.png)

The error mail is :
> An ActionView::Template::Error occurred in activities#show:
> 
>   undefined method `boolean_value' for #<AnalysisItem::ActiveRecord_AssociationRelation:0x007f9d039cfc50>
>   app/views/backend/activities/show.html.haml:75:in `block (3 levels) in _app_views_backend_activities_show_html_haml___221645794875190596_70156122771100'

**Comment by Nyxelio** [comment]
Fixed by 69f8ed1c7192d60fc14ad557dd6db5df80d73293
