### ISSUE TITLE
Seeding price calculation error

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#792]
v2.0.0rc25
Cf. https://liwa.ekylibre.farm/backend/interventions/26

Hi have error on seeding price calculation. For 3 similar seeding interventions with the same seeds only one is correct...

![seedingprice](https://cloud.githubusercontent.com/assets/17082331/16562693/8264104a-41fe-11e6-9d4c-d67df18cdedb.PNG)

![reclaimer](https://cloud.githubusercontent.com/assets/17082331/16562775/cbe0a9c2-41fe-11e6-88d3-d1ee82b323f2.PNG)

**Comment by EmmaDorie** [comment]
Yes, after calculation :
(20x50,27)/25 = 40,216kg big bag --> and not 4,021
40,216x250 = 10054

I think that deduction of products in stocks are false to ?

**Comment by Nicephore17** [comment]
Yes

**Comment by Aquaj** [comment]
Despite all my trying, I'm unable to reproduce.
Does the error only happen in this intervention or is it a recurring problem?

**Comment by Nicephore17** [comment]
1st time. I created 3 similar interventions. Only 1 was OK.
To correct one of the 2 other, I manually update quantity in kg (instead of kg/ha).
If you give my your mail, I can invite you to check in my instance.

**Comment by Aquaj** [comment]
Thanks, I'd gladly take a look at it.
My mail is jbonal (ekylibre.com).

**Comment by Nicephore17** [comment]
Done.
You will get the seeding here: https://liwa.ekylibre.farm/backend/interventions?utf8=%E2%9C%93&q=&procedure_name=sowing&product_id=

**Comment by Aquaj** [comment]
Thank you, I'll take a look at it.

**Comment by Aquaj** [comment]
After taking a look, it appears it only happened on old interventions, it shouldn't happen anymore nowadays (some bugs related to intervention parameters handlers have been fixed), hence why we can't reproduce it on creation of new interventions.

I fixed the values on your incorrect intervention, if it does happen again on more recents interventions (created after June '16) we'll reopen the issue.

**Comment by Nicephore17** [comment]
OK

**Comment by PH64** [comment]
I have the problem yesterday on the demo
