### ISSUE TITLE
Error when right clic on the button "map" to open in a new tab

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#795]
In production views, when trying to open the map in a new tab on right clic, there is an error.

![action controller exception caught 2016-07-08 18-01-29](https://cloud.githubusercontent.com/assets/11627573/16693588/17e12f06-4536-11e6-90a8-a4ee10cb744f.png)

**Comment by burisu** [comment]
The bug appeared because it's not unobtrusive. Need a partial rewriting of `janus` to fix bug.
