### ISSUE TITLE
At creation of a new future production land parcels are empty

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#809]
When adding a new production in an activity, if the start date of the production is later the today's date, production has no shape : 
![activity_productions](https://cloud.githubusercontent.com/assets/11627573/16987418/72aef5f8-4e8c-11e6-9517-fafb91d7a678.png)
And the land parcel created with the production has nothing : 
![landparcel](https://cloud.githubusercontent.com/assets/11627573/16987451/a28560a0-4e8c-11e6-826d-0af1ec9537c0.png)

**Comment by PH64** [comment]
Shape in production is corrected, but land parcel are always empty

**Comment by burisu** [comment]
It's more logical for land parcels to be empty because they don't exist at this moment. Although it's pretty bad to see blank map, for that reason, I'll make a change to see future shape of land parcel.

**Comment by PH64** [comment]
The created land parcel can be edited but : 
- in the list of land parcels, the surface is always 0.000m2 (not in modification)
- now, if we click on a land parcel, there's an error message

**Comment by burisu** [comment]
I went too fast on test. I'll fix that... sorry for my neglect and thank you for your help
