### ISSUE TITLE
Problem of unity in hervest intervention

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#815]
One unity is Kg (masse nette en tonnes)
Could it be possible tu add Qx/ha in the list ?

![capture du 2016-07-22 08-50-05](https://cloud.githubusercontent.com/assets/12525665/17048947/0547655e-4fea-11e6-9d87-8190b3a1fa4e.png)

**Comment by Aquaj** [comment]
Fixed, units are now displayed correctly as being what they were supposed to :
- unity
- quintal
- ton
- quintal/hectare
