### ISSUE TITLE
Impossible to create a new entity

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#816]
At creation of new entities, there's an error message.

A SyntaxError occurred in entities#new:

  /var/www/sheep-demo/releases/20160721013656-ekylibre-2.0.0.rc28/app/views/backend/entities/_form.html.haml:20: syntax error, unexpected ':', expecting =>
..., :field => elect, elected: f.object.country || Preferen...
...                               ^
  app/helpers/backend/form_builder.rb:619:in `fields'

**Comment by Nyxelio** [comment]
Already fixed by @Aquaj on 96f4f0c2401fa21ff91637cc2f3104c2cb3db14d

**Comment by PH64** [comment]
Sorry !
