### ISSUE TITLE
Issue on productions still persist when a quantity is in "unity" in the budget

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#819]
In an activity, when a budget is defined with a product_nature_variant in "unity", land parcels are always empty and it's impossible to open the productions linked to this activity.

**Comment by EmmaDorie** [comment]
issues #809 and #811

**Comment by Aquaj** [comment]
I went on [Activity 14](https://demo.ekylibre.farm/backend/activities/14)
[Budget](https://demo.ekylibre.farm/backend/activity_budgets/16/edit?redirect=%2Fbackend%2Factivities%2F14) is linked to a ProductNatureVariant "Location" in unity.
I still can open the [production](https://demo.ekylibre.farm/backend/activity_productions/49).

Did I misunderstand something? Is it possible to have some more details?

**Comment by EmmaDorie** [comment]
More informations sent by mail.

**Comment by Nyxelio** [comment]
Updating the land parcel fixes the issue. I think the land parcel had a shape indicator registered in the intervention creation and not in the intervention date, which could break shape retrieving. It is already fixed, see #823
