### ISSUE TITLE
land parcel register export : Error 504 Gateway timeout

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#822]
Most of the time, the export of Land Parcel Register generates an error 504 Gateway timeout
### 1- How to reproduce?
Go to Tools > Exports > Land parcel register. Page isn't loading.

### 2- What is really expected?
The Land parcel register.

### 3- How to test it?
Go to Tools > Exports and load the page "Land parcel register"

**Comment by Aquaj** [comment]
Discussed it with @burisu:
We'll try and see what takes up all that time and cut some down to try and solve this problem.

There'll be a rework of the PDF generation too at some point in the future.

**Comment by Aquaj** [comment]
After inspection, the work needed to optimize that quite heavy; it'll come, but for now we're moving this to the 3.0.0 release.
