### ISSUE TITLE
Activity production chronology period doesn't match

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#825]
When I create new production which is started to 05/07/2016 and finished at 26/08/2016, i have a gap on the product chronology bar (with my exemple, the bar begins between may and june and finished at the end of june).

**Comment by Aquaj** [comment]
I made some changes to better visualize the actual boundaries of the chronology. 

I'm not sure it was what you were talking about though (with the dates you use in your example, the bar displayed on my side definitely doesn't start between May or June but more like January/February).

Was I right to understand it's the chronology in Activities#show that is in question here or is it somewhere else ?

**Comment by igkyab** [comment]
Yes, it's in Activities#show.

The first product is defined like this : started at 01/10/2015 and finished at 01/08/2016.

**Comment by Aquaj** [comment]
Tested again with your data : 
There is indeed your problem if I test w/o commit c956678, but when tested with that change, it appears to be fixed.
If you can confirm that, I'll close the issue.

![activity_productions_chronology](https://cloud.githubusercontent.com/assets/2871879/17131715/05c6962a-531f-11e6-956e-df665a5c29f4.png)

**Comment by igkyab** [comment]
Tested again with your corrections. I confirm, it's fixed for me too.

**Comment by Aquaj** [comment]
Great ! :+1: 
Closing the issue.
