### ISSUE TITLE
Inventory print doesn't work

### ISSUE THREAD

**Issue by kakahuete** [ekylibre/ekylibre#831]
Something went wrong...

**Comment by Aquaj** [comment]
A RuntimeError occurred in inventories#show:

`net.sf.jasperreports.engine.JRRuntimeException: java.lang.IllegalArgumentException: `
`    Invalid character: P`

-------------------------------
Request:
-------------------------------

  * URL        : http://demo.ekylibre.farm/backend/inventories/1.pdf?key=&redirect=%2Fbackend%2Finventories%2F1&template=25

-------------------------------
Backtrace:
-------------------------------

  config/initializers/apartment.rb:52:in `call'

**Comment by Nyxelio** [comment]
Inventory sheet template contained a codabar component which attempts to render code from the product number property (i.e P00000000001) but it's invalid.
