### ISSUE TITLE
Unit in outgoing parcel items are always "#"

### ISSUE THREAD

**Issue by kakahuete** [ekylibre/ekylibre#832]
![image](https://cloud.githubusercontent.com/assets/20659539/17133273/b4d98ac2-5325-11e6-8c9b-c11067e6d3b0.png)

**Comment by EmmaDorie** [comment]
#664

**Comment by Aquaj** [comment]
Cannot reproduce.

Before selecting a product.
![before](https://cloud.githubusercontent.com/assets/2871879/17136252/909abd5c-5334-11e6-94bf-4dcefc32418d.png)

With non-unitary product.
![after](https://cloud.githubusercontent.com/assets/2871879/17136256/92d34846-5334-11e6-8a8f-264a89a730e1.png)
With unitary/identifiable product.
![after-unitary](https://cloud.githubusercontent.com/assets/2871879/17136500/10028128-5336-11e6-8d10-796c2a5ec415.png)

**Comment by Aquaj** [comment]
Cannot reproduce on Chrome either. (Updated after-unitary screenshot in last comment to showcase this.)

Something JS related probably, but what ?

**Comment by burisu** [comment]
Problem is a production problem. My console says that the request is HTTP in a HTTPS context is not cool
