### ISSUE TITLE
Crops list enhancement

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#835]
In Production / crop / crop list, it could be useful to see the dead on date and the status.

work name isn't translate in french

![capture du 2016-07-27 08-32-41](https://cloud.githubusercontent.com/assets/12525665/17166024/b7a1caf8-53d4-11e6-9989-64e06d6e4af5.png)

Same request for the land pacels (configuration/land parcels)

**Comment by PH64** [comment]
Could you add the creation date and dead date in the Land Parcels list. 
Thanks
![capture du 2016-07-27 10-33-27](https://cloud.githubusercontent.com/assets/12525665/17168977/9702075c-53e5-11e6-8fbc-5cbdfe133c63.png)

**Comment by Aquaj** [comment]
Oh yes of course, I didn't see that last line in your first message.

**Comment by PH64** [comment]
The creation date of land parcels isn't the same in the list and in the description of the land parcels

**Comment by Aquaj** [comment]
As of e63c749 they appear to be the same on my side. Can I have an example ?

**Comment by PH64** [comment]
In the list, this is the creation by Ekylibre, not the born of the land parcel

![capture du 2016-07-27 11-34-33](https://cloud.githubusercontent.com/assets/12525665/17170828/2a9e2b50-53ee-11e6-863c-61c004544216.png)

![capture du 2016-07-27 11-34-08](https://cloud.githubusercontent.com/assets/12525665/17170833/3115940a-53ee-11e6-9627-f919a916589e.png)

**Comment by Aquaj** [comment]
Do you have the latest version of the code ? It should be "Créé le" instead of "Date de création" as the column title as of commit e63c749.

**Comment by PH64** [comment]
You are right !! Sorry !

**Comment by Aquaj** [comment]
No problem :smile:
