### ISSUE TITLE
Parenthesis appears after the name of the target in interventions

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#852]
Parenthesis appears after the name of the target when an intervention is created but them are always empty. What is utility of these parenthesis ?

![demo interventions 2016-07-y28 09-39-45](https://cloud.githubusercontent.com/assets/11627573/17204748/9025043a-54a7-11e6-9e13-ea638f269c5d.png)

**Comment by burisu** [comment]
`work_number` should appear into this parentheses.
