### ISSUE TITLE
Incoherent left menu in configuration

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#853]
The left menu entitled "people" is incoherent with submenus "postal_zones" and "districts"
![demo equipiers 2016-07-28 10-29-02](https://cloud.githubusercontent.com/assets/11627573/17206133/a1641298-54ae-11e6-8331-9f2f26742958.png)

**Comment by burisu** [comment]
The postal zones and district are used by entity mail address and its the main reason of that. But I can understand that it's not friendly
