### ISSUE TITLE
Improve the worker form

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#854]
- Fields born_at and dead_at should be adapted for this form and replaced by hiring_date and leaving_date (or something like that).
- The field "initial_owner" is not adapted in the form workers.
- It's too long to have to registered the entities attached to the worker each time.
  If it's really necessary, the entities should be created automatically if the contact doesn't exist yet.

**Comment by burisu** [comment]
- `born_at` and `dead_at` are the valid dates and associated meaning. If the need is to follow job contracts, it's another thing. Although, we can hide this fields if preferred.
- :+1: for the `initial_owner`
- A button has been added on contacts which are not supplier, client or transporter. It permits to pre-fill worker form with all existing data. See 90fd2fafa7a5a310ca51c266d822a991c41686a7.

**Comment by EmmaDorie** [comment]
- Now, `born_at` and `deat_at` allow to filter workers in interventions to activate or inactivate them, it's why contracts date would be more appropriated. (A baby can't drive a tractor even if he is born, and an employee who doesn't work any more in the farm is not necessary dead...).

**Comment by EmmaDorie** [comment]
see also #980
