### ISSUE TITLE
Error message when clicking too quickly on production dashboard

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#856]
In the production view, if clicking directly on campaign while the map is still charging, the message "We're sorry, something went wrong" appears whereas it's not a bug.
![screenshot - 28072016 - 15 19 39](https://cloud.githubusercontent.com/assets/11627573/17218907/ac8fd810-54e9-11e6-9c45-5f3edb434b85.png)

**Comment by burisu** [comment]
This seems to appear only in development mode. Mono-thread error?

**Comment by EmmaDorie** [comment]
No, it appears in production mode too if there is a large number of data.

**Comment by EmmaDorie** [comment]
This issue seems to be solved.
