### ISSUE TITLE
Cropping plan widget feature request

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#873]
v2.0.1 @clegris

Is it possible to add a link from parcel to its production page.
It would be nice, by clicking on a production to go directly to relevant activity like https://liwa.ekylibre.farm/backend/activity_productions/9

![widget_croppingplan](https://cloud.githubusercontent.com/assets/17082331/16149267/e709c6d8-348f-11e6-9250-f2eef2152eab.PNG)

**Comment by EmmaDorie** [comment]
Repeat and details in #984

**Comment by Nicephore17** [comment]
Yep, thank you.
