### ISSUE TITLE
Map displaying fails on dashboard after fullscreen view

### ISSUE THREAD

**Issue by kakahuete** [ekylibre/ekylibre#880]
I configured a new dashboard and added "map".
Process : click on fullscreen > Click on a parcel > Click on "show" > return on dashboard
Result : map cut + invisible parcels

![image](https://cloud.githubusercontent.com/assets/20659539/17358091/508aa2b8-5960-11e6-82ed-c0707f981db2.png)

**Comment by burisu** [comment]
Cannot reproduce

**Comment by Aquaj** [comment]
Reproduced by following the steps mentioned above.
Definitely due to the use of "previous page" to go back to the Dashboard, not sure if linked to turbolinks or not.
