### ISSUE TITLE
Purchase: convert balance into loss raise a StandardError

### ISSUE THREAD

**Issue by jleveau** [ekylibre/ekylibre#893]
while adding randomly some deals in a Purchase i raised this error by clicking convert balance into loss

![purchase_error](https://cloud.githubusercontent.com/assets/7250382/17359417/c8a5f4e0-5966-11e6-9b79-1a9920d3cc40.png)

**Comment by burisu** [comment]
We should forbids to modify affairs where a gap is registered and should propose to remove gap before do anything else
