### ISSUE TITLE
Currency used in "Draft Journal" is not the absolute one

### ISSUE THREAD

**Issue by kakahuete** [ekylibre/ekylibre#895]
The displayed currency here is "French Franc", in settings, "Euro" is chosen (in "Journals too)
![image](https://cloud.githubusercontent.com/assets/20659539/17359712/1fc6dc84-5968-11e6-904e-a52287f0a9ff.png)

**Comment by burisu** [comment]
Not sure to understand how it was possible in a normal way of use...
