### ISSUE TITLE
Adding a target distribution on a new product fails

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#901]
If the product isn't already distributed (i.e a new product), the target distribution creation fails.

**Comment by burisu** [comment]
I understand that we can't distribute product because it's not distributed, and I think I'm going wrong, can you give more explanations?

**Comment by Nyxelio** [comment]
If you want to create a distribution for a product, using the distribution form in the product page. It fails if you don't already have distributed product using unaffected products button (on campaign page)

This issue will be fixed when distributions will be created with interventions.

**Comment by Aquaj** [comment]
Closing because it's essentially #915.
