### ISSUE TITLE
Intervention creation form raise error if containing empty working period

### ISSUE THREAD

**Issue by jleveau** [ekylibre/ekylibre#902]
when creating a new intervention, if you click add working period and create without filling the fields, it raise an ArgumentError

**Comment by burisu** [comment]
How do you do that? I tried to leave fields empty but I can't

**Comment by Aquaj** [comment]
Could only empty one of them at a time.
Went through HTML modification to empty both of them, got error with 
`@messages = {`
`    :"working_periods.started_at"=>["Débuté le ne peut pas être vide", "Débuté le est invalide"],`
`    :"working_periods.stopped_at"=>["Arrêté le ne peut pas être vide", "Arrêté le est invalide"]`
`}`
Which seems to indicate that everything is working.

**Comment by burisu** [comment]
I close for now since no one can reproduce from interface
