### ISSUE TITLE
Removes mapQuest tile provider in available map backgrounds

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#904]
As MapQuest doesn't provide direct tile access anymore, we should consider disabling this provider. http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by burisu** [comment]
Already done in 5d7cebdda2388fd0c96e9f493569dd9a04d28422 but database not updated, should we remove it in user database?

**Comment by Nyxelio** [comment]
Oh my mistake I didn't see it. Yes, we could remove it from user database

**Comment by burisu** [comment]
For now, we have let user destroy himself the map_background. But today, since it's a "managed" map background, it's not possible
