### ISSUE TITLE
When making a new plant by sowing, no target repartition appears.

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#913]
After a sowing intervention, a plant have to be put in a production.
But, in this case, no button appears

![1](https://cloud.githubusercontent.com/assets/1838491/17365095/7698e392-5984-11e6-9693-da2114d1a7bc.png)

![2](https://cloud.githubusercontent.com/assets/1838491/17365126/a10f93fa-5984-11e6-9d6e-5cb88ee36a79.png)

**Comment by Nyxelio** [comment]
The button appears only if the plant has been target of an intervention.

**Comment by Aquaj** [comment]
Closign because it boils down to #915.
