### ISSUE TITLE
French (FRA) translations are missing

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#914]
- [x] Relationship/Entities : tasks/new --> État : "todo", "doing", "done"
- [x] Stocks/parcels --> "Human state name"
- [ ] Production/sensors/new --> "Api key"
- [x] Tools --> "Target name" in the dashboard
- [x] Tools/documents --> "file updated at", "file pages count", "file file size"
- [x] Tools/documents/new --> "file"
- [x] Tools/cap_statements --> "Human net surface area"
- [x] Settings/map_backgrounds/new --> "Subdomains", "Enabled"
- [x] Settings/sequences/new --> "Deliveries", "Inspections", "Inventories", "Opportunities", "Parcels"
- [x] Settings/taxes/new --> "Fixed asset collect account", "Fixed asset deduction account"
- [ ] Analyses/show > éléments > phases' values + growth level values.
- [x] Task/_form : Values for state.

**Comment by Aquaj** [comment]
I'd like to add to the mix :
- Analyses/show > éléments > phases' values + growth level values.
- Task/_form : Values for state.

**Comment by burisu** [comment]
Adds #996 for sensor parameter translations and #997 for nomenclature items translations
