### ISSUE TITLE
Redundant information in timeline on Entities.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#921]
In the Timeline under an Entity we display the interventions they've been a part of, but for each of those we mention the person was 'with' themselves even though the intervention wouldn't even be mentioned on their page if they weren't in it.

Example on the page of Mr X Y :
![redundance](https://cloud.githubusercontent.com/assets/2871879/17367679/3cfb10d0-5991-11e6-870c-6363dd517b66.png)

**Comment by burisu** [comment]
Very similar to #887
