### ISSUE TITLE
'To deposit' on checks during deposit creation.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#932]
I find it confusing that I must set an item "To deposit" to true if I want it to be considered "deposited".
All checks are 'to deposit' before they are deposited. And deposited checks are not 'to deposit', in my understanding, whereas on Ekylibre, this is reversed.

I agree it makes sense if we're creating our deposit before actually making the trip to the bank, but if you do after coming back from the bank (as I would to be sure the money is actually deposited before considering it is in Ekylibre) it doesn't make much sense.

How about "Include in deposit" or something along those lines that'd work for both?

**Comment by burisu** [comment]
The deposit are made to give the paper with the checks to the bank. As your proposal works for all cases, it's better to use.
