### ISSUE TITLE
Product update wrongly updates population.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#934]
On each update of a product, a new ProductMovement is created at its birth date, therefore augmenting the population each time it is updated.

**Comment by burisu** [comment]
I can't reproduce, have you more details?

**Comment by Aquaj** [comment]
It's quite easy to reproduce.

Newly created Matter :
![matter_population_increase_on_update_before_circled](https://cloud.githubusercontent.com/assets/2871879/17546207/4fa64fa6-5ee1-11e6-883f-330c21f9aaf9.png)
with details :
![matter_population_duplicate_on_update_details_circled](https://cloud.githubusercontent.com/assets/2871879/17546213/574ad2e0-5ee1-11e6-9bb8-80b11acff786.png)

Edition of it:
![matter_population_duplication_on_update_details_modified_circled](https://cloud.githubusercontent.com/assets/2871879/17546271/a18d07b0-5ee1-11e6-8e93-52d03d1a32e4.png)
![matter_population_duplication_on_update_after_circled](https://cloud.githubusercontent.com/assets/2871879/17546276/a72c6512-5ee1-11e6-9fdf-2dd64c338ce3.png)
