### ISSUE TITLE
Product population graph doesn't take into account the dead_on date.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#935]
Example:
Create a Matter with a _Born at_ date that's Aug. 2 and _Dead on_ that's Aug. 4 and a _Population_ of 500.
The Matter #show view shows a graph where the population is stable at 500 from Aug. 2 to Aug. 10 (August 10 seems to be a constant no matter how the other dates are changed, I think it's Today + 1 week.)

**Comment by burisu** [comment]
Yes, it doesn't care since `dead_at` doesn't produce a negative product movement. I'll transfer it in 2.1.0 since it's not blocking but "only" a few confusing for user
