### ISSUE TITLE
Edition of an inventory keeps us on the form page without confirmation of changes.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#937]
It feels as if it had bugged, even though the changes really have been taken into account.
It would be better to redirect to the list of inventories after valdiation or at least to display a flash saying the changes were successful.

**Comment by burisu** [comment]
I can't reproduce with test data, @Aquaj have you more details on context?

**Comment by Aquaj** [comment]
Grouped in #998.
