### ISSUE TITLE
Distribute unaffected products is too long to load.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#941]
I find the *Distribute unaffected products* unclear before going on the actual page, which isn't too bad in itself but the page took over 3 minutes to load with my data set.

In production it'd probably timeout, therefore making it both cryptic and unusable.

**Comment by burisu** [comment]
I use `includes` to preload data and remove repetition of queries. We'll need to reopen issue if it is not sufficient.
