### ISSUE TITLE
Change the items number in the dashboard configurations

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#946]
Actually, we have a limit of item (the windows of the dashboard) in the same box when we edit the dashboard. But when we have 3 or 4 items in the same box, we can't see properly the informations of the items.

**Comment by burisu** [comment]
We need to use media queries to fit well with higher resolution too:

- 1920x1080: 4 cells
- 2560x1440: 5 cells
- 3840x2160: 8 cells
