### ISSUE TITLE
Bug when i print an inventory

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#947]
When i print an inventory, i have this bug : 

![bug_inventaire](https://cloud.githubusercontent.com/assets/1082026/17370321/e1a236b8-599b-11e6-9f35-4cd2f1862030.png)

**Comment by burisu** [comment]
Fixed by @Nyxelio in bc8bc2cabb4a89c40009683426a2e4de47ee5323 but templates must not be reloaded. See #985 for the remaining problem.
