### ISSUE TITLE
☆ symbol for drawing a polygon is unclear.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#948]
I think the ☆ symbol as the button to start drawing is confusing, ☆ is usually the symbol to set something as a favorite, or to rate something, the ability to draw is classically more represented by ✎, ✍  or other equivalents.

**Comment by Nyxelio** [comment]
If you want to change the symbol, you might consider polygon symbol as used by Leaflet Draw
![screenshot 6](https://cloud.githubusercontent.com/assets/9863590/17393816/41b33018-5a26-11e6-9242-5c56caea8d69.png)
