### ISSUE TITLE
Issues for the contacts and the organizations ?

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#965]
Should we keep the issues for the contacts and organizations ? Because when i add a new issue for contact for example, if i had intervention for this issue, i'm mandatory to fill animals group field or a caregiver.

I think the issues for contacts and organizations is not much used.

**Comment by burisu** [comment]
In first time, we will remove polymorphism on targets of `Issue` to be only "product-linkable". This will permit to generate a better context for actions.
