### ISSUE TITLE
nil:NilClass when i retrieve indicators from sensor

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#973]
When i retrieve indicators from sensor, i have the message "undefined method `[]' for nil:NilClass".

![erreur_capteurs](https://cloud.githubusercontent.com/assets/1082026/17394186/09021e26-5a28-11e6-9e68-b09504d9cac8.png)

**Comment by Aquaj** [comment]
I cannot reproduce, even when testing on the pepseed dataset.
Did you input anything specific in the sensor's settings ?
