### ISSUE TITLE
Geolocation input field on equipment edit page doesn't work on Chrome and Vivaldi browsers

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#975]
When i click in the matters list on equipment, and edit this equipment, i have a geolocalisation input field and not the map.

![issue](https://cloud.githubusercontent.com/assets/1082026/17394322/cb31a3d6-5a28-11e6-9d84-7dbef688e51a.png)

**Comment by Nyxelio** [comment]
It doesn't occur, could you please check if you have JS errors ?

**Comment by PH64** [comment]
The problem seems not to occur in 2.3.0
