### ISSUE TITLE
Improve production Menu

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#978]
New proposition is for production menu is : 
**Production**
 - Production --> Instead of "Activities"
    - Activities (Activités) --> Instead of "Campaign"
    - Interventions (Interventions) --> no change
 - Quality (Qualité) --> new submenu
    - Analysis (Analyses) --> no change
    - Issues (Incidents) --> Replace "Issues" menu in "tools" part
    - Inspections (Agréages)  --> no change
 - Field distribution (Parcellaire) --> Instead of "Land parcels"
    - Cultivable zones (Zones cultivables)  --> no change
    - Land parcels (Parcelles)  --> Replace "Land parcels" menu in "Settings" part - Warning : Remove button "new" of this view !!
    - Crops (Cultures)  --> no change
 - Sensors --> no change

**Comment by Nicephore17** [comment]
"Inspection" label will replace "product grading" ?

**Comment by EmmaDorie** [comment]
No, sorry I make a mistake because "inspection" is the term used in the code.

**Comment by PH64** [comment]
@Aquaj, Production menu seems to be always the same in local installation
