### ISSUE TITLE
Improve harvesting procedure for the case where "quantity" is unkown

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#981]
During a harvesting intervention, user doesn't always know the quantity of products harvested.
1) Add a boolean in the procedure to allow the user to check if "quantity is unknown for the moment"
2) Then the intervention should registered a product in the stocks with a quantity=0
3) Harvesting interventions which don't have quantity registered must be highlighted and a new view should be developed to registered quickly the quantity post intervention.
![demo nouvelle intervention 2016-08-04 12-20-50](https://cloud.githubusercontent.com/assets/11627573/17398609/e8f3c9ca-5a3d-11e6-8ee8-0262d58a9e69.png)

**Comment by Nicephore17** [comment]
We had the problem in our tests. We don't know the actual quantity before selling as the weight station in used before shipment. In some case (for forage production) we weight one or tow trailer to have a approx harvested quantity.

One of my question was: is it possible to update harvest production base on invoice as a invoice "know" the weight of a product/lot ?
