### ISSUE TITLE
Add a way to kill plant with an intervention or an issue

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#982]
For the moment, user can only kill his crops by adding a "dead_at" date in the "plant" view.
To simplify the recording of this information, a case must be add to allow the user to check if an intervention or an issue destroy the plant. 
Interventions and issues that will need to add this box must be defined.

**Comment by Nicephore17** [comment]
For info, in our procedure we have to way to kill a crop:
- Disk intervention
- Herbicide

Obviously crops should be killed for relevant soil working ;-)

**Comment by Nyxelio** [comment]
Fixed by #1602 & #1605
