### ISSUE TITLE
Improve "Cropping plan" graph in production dashboard

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#984]
This graph becomes illegible when there are too much informations : name of land parcels are cutting and there are too much subdivisions.

The solution would be to remove the most detailed level and just keep cutting by activities.

Flyover, values to display in the pop up for an activity : 
- Percentage of the net surface area
- Net surface area
- Number of productions in this activity

To finish, if possible, add a link from name of activity to open the activities view.

**Comment by Nicephore17** [comment]
\o/
