### ISSUE TITLE
Error in modification of an activity

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#999]
Showing /home/pierre/projects/ekylibre/app/views/backend/activities/_form.html.haml where line #5 raised:

Invalid nomenclature reflection: production_system

Extracted source (around line #25):
      klass = @object.class
      reflection = klass.nomenclature_reflections[association]
      raise ArgumentError, "Invalid nomenclature reflection: #{association}" unless reflection
      options[:collection] ||= reflection.klass.selection
      options[:label] ||= klass.human_attribute_name(association)
      input(reflection.foreign_key, options)

**Comment by burisu** [comment]
Fixed by 398514c25a0b3d470175fed4ce34419ee45e26cd
